### ISSUE TITLE
Twitter tracker bot based on Orbit

### ISSUE THREAD

**Issue by kristoferlund** [CommonsBuild/coordination#1001]

**Comment by AL0YSI0US** [comment]
Can I be present whenever someone's hacking at this?
I want to learn more about orbit / webhooks (if that's what's involved) deeply interested with fly on the wall energy. 🪰

**Comment by kristoferlund** [comment]
@Vyvy-vi will be looking into this after taking a stab at the meeting tracker bot.

**Comment by kristoferlund** [comment]
@Vyvy-vi we didn't talk about the Orbit option today. Let's not rule that out. If Orbit data could be fed into SourceCred reasonably easy perhaps that is a better option than developing the Twitter bot we talked about (See #1047). Could you investigate both tracks and propose which one to choose?

**Comment by mount-manu** [comment]
**Vyvy-vi's Update:** This issue did not gain approval so we might as well close it.
