### ISSUE TITLE
Copy for T&C / Code of Conduct 

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#1002]
## 👇🏽  What is this issue about? Give as much detail as you can. 
The Terms and Conditions for joining the server need to be confirmed. 

They current copy is in the Onboarding journey frame in this miro board:
https://miro.com/app/board/o9J_lYcRTik=/

(related to #978, the issue to finalize the survey questions)

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by tamarandom** [comment]
Code of conduct: https://app.gitbook.com/o/-MRe_DImEWCFDsZ_TQd2/s/-MRe_M_mUIIB11A-MQyZ/code-of-conduct

**Comment by eduardovegap** [comment]
Working document for the Revisited T&C (first page)

https://docs.google.com/document/d/1h0J0L0VAJ2UZH_Jwy1n6M2kI4ozlmlOV-Mb3uFH78yQ/edit

**Comment by tamarandom** [comment]
Done
