### ISSUE TITLE
Promotion for the Book Club - visual design

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#1007]
## 👇🏽  What is this issue about? Give as much detail as you can. 
Hey @acidlazzer ! Would you be able to create a graphic to promote the Book Club?

The two people that have the details about it are:
witwiki#0518
Mettodo#7010

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. Graphic that promoted the what, where and when for the Book Club Witwiki and Mettodo are kicking off
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@chuygarcia92 and  Ivy and David (for twitter promotion)

**Comment by acidlazzer** [comment]
Sure! I got this 👍

**Comment by tamarandom** [comment]
Yay!! Think we can have something we can use to promote the book club before Thurs or Friday? The book club happens on Saturday. CC: @iviangita

**Comment by acidlazzer** [comment]
![55432634-7F4F-49B0-ACBC-034E151CF344](https://user-images.githubusercontent.com/84995397/137013844-45201633-0ee3-4295-9d0b-14d88b78460b.jpeg)
Approved by Mettodo :)

**Comment by tamarandom** [comment]
Might I ask that we include an image of the book itself instead of the book emoji? 

https://books.google.fr/books/about/The_Sovereign_Individual.html?id=WuQblPwwAjgC&printsec=frontcover&source=kp_read_button&hl=en&newbks=1&newbks_redir=1&redir_esc=y

**Comment by acidlazzer** [comment]
Updated :D 
![book club3](https://user-images.githubusercontent.com/84995397/137048104-e579f832-97a6-4240-aa16-a6d51645e4ee.jpg)

**Comment by tamarandom** [comment]
Thanks @acidlazzer. Can you please send an editable file that I can make some
small changes to rather than asking you.

For example, “4am EST” certainly looks bizarre, right? Better we share the time zones that this club is intended to include! 

I am happy to make those small changes myself.

**Comment by tamarandom** [comment]
![book club2.jpg](https://images.zenhubusercontent.com/5faaa1d038c6409364f7830c/6f6d6ffa-2e9b-45ef-bb18-48319231c94c)

Will check with Witwiki and @mettodo on this version. Closing now and THANKS for taking this on, @acidlazzer !!
