### ISSUE TITLE
Pseudonym random generator dictionary

### ISSUE THREAD

**Issue by kristoferlund** [CommonsBuild/coordination#1008]
## 👇🏽  What is this issue about? 
We need a dictionary to be able to generate random pseudonyms used during quantification. 

Either one long list, ideally 500 names or more.

Or even better, two shorter lists that can be combined, creating more possible and fun combinations.

## ✨  What does success look like?
1. One or two dictionary files in csv format 

## Who should be part of the Advice Process? 
@liviade1  suggested making this into a hack party. 

## 👀  Who should be in the loop about this issue?
@liviade1

**Comment by divine-comedian** [comment]
here's a google sheet we can export in csv when it's ready - 

https://docs.google.com/spreadsheets/d/1vGGenNyCzKl0Brhp_e4MFfCKryIfCV77cpwU-OvIiH8/edit?usp=sharing

**Comment by kristoferlund** [comment]
I added an "adjective tab" and a rand formula to try out the combination. 

Algorithm says for example: 

```
Melodic Husky
Red Fettucini Carbonara
Blue Lotus
Noisy Cariblanco
Quiet Narwhal
Long Falcon
Prehistoric Fox
Slow Unicorn
Future Panther
Rapid Eagle
Rhythmic Lasagna
```

**Comment by tamarandom** [comment]
I really enjoy reading these lists! They make me laugh a lot.
