### ISSUE TITLE
Discord and Forum Analytics

### ISSUE THREAD

**Issue by Zeptimus** [CommonsBuild/coordination#1009]
## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by tamarandom** [comment]
Can we add analytics for Medium too??

**Comment by Zeptimus** [comment]
Medium its probably going to be cover by hubspot it feels its more like a comms issue like twitter annalytics. What do you think @chuygarcia92 ?

**Comment by Zeptimus** [comment]
Done!
