### ISSUE TITLE
Retrospective action: select 3 forum posts that could become blog posts

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#1019]
## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by tamarandom** [comment]
@natenatesoo volunteered one!

**Comment by tamarandom** [comment]
Looping in @mount-manu

**Comment by natenatesoo** [comment]
Rules of Praise Quantification!

**Comment by tamarandom** [comment]
Idea: the new dates would be a good forum post to convert to a medium post.

**Comment by tamarandom** [comment]
Hey @natenatesoo - going to close this issue since we have the TEC writers guild getting momentum on creating new articles.
