### ISSUE TITLE
Ethereum based forum accounts

### ISSUE THREAD

**Issue by Zeptimus** [CommonsBuild/coordination#1022]
## 👇🏽  What is this issue about? Give as much detail as you can. 
 Tam saw the option to create an account using an Ethereum address on Gnosis forum and we think its a very cool feature to add.  @Vyvy-vi  would you be interested on give it a look? They also use Discourse as we do

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🔗  Are there links or docs related to this issue?
https://forum.tecommons.org/t/ethereum-based-forum-accounts-good-idea-or-not-so-much/668

## 👀  Who should be in the loop about this issue?
@
@Vyvy-vi

**Comment by tamarandom** [comment]
Closing.
