### ISSUE TITLE
Reorganization of Discord Menu 

### ISSUE THREAD

**Issue by eduardovegap** [CommonsBuild/coordination#1023]
## 👇🏽  What is this issue about? Give as much detail as you can. 

We need a better alignment of the menus and channels of the discord server, so the idea is to present and get approval on a proposal that's sync with the onboarding journey. 

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. Having the menus and the pin/content messages ready. 
2. Having the channel distribution sync with the onboarding journey
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@tamarandom 

## 🔗  Are there links or docs related to this issue?
https://docs.google.com/document/d/17ArOa1BikAk20Czf1vbmZjT_ll0OQSc9rUrdFm9SAGc/edit#

## 👀  Who should be in the loop about this issue?
@

**Comment by gideonro** [comment]
Just added link to the audit document.

**Comment by tamarandom** [comment]
Update: this is ready on the Staging discord server.

**Comment by tamarandom** [comment]
Launched! Closing this issue now.
