### ISSUE TITLE
Member experience Flow Chart

### ISSUE THREAD

**Issue by eduardovegap** [CommonsBuild/coordination#1025]
## 👇🏽  What is this issue about? Give as much detail as you can. 

We want to have a visual understanding of the onboarding journey, what happens after validation, so the process could be clear and adapted.

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. Having a consensus of the flow chart and agreement upon.
2. implementation of the flow chart into the corresponding bot. 
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by mcsmith89** [comment]
@tamarandom @eduardovegap - LBS has added an awesome additional to the original doc I created: 
https://docs.google.com/document/d/1h0J0L0VAJ2UZH_Jwy1n6M2kI4ozlmlOV-Mb3uFH78yQ/edit#heading=h.11a9d6ihw8su

I vote we consider v3 of the diagram section that LBS has created as our new working diagram. Can we add them to this GH issue? I think we can keep the original document as a central area for all of the things going on (Content, etc.) but the Miro board and documents LBS has created are great for fleshing our this final vision. Thoughts?
