### ISSUE TITLE
Medium Article from Forum Post: Praise Quant and Rules

### ISSUE THREAD

**Issue by natenatesoo** [CommonsBuild/coordination#1027]
## 👇🏽  What is this issue about? Give as much detail as you can. 
I will be writing a Medium Article following the Forum Post by @liviade1 about the rules of praise quantification.  

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.  Adaptation of this forum post into a Medium Article.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@liviade1 

## 🔗  Are there links or docs related to this issue?
https://forum.tecommons.org/t/rules-of-praise-and-quantification/667

## 👀  Who should be in the loop about this issue?
@liviade1

**Comment by natenatesoo** [comment]
Written, not posted.  Add to next sprint (to start a Forum Insight Sections for Medium)

**Comment by chuygarcia92** [comment]
@Zeptimus has been working in a GREAT quantifier onboarding document, final one should be ready pretty soon but here's a draft:

https://docs.google.com/document/d/1I7OZrkGZaHUCQ1Ji-4B0DGWoHK1slECzoXQLvzCV_YM/edit#heading=h.qmtl1071sggz

**Comment by chuygarcia92** [comment]
DONE! Praise @Zeptimus @divine-comedian @mcsmith89 for the great job on this:

https://forum.tecommons.org/t/quantifier-onboarding/825

**Comment by chuygarcia92** [comment]
Still needs to be uploaded to medium!
