### ISSUE TITLE
Record the Orientation weekly call 

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#1036]
## 👇🏽  What is this issue about? Give as much detail as you can. 
On the call now, it just occurred to me that we are not recording these. Wondering whether anyone things there is any reason *not* to record them. I am leaning to us recording them going forward!

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@tamarandom @eduardovegap @iviangita @Zeptimus 

## 👀  Who should be in the loop about this issue?
@

**Comment by Zeptimus** [comment]
i was recording those back in the days, but then stopped coz they were the same every week but if we wanna get them im available at that time normally

**Comment by tamarandom** [comment]
I see this point. I am thinking we can record a few just to have them available in a playlist on Youtube so newcomers can easily find them and see the presentation if they can't make the meeting itself. Maybe we record the next 3-4? What do you think?

**Comment by Zeptimus** [comment]
thats a good point, lets do it!

**Comment by tamarandom** [comment]
Did it this week!

**Comment by eduardovegap** [comment]
This was accomplished, but did we record a call with the new orientation deck?

**Comment by Zeptimus** [comment]
Ill get it this week edu last week didnt remeber of recording that call

**Comment by tamarandom** [comment]
I had to skip the orientation call this week but @Zeptimus got this one!

**Comment by tamarandom** [comment]
@eduardovegap @Zeptimus @iviangita I will not be able to do this for these 2 weeks: Feb 16 & 25. Will it be possible for someone to cover those days?

**Comment by Zeptimus** [comment]
TEC Recorder can get it :D

**Comment by natenatesoo** [comment]
Closing this issue due to lack of need.

**Comment by tamarandom** [comment]
Hey @Zeptimus - is this one of the calls that Bear is taking on?

**Comment by Zeptimus** [comment]
Hey tam, no i could ask him. Did the orientation call changed format again so we get a couple of them or we just want to get them all as normal syncs?

**Comment by tamarandom** [comment]
Same format. What do you think @eduardovegap? Should we record each one as a weekly call or stop recording them now that we have a handful of the new format?

**Comment by tamarandom** [comment]
Closing and removing the #repeating tag. If we want to record future orientation, we'll have to request again from Transparency WG.
