### ISSUE TITLE
Do we have documentation for Praise bot / system? 

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#1037]
## 👇🏽  What is this issue about? Give as much detail as you can. 
We are being asked on the Orientation call whether someone can deploy Praise on their own Discord servers for their own community. Do we have docs or a github repo we can point them to? It was requested by Yonks. 

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. 
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@GriffGreen @Vyvy-vi @krisjpi 

## 👀  Who should be in the loop about this issue?
@

**Comment by TeamYonks** [comment]
Thanks @tamarandom for opening this issue!!

**Comment by GriffGreen** [comment]
We are completely revamping the Praise system... so they might want to consider checking that out...

That said... here is the Telegram bot:
https://github.com/commons-stack/CommonsStackBot

I think this is the Discord Bot:
https://github.com/hurek/Praise-Bot-Discord

@hurek or @Vyvy-vi can confirm that this is the most up-to-date version of the discord bot... there might be another repo floating around... not sure... maybe we can merge it into Commons Build?

**Comment by tamarandom** [comment]
Thanks @GriffGreen and best luck @TeamYonks! 

Closing.
