### ISSUE TITLE
New banners for Stewards and Communitas meetings

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#1038]
## 👇🏽  What is this issue about? Give as much detail as you can. 
@acidlazzer would you have cycles to work with me on new banners for the new call announcement bot? Let me know when you can fit this into your schedule.

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. New call announcement banners for Stewards and Communitas WG calls
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@eduardovegap @chuygarcia92 @iviangita  @tamarandom

**Comment by acidlazzer** [comment]
I am in! Text you at discord :)

**Comment by tamarandom** [comment]
These are the slides that were originally made by @markoprljic. I made a few changes to a few in order to test the new sesh.fyi bot. I like that it's in slides format because that's easier for most stewards to edit vs a psd. Want you @acidlazzer to know where they live!

https://docs.google.com/presentation/d/18qTPGk4yIa9ql2qj2y9gRhIoTM-z80NCc8w_MWi5rlY/edit#slide=id.gd611fbdc33_0_53

**Comment by tamarandom** [comment]
@acidlazzer - do you have a location with the latest versions of these banners? In whatever format they are in. @Vyvy-vi  will use them for testing.

**Comment by tamarandom** [comment]
@acidlazzer shared!!! https://drive.google.com/drive/folders/1dnNzaDHHl7BVskkRMyAUgJ423GsRnBa1?usp=sharing

**Comment by tamarandom** [comment]
Since we moved to Events (native Discord) we aren't using these banners anymore. Closing
