### ISSUE TITLE
Update Comms WG section on Gitbook 

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#1039]
## 👇🏽  What is this issue about? Give as much detail as you can. 

https://app.gitbook.com/o/-MRe_DImEWCFDsZ_TQd2/s/-MRe_M_mUIIB11A-MQyZ/cultural-components/communications

![Screen Shot 2021-10-21 at 10.14.17 PM.png](https://images.zenhubusercontent.com/5faaa1d038c6409364f7830c/6b512087-f667-40a6-b003-86986ccf1d5e)

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. Comms section reflect the correct Stewards, members, manifesto, and direction to T.E.A.M (fka CommsDAO)
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@chuygarcia92 @mount-manu 

## 👀  Who should be in the loop about this issue?
@

**Comment by chuygarcia92** [comment]
I'll make sure the new comms manifesto gets on github as soon as we put it up next sprint

**Comment by chuygarcia92** [comment]
this was updated with temporary but valid information while the new documentation is ready along with the funding proposal

**Comment by GriffGreen** [comment]
Hoping to update this after the proposal is up

**Comment by mount-manu** [comment]
**Chuy Update:** @Costa91 was going to look into this, any updates Costa?

**Comment by eduardovegap** [comment]
The version in the gitbook is the most updated version. It needs more polishing and crossreferencing.
