### ISSUE TITLE
Setup the Reward Board / Aragon Rewards DAO

### ISSUE THREAD

**Issue by kristoferlund** [CommonsBuild/coordination#1040]
See details at Notion: https://www.notion.so/fmckl/Setup-the-Aragon-Rewards-DAO-Mitch-Mateodaza-bdadac3a161e416691ac40396cccfb35

**Comment by divine-comedian** [comment]
Livia made a great point that we have an existing Rewards DAO so for the sake of simplicity we could use this same DAO - it seems to have all the required apps and the current voting settings seem reasonable:
> vote duration is of 24h.
Quorum is 41% - so at least 3 people have to vote on every round
Support required is 81% - so 1 person can block a vote if up to 4 people are voting, and 2 people can block the vote in any scenario.



https://xdai.aragon.blossom.software/#/tecdrops/

**Comment by divine-comedian** [comment]
JK here is the new reward board with proper tokens minted 

https://xdai.aragon.blossom.software/#/rewardboardtec/

**Comment by kristoferlund** [comment]
@divine-comedian  Is this the DAO with 24h vote period?

**Comment by divine-comedian** [comment]
> @divine-comedian Is this the DAO with 24h vote period?

now, yes
