### ISSUE TITLE
Medium, Youtube and other platform analytics

### ISSUE THREAD

**Issue by iviangita** [CommonsBuild/coordination#1041]
## 👇🏽  What is this issue about? Give as much detail as you can. 
Start generating analytics data for our platforms until a strategic group handles it (Check the last Labs call from YGG where he developed a tool to analyse Medium profiles)

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@Zeptimus

**Comment by iviangita** [comment]
Here's the report: https://docs.google.com/presentation/d/1Df2ajD3JneQr6bez82WgRz6M-_QNccRujEWydRRUMeY/edit?usp=sharing

**Comment by Zeptimus** [comment]
done ! :D
