### ISSUE TITLE
Add Snapshot to https://tecommons.org/

### ISSUE THREAD

**Issue by iviangita** [CommonsBuild/coordination#1042]
## 👇🏽  What is this issue about? Give as much detail as you can. 
The TEC Snapshot link should be added to the website for easier access to the community since it will be used in making decisions

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@Zeptimus

**Comment by iviangita** [comment]
UPDATE: Already reached out to @kristoferlund to make the changes to the website 🙏

**Comment by tamarandom** [comment]
boardroom link instead of snapshot! 
https://app.boardroom.info/tecommons

**Comment by kristoferlund** [comment]
Added the icon. A bit unclear what would be the best link text though. We are not linking to Boardroom as such but to the voting page that allows you to interact with a Snapshot vote. 

![image](https://user-images.githubusercontent.com/9698363/139694450-d37e85c9-edbb-4324-9287-1a75ac2fa99f.png)

**Comment by Zeptimus** [comment]
Close

**Comment by tamarandom** [comment]
Nice!
