### ISSUE TITLE
Update the Transparency WG funding proposal

### ISSUE THREAD

**Issue by iviangita** [CommonsBuild/coordination#1043]
## 👇🏽  What is this issue about? Give as much detail as you can. 
We will add Transparency Training to our proposal so we can go back to it when we're ready. We will also make the final changes so the proposal is more comprehensible.

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@Zeptimus

**Comment by iviangita** [comment]
We have updated the funding proposal, but still confirming the number of hours for setting up Dune analytics - @Zeptimus is on top of it

https://docs.google.com/document/d/1FrCvZz_otDLVop2nFGkRveTNz84hME-40KP-FEQNfso/edit?usp=sharing

**Comment by Zeptimus** [comment]
Done
