### ISSUE TITLE
Training guide for new Guides

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#1044]
## 👇🏽  What is this issue about? Give as much detail as you can. 
@eduardovegap is doing all of the welcoming to Discord single handedly. Having 2-3 other Guides can help take some of this responsibility off his shoulders. 

While we are working on the Onboarding experience, creating a simple guide for new TEC Guides will make it easier to onboard new folk in that role. 

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@ LBS @mcsmith89 @tamarandom 

## 👀  Who should be in the loop about this issue?
@

**Comment by mcsmith89** [comment]
Thanks! I was just discussing this with LBS today on our check-in. This seems like the natural next priority post MVP survey/onboard question launch?

**Comment by tamarandom** [comment]
Idea: Check whether Gravitons might be interested in this type of role? (thanks Durgadas)

**Comment by eduardovegap** [comment]
Working document: https://docs.google.com/document/d/1y4kaZM5nWypg1iVf4m-7yvv5BDB6odxwrhpnqGsX0ZE/edit

**Comment by tamarandom** [comment]
Good, closed! Woo.
