### ISSUE TITLE
Actionable actions and follow-ups from the TEC-TE Stewards' council

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#1046]
## 👇🏽  What is this issue about? Give as much detail as you can. 
Notes here: https://docs.google.com/document/d/1T1XxYQPHyAN6biQSlThLLeFO7Ihb8hidjJKd5MeKb7Y/edit

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. What does an immediate, short and long term actionable plan look like?
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by tamarandom** [comment]
This is where we will be tracking actions to take for now: https://docs.google.com/spreadsheets/u/1/d/1vKr991CRiAWR42UA31MeFLp3n6hBqZ3cRtEtiIcC5j8/edit?usp=drive_web&ouid=100603646152821457059

**Comment by tamarandom** [comment]
There is a call with TE Academy to talk our discords on Dec 15 at 3pm CET. 

@Vyvy-vi @mcsmith89 @eduardovegap @natenatesoo (prob to early for you!) : any of you can make it?

**Comment by tamarandom** [comment]
and @Zeptimus ? ;)

**Comment by mcsmith89** [comment]
What's the message and knowledge expectations to represent TEC on this @tamarandom? Right now that would be 09:00 my time, and it is highly likely I can attend :) (95% confidence).

**Comment by Zeptimus** [comment]
i can attend it too is it on our server or on te server should we create an event?

**Comment by Vyvy-vi** [comment]
I could attend

**Comment by tamarandom** [comment]
Awesome! I tried to add you all to the cal entry but I don't think I have the perms to do so. I'll create a twin cal entry so I can invite you. It will be on Zoom.... https://us02web.zoom.us/j/6985323627?pwd=YmxXaWNrdk1uSmV5bUFsaTJEWEtNZz09

**Comment by tamarandom** [comment]
Done!

**Comment by tamarandom** [comment]
@mcsmith89 it will be a brainstorm/prioritization of how we can better link the TEA and TEC discord communities. Cross server events, channel bridges, and other ideas to foster community closeness.

**Comment by mcsmith89** [comment]
Sounds like a plan @tamarandom

**Comment by tamarandom** [comment]
Output was the TEA x TEC joint Introduction to TE monthly which went very well! Thanks to @mcsmith89 and Heater and Patti for getting that done! Thanks to @JuankBell for presenting the TEC there! Ongoing, we are invited by TEA to continue to joint host that call. Current thinking is that the Stewards will rotate in presenting the TEC on that call. 

This is the full list of brainstorm from the Stewards council and I'd invite anyone that wants to move the dial on any of these to reach out to @mcsmith89 or myself or any Steward!
Ideas about strengthening the bind:
More TEC coming to TE Academy programs, learning more about TE 
Invitations to the community when there are new courses offered 
Promote and support TE projects across entire ecosystem, wherever they need support 
Communications partnerships
Community cultural partnerships 
Biggest frustration: getting support from TE. Params, rewards, etc. Feels like we are flying blind when looking for guidance on building the tools we are building. TE Hotline.
Not interacting with TE discord for lack of bandwidth. Would be easier if they were in the same place. Feels like TEC feels like more and more filled with people that don’t really know TE. The TE is filled with them.
See TE channel as the TE Academy. Feels bummer there is not much cross-pollination. Difficulty keeping up with 2 servers all the time. Maybe can build more channel links. Or a shared chat - where proposals are happening in the ecosystem. (Amplify for proposals, what is needed, who is involved).
Some bridges stopped working. Bridge maintenance needed. 
Gap in knowledge. Course for people in TEC that want to go father/deeper on the learning curve. 
Calendar for TE events that are open to TEC to join.
Having calls or TE server or vice versa. 
Communication collaborations in preparation. Offering TE promotion as a public good.
Discord wizards, only Kai has experience with channel bridging. Maybe get a backup for that.
Would love to start doing out community call on the TE Discord (at Commons upgrade). Would love to make TEC discord only avail to TEC token holders. Have TE public goods work in the TE discord and DAO decisions in the TEC. 
Looking fwd to T.E.A.M coming to full force. 
Ocean thread, sensing people value applied research over other research. Have way to promote te proposals. 
Priority brining legitimacy to TE, produce and publicize research 
Interviews TE on the TEC, blog posts
Monthly project spotlight, 2-3 projects presenting in this startup pitch style session
#amplify-proposals to get community support behind TE proposals 
Monthly introduction to TE (get schedule, promote in TEC)
TE has lots of video and content. Can be used for self-study.

**Comment by tamarandom** [comment]
There is a lot of momentum on these actions. Closing this issue now.
