### ISSUE TITLE
Retro action: focus on params parties "live token engineering"

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#1054]
## 👇🏽  What is this issue about? Give as much detail as you can. 
- Make a list of discord communities to target
- Frame the Params Party as Education

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.  Params parties on other discord servers 
2. Messaging beyond "params parties", more focused on educational aspects and live token engineering 
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by chuygarcia92** [comment]
This is an initial list of the communities I'll approach to organize Param Parties starting around Nov 10th and until Nov 18th:
• 1Hive
• Metagame
• ForefrontDAO
• dOrg
• Gitcoin
• VitaDAO
• PrimeDAO
• Ocean Protocol
• Symmetric
• BrightID
• Shapeshift

**Comment by divine-comedian** [comment]
link for TEC param party calendar 

https://calendar.google.com/calendar/u/0?cid=ZHRpbnQzYmE2NnY0cDJqN25uZWdlZnB2dmdAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ

**Comment by Big-Gray-Al** [comment]
You might also consider rally.io  they are focused on the creator economy. That was my entry point to the ethereum ecosystem and they have multiple new creators launching coins every week.  So params is a somewhat constant point of discussion for their coin creators

**Comment by divine-comedian** [comment]
> You might also consider rally.io they are focused on the creator economy. That was my entry point to the ethereum ecosystem and they have multiple new creators launching coins every week. So params is a somewhat constant point of discussion for their coin creators

interesting! thanks for the reference

**Comment by chuygarcia92** [comment]
still doing local (TEC Discord server) params parties next week, other communities were a success last week!

**Comment by tamarandom** [comment]
Cleanup. This is well done. Closing this issue.
