### ISSUE TITLE
Hatcher relations campaign: the time is now to design our economy 

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#1055]
## 👇🏽  What is this issue about? Give as much detail as you can. 
Reach out to our Hatchers to let them know about where we are with the CCD and that the time is now to configure our economy.

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. Draft message
2. Individual outreach, invitations to params parties
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by eduardovegap** [comment]
Updated the document: https://docs.google.com/spreadsheets/u/1/d/169yWkwvAI_t1ucN5yRdFK4-EbDuWcIMKazScO-dCw6Q/edit#gid=1160000136

Done.
