### ISSUE TITLE
Initial buy-in: get this voted on

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#1057]
## 👇🏽  What is this issue about? Give as much detail as you can. 
Next steps are:
- finalize the choice for the multi-sig holders
- edit the proposal, incorporate some feedback from the forum
- put the proposal up for vote on Snapshot
- create the gnosis safe 

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by Zeptimus** [comment]
https://app.boardroom.info/tecommons/proposal/cHJvcG9zYWw6dG9rZW4tZW5naW5lZXJpbmctY29tbW9uczpkZWZhdWx0OjB4MTEzZWZmNjA3MTBhNzM0MGQzNWVlMThkYzUxMTkxY2ZlODU3M2I2MTczMDdmMGM1NTA4OWU2ZWQ4YTg1NzUzNQ==

Multisig vote will come today after this finish

**Comment by tamarandom** [comment]
Hey Zep, so we close this after the vote closes and the new vote on the multi-sig holders gets passed too. Sound good? I assigned it to you as the relieving quarterback while @divine-comedian is on vacay.

**Comment by tamarandom** [comment]
Since this vote passed, closing. Opened #1086 to track the multisig nomination vote.
