### ISSUE TITLE
Proposal / TE Academy 

### ISSUE THREAD

**Issue by GriffGreen** [CommonsBuild/coordination#106]

**Comment by liviade1** [comment]
Jess is talking to Angela today

**Comment by jessicazartler** [comment]
Had a great call :D Angela is thinking about her ask for the community and will submit in January, will follow up then :D

**Comment by jessicazartler** [comment]
In talks with Angela, she is super busy with Gitcoin grants research group -- I will ask her again next week on our next call together

**Comment by eduardovegap** [comment]
Will move the tracking of this proposal to TEC Curate document, if they propose or any other update, please follow it up here: https://docs.google.com/spreadsheets/d/1RJK8gPqUoRfehX9e60sTCMAM_R1rI2CuiV1r-i3wAXQ/edit#gid=875503092

**Comment by jessicazartler** [comment]
Sure, will do - talking with Nathalia, new TE Academy team member about getting the proposal in before the hatch - thanks for following up!
