### ISSUE TITLE
Gene's outreach to Hatchers Campaign

### ISSUE THREAD

**Issue by eduardovegap** [CommonsBuild/coordination#1062]
## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 🔗  Are there links or docs related to this issue?
https://docs.google.com/spreadsheets/d/169yWkwvAI_t1ucN5yRdFK4-EbDuWcIMKazScO-dCw6Q/edit#gid=361654952

## 👀  Who should be in the loop about this issue?
@

**Comment by tamarandom** [comment]
Closing!
