### ISSUE TITLE
Update credentials document

### ISSUE THREAD

**Issue by iviangita** [CommonsBuild/coordination#1066]
## 👇🏽  What is this issue about? Give as much detail as you can. 
Time to update the credentials document since some contributors have left and some have joined

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@Zeptimus

**Comment by Zeptimus** [comment]
https://docs.google.com/spreadsheets/d/1wfPGwNP7pWUx6WRCdO7HRA_GGJG_5IUGFZQ21EsUrb0/edit#gid=0

**Comment by iviangita** [comment]
UPDATE: No access has recently been revoked. Closing this!
