### ISSUE TITLE
Call for Legal WG help

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#1067]
## 👇🏽  What is this issue about? Give as much detail as you can. 
@iviangita has accepting being the acting Steward of Legal for the present. The primary task is to put out a call for legal advisory support as Shawn has accepted a FT position at a company and must step away from the TEC. 

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by iviangita** [comment]
Hi @tamarandom, here's the open call we released last time. Can we reuse it? I put my name as the contact person, let me know if there are other persons to be contacted too.

OPEN CALL FOR LEGAL EXPERTS: Do you have a legal background & strong interest in decentralized technologies? We'd love to have you in our Legal WG! Your expertise will be a huge help in shaping our legal strategies. If interested, pls contact our Community Steward @iviangita 🙏

**Comment by tamarandom** [comment]
Awesome! I added it to the community slides too.

**Comment by iviangita** [comment]
Pablo (PabloA#7958) is on board! :D
