### ISSUE TITLE
Onboarding Experience - New landing flow 

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#1068]
## 👇🏽  What is this issue about? Give as much detail as you can. 

There are 3 parts that are being updated  as part of this new flow:
- Survey
- Guide
- Channels 

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 🔗  Are there links or docs related to this issue?
@mcsmith89  onboarding flow doc: https://docs.google.com/document/d/1hCpDD4zyZ8BZ54qevU0miyfhGbrk44_AFumqXRebFQI/edit
@eduardovegap  Onboarding journey: https://docs.google.com/document/d/1hCpDD4zyZ8BZ54qevU0miyfhGbrk44_AFumqXRebFQI/edit
@lexiebird  Newcomer journey: https://docs.google.com/document/d/1VEpXXxIzetGzEjw-3KlNk6NY_PPipGc7v4FGwujRVLI/edit

## 👀  Who should be in the loop about this issue?
@

**Comment by natenatesoo** [comment]
Epic is done.  Only needed iterations.  This can be closed if no one objects.  Will remain as open epic until next sprint.
