### ISSUE TITLE
Onboarding journey : message to community that channels will move around

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#1070]
## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. Share the new flow on a community call
2. The day / day before we deploy, share a message to @all that our channels will be updated. 
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by eduardovegap** [comment]
done.
