### ISSUE TITLE
TEC discord deployment server access

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#1071]
## 👇🏽  What is this issue about? Give as much detail as you can. 
@Vyvy-vi is creating dicord bots for the TEC server and is hosting them on his own servers. 

@geleeroyale @GriffGreen - is there a better place, a shared server, where he can move these bots to? 

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by geleeroyale** [comment]
I can set up an instance for @Vyvy-vi  - pls ping me withyour public ssh key (discord geleeroyale#3288)

**Comment by tamarandom** [comment]
Woohoo!!

**Comment by tamarandom** [comment]
@Vyvy-vi confirmed he has access. All is good. Closing.
