### ISSUE TITLE
Retro action: #twitter-feed on our Discord server 

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#1073]
## 👇🏽  What is this issue about? Give as much detail as you can. 

Hey @Vyvy-vi do you want to take this on next Sprint!? 
Should probably be close to our #amplify channel 

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by Vyvy-vi** [comment]
Yes, sure!

I think something like tweetshift bot can be used here, instead of making our own

**Comment by tamarandom** [comment]
Setup with Vy. 

![Screen Shot 2021-11-25 at 3.57.20 PM.png](https://images.zenhubusercontent.com/5faaa1d038c6409364f7830c/dada5910-d887-4292-ae19-2d1f68f316b0)
