### ISSUE TITLE
Optimism retroactive public funding 

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#1074]
## 👇🏽  What is this issue about? Give as much detail as you can. 
Paperwork needed for this. Praise @chuygarcia92 for taking this on!! 

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by chuygarcia92** [comment]
the W8 form was sent and my address confirmed. I'll share the tx here when I get the funds to check next steps.

**Comment by chuygarcia92** [comment]
got 0.8 ETH from Optimism RPGF! before we close this issue: should we aim to put this ETH in the lasertag multisig?

**Comment by tamarandom** [comment]
Idea from Sprint Planning: Gitcoin (multiple coins) and RPGF (eth) to be sent to the LASERTAG multisig, intention to use for future LP.

**Comment by chuygarcia92** [comment]
DONE!

0.8 ETH transfer to Griff: https://etherscan.io/tx/0xecc9e959f577e53fb7a59e1cac433660490647e089622e695706c7a4fa752416 

Griff's transfer to Lasertag multisig on Gnosis Chain: https://blockscout.com/xdai/mainnet/tx/0x4b097c0ade664cdec0afd8f64e09f2ca8184ebbbd924ab11d340bfb397f2e74d
