### ISSUE TITLE
Commons upgrade checklist 

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#1076]
## 👇🏽  What is this issue about? Give as much detail as you can. 

Before we push the button. Make sure we have checklist from every WG and sign-off from each WG steward that has blocking tasks to confirm when done.

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. List of every blocking piece of work and Steward to give the sign-off on it.
2. 
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by tamarandom** [comment]
This is the basis for the checklist but is there more? What else are we missing? Creating the voter pamphlets, is one. 

Demo with feedback #834
Covenant #849
LASERTAG multisig (pending quadratic rank choice voting) #1086
Final params (Voting primaries & runoff) 
Legal T&C (needs the final parameters to be voted in first) #245 & #246
(important, not blocking) WG funding proposals Epic #1087

**Comment by GriffGreen** [comment]
Legal has a bunch of T&Cs but the only one that is critical for the upgrade is the ABC... the CV related ones don't exist for most groups and is a lot lower risk than the ABC

**Comment by tamarandom** [comment]
We're tracking this in every Steward call. Also labelled "blocking commons upgrade" in this repo. Closing.
