### ISSUE TITLE
Make progress on Graphic content for User Journey. :-D

### ISSUE THREAD

**Issue by eduardovegap** [CommonsBuild/coordination#1078]
## 👇🏽  What is this issue about? Give as much detail as you can. 

We want to layout a visual version of the journey.

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. Having a draft of what the journey for a user would look like
2. Consensus on its parts and content.
3.

## 🔗  Are there links or docs related to this issue?

LB has advanced part of this here: https://docs.google.com/document/d/1VEpXXxIzetGzEjw-3KlNk6NY_PPipGc7v4FGwujRVLI/edit?usp=sharing

## 👀  Who should be in the loop about this issue?
@

**Comment by acidlazzer** [comment]
Nice initiative, showing some progress soon!

**Comment by tamarandom** [comment]
@acidlazzer @mcsmith89 : can you drop an update in here? @eduardovegap believes it was started. Is there any help needed?

**Comment by acidlazzer** [comment]
![newcomer journey.jpg](https://images.zenhubusercontent.com/60b15c4caa64fc5b8e239a2b/3f846fb7-4eac-4b40-a3a6-0d8f0a5d325c) Hello! This graphic?

**Comment by GriffGreen** [comment]
To be updated this sprint

**Comment by mcsmith89** [comment]
Hey Team! 

The last few discussion points around this can be found on the retro board - https://miro.com/app/board/o9J_lYcRTik=/

![image](https://user-images.githubusercontent.com/60235653/152818351-58915b2e-f538-40ed-9c0b-d13e307103b0.png)


This has stalled on my end - re-calibrating with @eduardovegap for next best steps.

**Comment by natenatesoo** [comment]
The graphics should be updated to fit the context of the TEC user journey.

**Comment by mount-manu** [comment]
@gideonro You're already working on this so I'm just updating this issue for it.

**Comment by gideonro** [comment]
I think we can close this, right @eduardovegap ?
