### ISSUE TITLE
Discord and Forum analytics

### ISSUE THREAD

**Issue by Zeptimus** [CommonsBuild/coordination#1079]
## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by Ionneto** [comment]
[statbot ](https://statbot.net/) has shown itself to be the best one for me so far, premium version pretty complete for discord data

**Comment by Zeptimus** [comment]
Hey Ionneto  for now we are using the stats that discord give it self for free and this is the result. [https://app.zenhub.com/files/306706322/b755cd26-3ae8-43e0-9f84-5557c2161ac5/download](https://app.zenhub.com/files/306706322/b755cd26-3ae8-43e0-9f84-5557c2161ac5/download) 

What would be the benefits of using statbot instead? Thanks for sharing and would love to see you on a transparency call to discuss it in more depth, we could also do it here asyc if you prefer it :)

**Comment by Ionneto** [comment]
Would gladly jump in a call with you guys, really admire the work you're doing. following quietly from my corner of DAO world. 

I think statbot is way more complete than the ones that discord gives, you can access their site and see an example it shows you. 

They have member and channel message counters, voice timers, join and leave of members broken down by the hour and some bit more flavor to break those down into smaller pieces to better analyze.

I can't really access the link you shared rn, but I'll believe you that you're extracting the most you can from discord native stats, maybe I'm just not that good with them haha will check the link when back on my machine

**Comment by Zeptimus** [comment]
done this month :D
