### ISSUE TITLE
Give Lauren access to the Twitter :)

### ISSUE THREAD

**Issue by laurenluz** [CommonsBuild/coordination#1083]
## 👇🏽  What is this issue about? Give as much detail as you can. 
I'm running the Twitter for Giveth and leading a bunch of param parties so I see a lot of good stuff to RT / respond to from TEC! Would love to have to have the power to support :D

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by chuygarcia92** [comment]
Done!
