### ISSUE TITLE
Ask Gravitons if they want to appear in the side bar of the server

### ISSUE THREAD

**Issue by JuankBell** [CommonsBuild/coordination#1084]
## 👇🏽  What is this issue about? Give as much detail as you can. 
We want to ease access to Gravitons, so we are now displaying this role in the server, but to not put people in awkward places, Juan will ask all gravitons if they would like to be displayed in this way. 

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. Easy access to Gravitons
2.  Decentralization between Gravitons
3. Create a practice that could be reproduced in other servers

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@GriffGreen @liviade1 @tamarandom 

## 🔗  Are there links or docs related to this issue?
![Captura de Pantalla 2021-11-11 a la(s) 1.49.28 p. m..png](https://images.zenhubusercontent.com/5fb57c9c5472cf79e80e7f7e/e6ddcacf-711b-4a1f-9533-7bd23b3b276e)

## 👀  Who should be in the loop about this issue?
@durgadas

**Comment by tamarandom** [comment]
I volunteer!

**Comment by tamarandom** [comment]
Process definition, active gravitons training session? This will be great!!

**Comment by JuankBell** [comment]
done! ![Captura de Pantalla 2022-03-03 a la(s) 2.17.11 p. m..png](https://images.zenhubusercontent.com/5fb57c9c5472cf79e80e7f7e/94ddc095-1b86-455b-a5d3-245fb5cb63c4) Must update in community call slides :)
