### ISSUE TITLE
Boardroom Finalization

### ISSUE THREAD

**Issue by natenatesoo** [CommonsBuild/coordination#1085]
## 👇🏽  What is this issue about? Give as much detail as you can. 
Making sure all aspects of Boardroom are prepped and ready for community use.  This includes the following:

- [ ] Overview.md file describing Decision-Making & Governance Process

- [ ] Discourse Forum - Proposals Section to be available for community engagement through Boardroom\

- [ ] Update Calendar for the next two months and develop a process for updating Schedule in Boardroom for future PRs.

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. Full setup of our Boardroom Instance.  Interactions with Snapshot, Discourse, and Scheduling.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@liviade1 
@tamarandom 

## 🔗  Are there links or docs related to this issue?
N/A

## 👀  Who should be in the loop about this issue?
@Vyvy-vi

**Comment by tamarandom** [comment]
Hey @natenatesoo  - Should we make a quick edit to that Overview file so that the page isn't totally blank? Even if we don't have the final version ready yet? 

![Screen Shot 2021-11-16 at 12.11.56 PM.png](https://images.zenhubusercontent.com/5faaa1d038c6409364f7830c/c9afff63-5a47-4bb2-b7d0-007a9442c500)

**Comment by natenatesoo** [comment]
Yes. I have a blueprint for it which will include the Advice Process and decision-making methods.  However, do we have established rules around Snapshot voting (how many days should a vote be open for, and the use of proposal templates, etc.)?

**Comment by tamarandom** [comment]
Let's check in on it this Sprint. Both @natenatesoo and I requested access to update the page but no news yet!!

**Comment by tamarandom** [comment]
Hey @natenatesoo - this looks GREAT! We call it done, right? Is there any reason not to close this issue now?

![Screen Shot 2022-03-17 at 8.06.24 PM.png](https://images.zenhubusercontent.com/5faaa1d038c6409364f7830c/89b07f54-9094-4440-bb5a-9be71e10bc00)

**Comment by tamarandom** [comment]
Closing....
