### ISSUE TITLE
Write Rewards WG manifesto

### ISSUE THREAD

**Issue by kristoferlund** [CommonsBuild/coordination#1090]
## 👇🏽  What is this issue about? Give as much detail as you can. 

The Rewards WG will steward the periodic reward quantifications.

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. The WG manifesto should cover all responsibilities previously described in the following docs: 
[🔗  The SourceCred committee proposal](https://forum.tecommons.org/t/sourcecred-committee-proposal/271)
[🔗  Outlining the Rewards System Process.. v2!](https://forum.tecommons.org/t/outlining-the-rewards-system-process-v2/646 )

## 👀  Who should be in the loop about this issue?
@

**Comment by liviade1** [comment]
https://docs.google.com/document/d/1NTElbsIUf9_ov0Z9PyRX9y0zVRII04_551XyT9x5HqY/edit#
