### ISSUE TITLE
First quant - preparations and execution

### ISSUE THREAD

**Issue by kristoferlund** [CommonsBuild/coordination#1097]
See notion for details: https://www.notion.so/fmckl/Preparations-for-first-quant-df927dd3bff140b59588e9975c1a0a5a

**Comment by divine-comedian** [comment]
Prepare for first quant on Mon. March 7 

Period Created for 2 weeks until July 31 202, start with test real quant for 2 weeks then transition to 1 month blocks until we catch up

Praise Discord bot is ready in the TEC discord. 

Waiting for @kristoferlund  to import praise users back into praise dashboard - needs to write scripts, should be ready for Mar 3

**Comment by divine-comedian** [comment]
Schedule recorded quant session early next week  synchronous call where we can answer questions and facilitate first quant process

**Comment by GriffGreen** [comment]
OMG YOU GUYS ROCK!

**Comment by divine-comedian** [comment]
we're still gearing up for the first sourcred distro, should happen in about one week, will follow up in this epic depending on success

**Comment by divine-comedian** [comment]
we made the first grain distro but the results are less than ideal, we need to continue merging sourcecred accounts and tweak some distribution settings in order to get an accurate distribution.

we are able to remove grain distributions and recalculate them as needed before rewards go out.
