### ISSUE TITLE
Recruit quantifiers for quant #1

### ISSUE THREAD

**Issue by kristoferlund** [CommonsBuild/coordination#1100]
## 👇🏽  What is this issue about? Give as much detail as you can. 

Recruit and onboard the quantifers for first quant post Commons Upgrade.

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

##  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 🔗  Are there links or docs related to this issue?

https://www.notion.so/fmckl/First-rewards-quantification-df927dd3bff140b59588e9975c1a0a5a

## 👀  Who should be in the loop about this issue?
@

**Comment by graial** [comment]
I dont know if id qualify as a quant at my current membership level but I would certainly be interested in sitting in on the process to observe in order to better understand the workflow and decision making process

This would help us develop our use cases.

**Comment by tamarandom** [comment]
@divine-comedian, any reason not to close this? Hit the target number?

**Comment by divine-comedian** [comment]
yes! we hit 31 a few days ago! mission success.
