### ISSUE TITLE
Forum post: The Quantifier role

### ISSUE THREAD

**Issue by kristoferlund** [CommonsBuild/coordination#1101]
## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

##  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by divine-comedian** [comment]
@Zeptimus  to create thorough onboarding tutorial with text/images adding to current onboarding doc @mcsmith89  to assist 

current doc - https://docs.google.com/document/d/1I7OZrkGZaHUCQ1Ji-4B0DGWoHK1slECzoXQLvzCV_YM/edit?usp=sharing

**Comment by kristoferlund** [comment]
Great to see work started on this!

**Comment by mcsmith89** [comment]
@Zeptimus happy to connect soon around this - will follow-up in Discord too.

**Comment by Zeptimus** [comment]
I polished it a bit https://docs.google.com/document/d/1I7OZrkGZaHUCQ1Ji-4B0DGWoHK1slECzoXQLvzCV_YM/edit there are some questions that we could do the advice process on the call before posting for advice process in the community i won't be able to attend today but i left some questions that i would love some input

We missing some pictures @kristoferlund  could you grab them from the dashboard and send it to me or @mcsmith89  for the HOW TO QUANTIFY part or should we wait until its ready?.

**Comment by Zeptimus** [comment]
updated with the screen shots: https://docs.google.com/document/d/1I7OZrkGZaHUCQ1Ji-4B0DGWoHK1slECzoXQLvzCV_YM/edit

**Comment by mcsmith89** [comment]
Looking good - I like that it is starting simple. We could shoot a simple Loom to compliment in the near future until we do a full animated experience with Comms too.

**Comment by Zeptimus** [comment]
https://forum.tecommons.org/t/quantifier-onboarding/825
