### ISSUE TITLE
Video of param party hosted on Gticoin

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#1102]
## 👇🏽  What is this issue about? Give as much detail as you can. 

@GriffGreen shared this. It is a very good params party. What can we do with it? @Zeptimus can we somehow add it to our YouTube? @chuygarcia92 do we want to promote this more? 

https://www.youtube.com/watch?v=wd5krPdr7WA&t=2985s

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

**Comment by Zeptimus** [comment]
https://www.youtube.com/watch?v=-CRK55bO6es I edited the call the explanation of why TEC its at the begining and then the param party

**Comment by tamarandom** [comment]
Closing. @Zeptimus will make it the feature video for the next few weeks.
