### ISSUE TITLE
Update TEC soft gov decision tracking

### ISSUE THREAD

**Issue by Zeptimus** [CommonsBuild/coordination#1103]
## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by Zeptimus** [comment]
close, https://docs.google.com/spreadsheets/d/12_PK_G9-gGxPOm-mdl5dlfdh9GSZGuI5gkTLkWlfNcY/edit#gid=0

**Comment by tamarandom** [comment]
Hey @liviade1 @Zeptimus I just took off the "repeating" tag on this issue so it stays closed!

**Comment by Zeptimus** [comment]
hey @tamarandom  its actually going to happen continously since we are taking decisions every period of time

**Comment by tamarandom** [comment]
ok, raised it from the dead. 🧟

**Comment by Zeptimus** [comment]
Done :D
