### ISSUE TITLE
Calendly for Orientation 1-1's 

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#1105]
## 👇🏽  What is this issue about? Give as much detail as you can. 
9:01 PM] Vyvy-vi: I'm wondering, if we can maybe set up a shared version of Calendly for Orientation Guides
[9:01 PM] Vyvy-vi: :D I set one up for my use, and it's awesome! - https://calendly.com/vyvy-vi

This. 👆  😁

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by eduardovegap** [comment]
Temporaly i have set up this one: https://calendly.com/vegayp/60?

We can set up one for each guides.

**Comment by eduardovegap** [comment]
is set up: https://calendly.com/tecguides/30min

guidesatttec@gmail.com is the email provided and created. 
We can either each of us create a meeting with our names or use a single meeting. To be decided.

**Comment by GriffGreen** [comment]
DONE! YAY!

**Comment by tamarandom** [comment]
We'll need a subscription to make the workflows and multiple calendars work. @eduardovegap is working on this now.

**Comment by tamarandom** [comment]
Also, we're looking at alternative: https://cal.com/

**Comment by eduardovegap** [comment]
We explored also Hubspot, but it's too expensive. It charges per user calendar. So my suggestion is to stick to calendly and paid it.

**Comment by tamarandom** [comment]
Another possibility: https://savvycal.com/pricing/

**Comment by tamarandom** [comment]
Done. We just need to publish it so people know about it!

**Comment by mount-manu** [comment]
Completed! This is the Calendly link we'll be using: https://calendly.com/tecguides
