### ISSUE TITLE
Create avatar for Discord 'your-guide' bot. 

### ISSUE THREAD

**Issue by mcsmith89** [CommonsBuild/coordination#1107]
## 👇🏽  What is this issue about? Give as much detail as you can. 
We would like to have a TEC branded avatar for the 'your-guide' bot. 

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. An avatar that helps the guide feel branded to the TEC experience. 

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@tamarandom, @Vyvy-vi, @mcsmith89, @eduardovegap 

## 👀  Who should be in the loop about this issue?
@

**Comment by mcsmith89** [comment]
I think this looks great @acidlazzer i submitted to @Vyvy-vi and if we are good with it I will close issue.

**Comment by Vyvy-vi** [comment]
:D Awesome icon -

![icon for the onboarding bot, smiling robot with a tec logo](https://cdn.discordapp.com/attachments/910937345312850020/914957729334968320/unknown.png)
