### ISSUE TITLE
Using Announcements on Discord 

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#1108]
## 👇🏽  What is this issue about? Give as much detail as you can. 
To/From Commons Stack, Token Engineering, Giveth, etc... (let's make the full list)

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by tamarandom** [comment]
@Vyvy-vi and I setup the one for Commons Stack and Giveth.

TE discord doesn't have an Announcements channel. Closing this for now. Any others can be setup but we just need to know which ones and add them to the Ecosystem section.

**Comment by Ekeneodigwe** [comment]
> @Vyvy-vi and I setup the one for Commons Stack and Giveth.
> 
> TE discord doesn't have an Announcements channel. Closing this for now. Any others can be setup but we just need to know which ones and add them to the Ecosystem section.

I am wondering If the Commons Stack and Giveth announcement channels have been set up shouldn't the cross posting should  be viable? I am thinking so because the testing this announcement channel message @tamarandom did on Commons Stack Server was not seen on Giveth Server

**Comment by tamarandom** [comment]
To be more clear this time, ;) @Ekeneodigwe 

TEC <--> Commons Stack
TEC <--> Giveth
