### ISSUE TITLE
Mint tokens for new Reward Board

### ISSUE THREAD

**Issue by divine-comedian** [CommonsBuild/coordination#1111]

**Comment by divine-comedian** [comment]
We'll need a clear list of Reward Board members who will participate in the voting processes required in the DAO and then mint 1 DAO token for each of them.

**Comment by divine-comedian** [comment]
DONE! 
![image](https://user-images.githubusercontent.com/67759413/144460188-c5a4db93-6b93-43cf-b174-0fec7b81ebec.png)

https://xdai.aragon.blossom.software/#/rewardboardtec/0x4fa865e524512b8007c1d63125f476bffe5e8e85/

**Comment by tamarandom** [comment]
Excellent!!!
