### ISSUE TITLE
Revoking access to TEC platforms

### ISSUE THREAD

**Issue by iviangita** [CommonsBuild/coordination#1114]
## 👇🏽  What is this issue about? Give as much detail as you can. 
After posting the proposed process for offboarding credentials on the [forum](https://forum.tecommons.org/t/tec-offboarding-credentials-and-access/699) and no one objects, we will proceed with the process of revoking access of inactive contributors to TEC platforms.

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@iviangita

**Comment by Zeptimus** [comment]
we reach out to the platform admins nate and chuy and they said there is no plans to revoke access to anyone and close
