### ISSUE TITLE
Create Onboarding Process for Quantifiers

### ISSUE THREAD

**Issue by divine-comedian** [CommonsBuild/coordination#1115]

**Comment by tamarandom** [comment]
@divine-comedian this is done, right? Any reason not to close?

**Comment by divine-comedian** [comment]
Just waiting for @Zeptimus   to publish the onboarding guide to the forum and incorporate feedback from our test quant

**Comment by Zeptimus** [comment]
done https://forum.tecommons.org/t/quantifier-onboarding/825
