### ISSUE TITLE
Check the requirements/needs to get Dune analytics set up

### ISSUE THREAD

**Issue by iviangita** [CommonsBuild/coordination#1118]
## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by Zeptimus** [comment]
After talking with fabio  the bounty for dune normally goes between  500 and 1500 USD depending on the needs.
