### ISSUE TITLE
New deck for Orientation.

### ISSUE THREAD

**Issue by eduardovegap** [CommonsBuild/coordination#1123]
We need to improve the presentation we provide on the orientation call. 

We are using the current document as reference. 

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 🔗  Are there links or docs related to this issue?

https://hackmd.io/RTSV_pISTNWTjP-j9c0N0Q

## 👀  Who should be in the loop about this issue?
@

**Comment by acidlazzer** [comment]
Working on that! <3

**Comment by acidlazzer** [comment]
Presentation ready! :) https://docs.google.com/presentation/d/1n7W9zaamNxjDPRpd7s7gW8LSbiwcuej1BWmi0xuRO08/edit?usp=sharing

**Comment by eduardovegap** [comment]
done.
