### ISSUE TITLE
Hatcher outreach for params, encourage participation 

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#1124]
## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by eduardovegap** [comment]
@acidlazzer can we have the list of attending for Poaps? :D

**Comment by acidlazzer** [comment]
Param parties attendees list! https://docs.google.com/spreadsheets/d/1SgGDSTG6dDqH3qqOD9nazp73upLRbXi4HZMSAVfsFZE/edit?usp=sharing

**Comment by eduardovegap** [comment]
we can use this issue to outreach top TH.
