### ISSUE TITLE
Setup Discord plugin for TEC SourceCred so we can use data from the meeting tracker bot

### ISSUE THREAD

**Issue by kristoferlund** [CommonsBuild/coordination#1132]
## 👇🏽  What is this issue about? Give as much detail as you can. 
We need to have the Discord plugin configured for the TEC SourceCred instance. Meeting tracker bot will most likely need it, the 1hive pollen bot will maybe need it. 

But, we don't want the plugin top track any channels or generate any cred or grain.

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. Plugin installed and configured, not tracking any channels
2.
3.

**Comment by GriffGreen** [comment]
This still needs the meeting tracker bot to get done... right... is this even true ? @mateodaza @Vyvy-vi can you verify?

**Comment by Vyvy-vi** [comment]
The bot is in testing mode right now.
I think we can get this done around 15th Feb
