### ISSUE TITLE
Move pollen bot repositories to the TEC GitHub

### ISSUE THREAD

**Issue by kristoferlund** [CommonsBuild/coordination#1133]
## 👇🏽  What is this issue about? Give as much detail as you can. 
Three repositories need to be moved:
1. Pollen bot
2. Onboarding script
3. Cred fetcher

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. Repos moved :)
2.
3.

**Comment by hozzjss** [comment]
I don't think i can edit this issue so i'll write here that i have moved all three repos here

https://github.com/CommonsBuild/pollen-cred-fetcher
https://github.com/CommonsBuild/pollen-bot
https://github.com/CommonsBuild/pollen-onboarding

**Comment by kristoferlund** [comment]
Great, closing this issue then!
