### ISSUE TITLE
Describe how the Reward Board works in detail

### ISSUE THREAD

**Issue by kristoferlund** [CommonsBuild/coordination#1134]
## 👇🏽  What is this issue about? Give as much detail as you can. 

Details such as:
- How to join
- How to leave
- What votes are being conducted
- What funds are being managed
- The quantification review process
- etc.

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. A doc and a forum post describing the inner workings of the Reward Board
2.
3.

##  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)

- The Rewards WG

## 🔗  Are there links or docs related to this issue?

https://fmckl.notion.site/Reward-Board-Description-2766d6ca769f4c1daa6bca6e58860326

## 👀  Who should be in the loop about this issue?

- All TEC stewards

**Comment by divine-comedian** [comment]
huge updates in the original notion doc - please review 

https://www.notion.so/Reward-Board-Requirements-and-Guidelines-2766d6ca769f4c1daa6bca6e58860326

**Comment by GriffGreen** [comment]
@divine-comedian can this be closed? did you get enough reviews? do we need to add more details to it?
