### ISSUE TITLE
Create Quant Review Call agenda 

### ISSUE THREAD

**Issue by divine-comedian** [CommonsBuild/coordination#1137]
We've decided to remove the power from the reward board to modify the reward distribution - instead we will have a collaborative review process when all quantifiers have finished their praise assigned. There will be a synchronous call with all quantifiers that can attend and a couple reward board members. Some rough notes around the objectives for this call: 

Final Quant Review:
- objectives of final quant review call 
    - open forum to discuss 
    - barometer of reward system effectiveness  - high level questions 
    - catch duplicative praise 
    - catch invalid praise - how detailed is praise
    - recognize people who are doing invisible work - working hard, quietly in the background
- recognizing the work done that impact the TEC but not explicitly happening inside of it 
    - i.e simon inventing bonding curves
- transparency - keeping a changelog of changes made during the quant call
- creating a track of common problems during quantification

The purpose of this issue is to create an agenda that reward board members can take with them to the quant review calls to guide them through the process and successfully submit a final quant to the reward board

**Comment by divine-comedian** [comment]
document started here - https://hackmd.io/I0_ESWd7SC6yCU3aJ4nIgA

**Comment by GriffGreen** [comment]
@divine-comedian can this be closed?

**Comment by divine-comedian** [comment]
we should leave this open - doc is far from finished and we haven't had a quant review call yet

**Comment by liviade1** [comment]
@divine-comedian is this something different from the tweak session? https://docs.google.com/document/d/1bvpgt8YbDJxdrC3i3cEK9HJYwPwrqNiaUV8nFDyDPgc/edit#heading=h.o22gr64rapuc

**Comment by divine-comedian** [comment]
> @divine-comedian is this something different from the tweak session? https://docs.google.com/document/d/1bvpgt8YbDJxdrC3i3cEK9HJYwPwrqNiaUV8nFDyDPgc/edit#heading=h.o22gr64rapuc

this would be the same thing
