### ISSUE TITLE
Add our MVV to the website replacing the outdated mission

### ISSUE THREAD

**Issue by GriffGreen** [CommonsBuild/coordination#1139]
## 👇🏽  What is this issue about? Give as much detail as you can. 

The Mission on the website is different than the in the gitbook 😱 

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. The website matches our content in the gitbook
2. Bonus points for doing a website vs gitbook content review

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@chuygarcia92 @kristoferlund 

## 🔗  Are there links or docs related to this issue?

https://token-engineering-commons.gitbook.io/tec-handbook/what-is-the-tec/mission-vision-and-values

https://tecommons.org/#mission

## 👀  Who should be in the loop about this issue?
@tamarandom @liviade1

**Comment by tamarandom** [comment]
Who can work on this? @kristoferlund do you have someone?? @chuygarcia92 ??

**Comment by kristoferlund** [comment]
The website texts can be edited through the CMS, no hacking needed.

https://tecommons.org/admin/

![image](https://user-images.githubusercontent.com/9698363/146197454-a4c611ec-43b9-45a2-b42b-cead50469871.png)

**Comment by tamarandom** [comment]
Great! @chuygarcia92 is there a volunteer in Comms perhaps that can take this issue on?

**Comment by chuygarcia92** [comment]
bring the website to the Hubspot TEAM is something that is being considered
how to integrate efforts under the same organizational workspace for platforms to be coherent is a raising concern that the hubspot team can make happen

**Comment by chuygarcia92** [comment]
@mount-manu has been working on access credentials for the website, and the Hubspot TEAM has been adding some web devs to our lines :) 
@mount-manu do you feel okay to take this issue on as one of the most urgent fixes?

**Comment by mount-manu-zz** [comment]
Sure @chuygarcia92 , I got this

**Comment by tamarandom** [comment]
Hey guys. Just FYI that the mission on the website is still the wrong one ;(

![Screen Shot 2022-01-30 at 1.04.29 PM.png](https://images.zenhubusercontent.com/5faaa1d038c6409364f7830c/68417d1c-d00d-4685-a6a2-2ae902e6d1bd)

![Screen Shot 2022-01-30 at 1.04.34 PM.png](https://images.zenhubusercontent.com/5faaa1d038c6409364f7830c/965386a6-c471-4c3a-bffb-d2cbdce1acd6)

**Comment by kristoferlund** [comment]
@mount-manu You'll be able to change this with the CMS login we set up.

**Comment by chuygarcia92** [comment]
we're starting to make pull requests for these changes with the help of Casale, we're somehow blocked by the Comms TEAM DAO funding proposal but moving on for this sprint

**Comment by GriffGreen** [comment]
YEAH!

**Comment by mount-manu-zz** [comment]
Done!
![Screen Shot 2022-02-23 at 6 06 55 PM](https://user-images.githubusercontent.com/55956086/155431941-256f9a64-1c52-47dc-80a0-975b85218c02.png)
