### ISSUE TITLE
create a #quantifier-support channel for reward board WG to assist quantifiers

### ISSUE THREAD

**Issue by kristoferlund** [CommonsBuild/coordination#1140]

**Comment by divine-comedian** [comment]
Where should we put this? under Working Groups or in the Community category? I would think that community would be better

**Comment by Vyvy-vi** [comment]
Should this channel be restricted to be specifically for quantifiers and Reward Board WG?

**Comment by divine-comedian** [comment]
> Should this channel be restricted to be specifically for quantifiers and Reward Board WG?

I think its safe to make it unrestricted - we can pin resources for people who are interested in becoming a quantifier - if it becomes a problem we can add restrictions later

**Comment by divine-comedian** [comment]
DONE
