### ISSUE TITLE
Review of praise channel messages 

### ISSUE THREAD

**Issue by mcsmith89** [CommonsBuild/coordination#1142]
## 👇🏽  What is this issue about? Give as much detail as you can. 
We are looking to perform a sample audit of the message within the praise channel on Discord. The goal is to look for any inconsistencies in the data making sure everyone was picked up by the praise bot etc. The initial prompt for this review is the praise bot not marking confirmation for Juankbell. 

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. Proper review of a sample of data to render inconsistencies. 
2. Re-run of another sample of data. 
3. Eventually full review to a point back in time we feel is meaningful. 

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@Vyvy-vi @tamarandom @mcsmith89 

## 🔗  Are there links or docs related to this issue?
[https://discordapp.com/channels/810180621930070088/810180622336262195/918507232222650409]

## 👀  Who should be in the loop about this issue?
@Vyvy-vi @mcsmith89 @tamarandom @kristoferlund

**Comment by mcsmith89** [comment]
@Vyvy-vi Feel free to DM me with a CSV of sample praise messages if you'd like? I can start to run a preliminary analysis on what exports if it helps out :)

**Comment by mcsmith89** [comment]
Update - @Vyvy-vi and I discussed how the data should come over and will provide in the near future :)

**Comment by mcsmith89** [comment]
@tamarandom @Vyvy-vi I have a simple beginning to the praise data being reviewed including output of people who had praise in the channel without the praise bot recognizing it. Where should I keep my analysis as I go through? Also, is it helpful if I place my (very basic) py scripts somewhere as I continue? 

**Example Output:**
![image](https://user-images.githubusercontent.com/60235653/147984538-5bfd8a60-5b16-4521-be17-434d49d304be.png)

**Comment by Vyvy-vi** [comment]
A repo would be nice

**Comment by liviade1** [comment]
Juank praise was being recorded, just didn't receive the checkmark emoji. 
There was one praise from acidlazer that wasn't recorded. Nuggan will look more into it to try to find a reason. 
This was considered a minor issue. 
since Vy is creating a new bot, it's expected this doesn't happen anymore.

**Comment by mcsmith89** [comment]
Agreed, Nuggan rocked it. All good.

**Comment by tamarandom** [comment]
Hey @mcsmith89 @liviade1 @0xNuggan is there any reason to keep this issue open? It can be closed now, right?

**Comment by kristoferlund** [comment]
Closing.
