### ISSUE TITLE
Create Automated template for Distribution Reports 

### ISSUE THREAD

**Issue by divine-comedian** [CommonsBuild/coordination#1143]
![image](https://user-images.githubusercontent.com/67759413/145597618-14e13ede-1e08-4aac-82bc-796f01a2c9e3.png)

**Comment by Fobey123** [comment]
wonderful stuff,keep going ser.

**Comment by tamarandom** [comment]
Hey @divine-comedian - do you mean for this to be an epic?

**Comment by divine-comedian** [comment]
nooo, I think this issue might be irrelevant now

**Comment by divine-comedian** [comment]
Sorry this issue is still being actively worked on by @0xNuggan 

This is our base template we'll use for automation. 

https://forum.tecommons.org/t/tec-rewards-distribution-august-2021/1012

**Comment by divine-comedian** [comment]
nuggan was able to create the automation, the only thing that will need to be added manually will be the url link for the analysis report! closing
