### ISSUE TITLE
Retro action: Find support for gravity!

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#1146]
## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by tamarandom** [comment]
Update: starting with a hack session with @GriffGreen

**Comment by JuankBell** [comment]
A lot of support received from Griff, Heather, Chuy and gravity contributors. Thanks. Right now we are more clear on how to coordinate after the commons upgrade
