### ISSUE TITLE
Retro action: Assign a buddy for new contributors.

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#1147]
## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by eduardovegap** [comment]
This will be accomplished ideally, when the guides get launched, so for next sprint we could start pairing potential contributors first with guides or members who have the time bandwith to support it.

**Comment by tamarandom** [comment]
Guides solve this and they have started! Closing.
