### ISSUE TITLE
Transparency of funding flows 

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#1149]
## 👇🏽  What is this issue about? Give as much detail as you can. 
The idea is for Transparency to publish a set of guidelines of how each WG can make transparent their funding flows. 

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by Zeptimus** [comment]
done
