### ISSUE TITLE
Gravity WG funding proposal 

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#1150]
## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. Finalize, publish on Forum
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by JuankBell** [comment]
Final review document for Gravity's funding proposal :)
https://docs.google.com/document/d/1u0mF9x5vEIYOgK5CWI-hH6Vwnfg8Hy7VrVB_LL-Q0Zc/edit#

Temptative schedule: 
This funding proposal will be posted in the forum: 11th january and open applications until the 20th of January.
The review process for the applications will be done by the TEC stewards between the 20th of january to the 25th of january 
The Gravity Community will review the TEC steward’s process and collectively agree on the assigned positions between the 25-28th of Jan 2022. 
The Gravity Funding proposal will be posted in the Conviction Voting app (gardens) by the 29th or 30th of january.

**Comment by tamarandom** [comment]
Closing. It's on the forum! Thanks @JuankBell !!

**Comment by JuankBell** [comment]
https://gardens.1hive.org/#/xdai/garden/0x1fc7e8d8e4bbbef77a4d035aec189373b52125a8/

**Comment by natenatesoo** [comment]
Still needs support to pass this proposal!  If not, revision of Budget will be implemented.

**Comment by JuankBell** [comment]
Passed! funds in multisig! First distribution made yesterday https://gnosis-safe.io/app/gno:0xfFbD35255008F86322051F2313D4b343540e0e00/balances
