### ISSUE TITLE
TEC spotlight on 1hiveTV

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#1151]
## 👇🏽  What is this issue about? Give as much detail as you can. 
Working on this now... should be recording this next Sprint!

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by tamarandom** [comment]
recorded... in  post-production.

**Comment by tamarandom** [comment]
This is in 1Hive's hands now. Kudos to @iviangita @eduardovegap and @divine-comedian! Will close this after it goes live.

**Comment by tamarandom** [comment]
Theeeeeeeees close. We will need a little support from TEAMS if they have the bandwidth, @chuygarcia92 !

**Comment by tamarandom** [comment]
There was a small hiccup with editing but it looks like it will be resolved. Would expect the ep to come out this Sprint.

**Comment by GriffGreen** [comment]
w00T!

**Comment by natenatesoo** [comment]
Can this be closed?

**Comment by tamarandom** [comment]
Retroactive funding was requested for this. Idea being to save the not insignificant gas fees that would be needed if it went through a Giveth Trace. 

Here is the vote: https://gardens.1hive.org/#/xdai/garden/0x1fc7e8d8e4bbbef77a4d035aec189373b52125a8/proposal/11

@chuygarcia92 Can I ask you what you think is the next best step? I think Twells is only waiting os us to confirm we are OK to release the video as is. Can we have someone in the video prod team look at it? There are some small glitches but I think we can probably live with them.

**Comment by tamarandom** [comment]
Update: We will release it! Some minor glitches that we will live with rather than wait longer.

**Comment by mount-manu** [comment]
Success! Here are the fruits of @chuygarcia92's labor: https://www.youtube.com/watch?v=fXwnWCc2hL8.

**Comment by tamarandom** [comment]
Closing!
