### ISSUE TITLE
Create a "Challenger" Terms and Conditions

### ISSUE THREAD

**Issue by GriffGreen** [CommonsBuild/coordination#1153]
## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@GriffGreen 

## 👀  Who should be in the loop about this issue?
@

**Comment by iviangita** [comment]
Closing this since the challenger T&Cs are already covered in this [issue](https://app.zenhub.com/workspaces/tec-coordination-workspace-5fad0d3fbbe4da0011c2f40d/issues/commonsbuild/coordination/246)
