### ISSUE TITLE
LASERTAG coordination

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#1160]
## 👇🏽  What is this issue about? Give as much detail as you can. 

The LASERTAG multisig voted in are: Paul, Zargham, Gideon, Angela, Griff, Tam, Mitch

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. Creation of multi-sig
2. Discord or TG group with all the above
3. (do we want/need a simple statement for this group?)

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by divine-comedian** [comment]
small hiccup - Angela was not informed of the LASERTAG multisig nor her nomination - will need to followup if she is still willing to take on the role or find a replacement via the outlined voting method

**Comment by divine-comedian** [comment]
following this vote - https://snapshot.org/#/tecommons.eth/proposal/0xcad826c818f3bfc821e746cc3f72f378bee5e935de7092864294a47710785c77

I've reached out to Gabi for an address - once I have all the addresses I will create the gnosis safe and the appropriate DM channel to coordinate

**Comment by divine-comedian** [comment]
safe is created! 
https://gnosis-safe.io/app/xdai:0xF41dEFf41016216346270e302DC0a5Dd4913DAdA/balances

DM chat is made with multisig signers 
closing this one out

**Comment by tamarandom** [comment]
Hero!
