### ISSUE TITLE
For some reason Juanka praise is not going through. 

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#1161]
## 👇🏽  What is this issue about? Give as much detail as you can. 

![Screen Shot 2021-12-14 at 8.00.58 PM.png](https://images.zenhubusercontent.com/5faaa1d038c6409364f7830c/8073956b-9cdb-45f9-9b58-331516d31b98)

@mcsmith89 pointed this out to me too and he and @Vyvy-vi are already looking at it. Just want to drop it here so we don't lose track of it.

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. Juanka's praise gets recorded
2. Mechanism to identify praise that the bot misses
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by mcsmith89** [comment]
Thanks for opening this! I also have this issue opened to work with @Vyvy-vi on - https://github.com/CommonsBuild/coordination/issues/1142

**Comment by mcsmith89** [comment]
I am happy to perform the analysis @tamarandom once I can grab a healthy set of sample data from the channel and that should help uncover similarities that may be causing the issue.

**Comment by tamarandom** [comment]
Oh I'll close this one then! 
Dupe of #1142
