### ISSUE TITLE
WGs: Explanation & Interrelationships (Medium article, evergeen)

### ISSUE THREAD

**Issue by mount-manu-zz** [CommonsBuild/coordination#1165]
## 👇🏽  What is this issue about? Give as much detail as you can. 

This isssue is about writing an article describing the Working Groups in the TEC. How are they created, how do they organize, what's their working style, how do they relate to one another..

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@gideonro @jasontphelps 

## 👀  Who should be in the loop about this issue?
@

**Comment by tamarandom** [comment]
I tagged this Communitas because it will be a go-to resource for newcomers into our community.

**Comment by tamarandom** [comment]
Hey @mount-manu - I pulled this from the doc we used to create the you tube video descriptions which was, I believe, also what we also used for the website, if it helps for the WG article: https://docs.google.com/document/d/1S8BkakHNifi-pMdzWJIaw5EV9sD444-c3Ndy4RFl5nY/edit

**Comment by Costa91** [comment]
I was asked to do an outline, to be then delivered to the writers guild so they can develop it into the article. 

https://docs.google.com/document/d/1-j9VmgsEteISqb7k4ChQMwjsObVoSN72/edit?usp=sharing&ouid=101908942387065528643&rtpof=true&sd=true

**Comment by tamarandom** [comment]
Passed to Writers Guild. 
CC @gideonro
