### ISSUE TITLE
Preparations for deluge of newcomers to the Discord 

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#1168]
## 👇🏽  What is this issue about? Give as much detail as you can. 

Following the launch of $TEC!

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by GriffGreen** [comment]
SUCCESS!
