### ISSUE TITLE
Gravity selection process for role applications

### ISSUE THREAD

**Issue by JuankBell** [CommonsBuild/coordination#1169]
## 👇🏽  What is this issue about? Give as much detail as you can. 

People will use [this form](https://forms.gle/ckmBaCT8oRiYkKMD8) to apply to the roles we are designing in the Funding proposal of Gravity. To make this process more formal and transparent, at least 3 TEC stewards could make some sense on the applications and design a structure to be presented to the gravity working group for feedback. 

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. Volunteers from the CS or stewards from the TEC helping on the selection process
2. Designing a working group structure with roles and assignees
3.  Draft for structure design to be presented 25th of January and open to negotiate details to receive approval.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@Zeptimus @chuygarcia92 @GriffGreen @iviangita @liviade1 @natenatesoo 

## 🔗  Are there links or docs related to this issue?
https://forms.gle/ckmBaCT8oRiYkKMD8

**Comment by GriffGreen** [comment]
Updated in a forum post, need to have 1-1's to figure out what success looks like for each person.

**Comment by JuankBell** [comment]
https://forum.tecommons.org/t/gravity-6-month-funding-from-the-tec/809/4

**Comment by JuankBell** [comment]
https://app.dework.xyz/o/gravity-dao-4UHhckKWxf8whABj2pY8mV/p/trust-creati-7BGDkdjAK9Fh6c4clekm2E

**Comment by JuankBell** [comment]
this can be closed! right now we have an initial group of 12 contributors, and may include some according to the needs that are identified while progressing.![Captura de Pantalla 2022-03-04 a la(s) 1.09.16 p. m..png](https://images.zenhubusercontent.com/5fb57c9c5472cf79e80e7f7e/590392e7-18fd-446d-9726-f98b627e1199)
https://app.dework.xyz/o/gravity-dao-4UHhckKWxf8whABj2pY8mV/p/trust-creati-7BGDkdjAK9Fh6c4clekm2E
