### ISSUE TITLE
Make Proposal on Snapshot for What We Hold Constant For the ABC

### ISSUE THREAD

**Issue by GriffGreen** [CommonsBuild/coordination#1172]
## 👇🏽  What is this issue about? Give as much detail as you can. 
![Screen Shot 2022-01-07 at 11.56.00 AM.png](https://images.zenhubusercontent.com/597b3dc4f8b79f8376e1224b/c9a8e52b-fc9b-4ccc-9139-94c9568cf360)

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by Zeptimus** [comment]
done https://forum.tecommons.org/t/how-should-we-adjust-the-abc-to-deal-with-the-unknowns-presented-by-ragequitting/800
