### ISSUE TITLE
Make a snapshot vote for when the vesting should start... 

### ISSUE THREAD

**Issue by GriffGreen** [CommonsBuild/coordination#1174]
There are 4 options... The Freeze can start 

#1 At the HatchDAO vote (Jan 13th)
#2 When CV Opens (Jan 19th/20th)
#3 When the ABC opens (Jan 24th/28th)
#4 Whenever Griff, Sem, Paulo, Nuggan and Vitor decide.

Should this be dependent on the proposal?

**Comment by tamarandom** [comment]
Done! Closing.

**Comment by JuankBell** [comment]
Snapshot vote done!

**Comment by JuankBell** [comment]
https://snapshot.org/#/tecommons.eth/proposal/0x15a47bed4e8cb92de3f5f4dd0802b8f84877e9c67e3ea5ed14d58d37e046d645
