### ISSUE TITLE
Setting up Dework platform with TEAMs as projects

### ISSUE THREAD

**Issue by chuygarcia92** [CommonsBuild/coordination#1175]
## 👇🏽  What is this issue about? Give as much detail as you can. 
Setting up dework.xyz and respective multisigs for TEAMs

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. Project management is done through dework, as well as compensation for bounties and recurring activities
2. Gnosis safes are associated with each TEAM, contributing to the Transparency WG efforts 
3. TEAMs are accountable in an easy and organized way

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@zeptimus @tamarandom

## 🔗  Are there links or docs related to this issue?
https://dework.xyz/o/team-dao-13kSBHOv5okqXbTIVuNaIk 

## 👀  Who should be in the loop about this issue?
@juank

**Comment by chuygarcia92** [comment]
we're almost done! just need to fix some stuff with the gnosis safes linked to the dework projects

**Comment by chuygarcia92** [comment]
UPDATE:
TE Academy TEAM multisig is already up & running! For the rest of the multisigs we've been bringing Zepti on board as a backup signature that doesn't restrict autonomy to the TEAMs, but supports in case of an emergency and/or risks around the funds.

**Comment by chuygarcia92** [comment]
## UPDATE
Current status of the different TEAMs and their Deworks/Multisigs:

| T.E.A.M. | Dework | Gnosis Safe |
| -------- | -------- | -------- |
| TE Academy     | Ready     | Ready     |
| Twitter Planning     | Ready     | Funds in place     |
| Translations     | Ready    | Funds in place   |
| Marketing     | In progress    | Stand-by   |
| Animation     | In progress    | To be reviewed by Transparency   |

**Comment by mount-manu** [comment]
Chuy is telling me this is done so I'm closing.
