### ISSUE TITLE
For Guides: Canned answers for common questions 

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#1177]
## 👇🏽  What is this issue about? Give as much detail as you can. 

We see a lot of the same questions on our Discord server. 
- is there someone that can help my project with tokenomics?
- how do I become a token engineer?

Adding a canned reply for these most common questions to the Guide for Guides will make it a lot easier for new guides to provide informed info to newcomers. 

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. Canned reply section for most commons questions in the Guide of guides
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 🔗  Are there links or docs related to this issue?
https://docs.google.com/document/d/1y4kaZM5nWypg1iVf4m-7yvv5BDB6odxwrhpnqGsX0ZE/edit

## 👀  Who should be in the loop about this issue?
@eduardovegap @tamarandom

**Comment by tamarandom** [comment]
Started the FAQ for guides here. Please add to it! https://docs.google.com/document/d/1edIsA8yYOxhC7if4mXW_3cz09zoeOhcQaj0wItymjZE/edit#

**Comment by tamarandom** [comment]
We can still do some work on this @eduardovegap @mount-manu and Costa though we need to decide priority and whether to pull it into the next Sprint.

**Comment by eduardovegap** [comment]
Costa is working on the document, gathering questions that I may have slipped to include as well as learning about the TEC while "answering" the questions on the document. On Monday he should be providing feedback and presenting it.

**Comment by eduardovegap** [comment]
The document has been finished: https://docs.google.com/document/d/1edIsA8yYOxhC7if4mXW_3cz09zoeOhcQaj0wItymjZE/edit

A more comprehensive version is also here: https://token-engineering-commons.gitbook.io/tec-handbook/hatch-101/faq
