### ISSUE TITLE
OPEN FOR CONTRIBUTORS: Set up TEC duneanalytics

### ISSUE THREAD

**Issue by Zeptimus** [CommonsBuild/coordination#1178]
## 👇🏽  What is this issue about? Give as much detail as you can. 

To show transparency around the TEC economy and support material for the [transparency audit](https://forum.tecommons.org/t/transparency-audit-report-a-new-approach/673)

NOTE: Before starting this task, reach out to @Zeptimus or @iviangita 

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@iviangita @Zeptimus 

## 👀  Who should be in the loop about this issue?
@

**Comment by natenatesoo** [comment]
Done! Yay!
