### ISSUE TITLE
Snapshot: change snapshot instance to use TEC tokens 

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#1179]
## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@liviade1 @natenatesoo @Zeptimus 

## 👀  Who should be in the loop about this issue?
@

**Comment by liviade1** [comment]
I changed the quadratic voting, now we need to change the ranked choice voting but @marthendalnunes has to look into it
