### ISSUE TITLE
Structure transparency issues for the audit

### ISSUE THREAD

**Issue by Zeptimus** [CommonsBuild/coordination#1180]
## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 👀  Who should be in the loop about this issue?
@iviangita

**Comment by GriffGreen** [comment]
Need bounties for the audit... @iviangita will help

**Comment by Zeptimus** [comment]
done, praise @iviangita :D

**Comment by mount-manu** [comment]
**Zepti's Update:** Audit's done so we're closing this one. Here's the link to the work done: https://www.figma.com/proto/JOrcjzjhxVE5s2imJBbnOa/TEC-Transparency-Audit-JAN-MARCH-%2722?node-id=309%3A682&scaling=min-zoom&page-id=0%3A1
