### ISSUE TITLE
Update the Transparency page on Gitbook

### ISSUE THREAD

**Issue by iviangita** [CommonsBuild/coordination#1195]
## 👇🏽  What is this issue about? Give as much detail as you can. 
https://token-engineering-commons.gitbook.io/tec-source/working-groups/transparency-wg 

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@iviangita

**Comment by Zeptimus** [comment]
Done :D
