### ISSUE TITLE
Previous gitcoin donations: send to lasertag? Common Pool? = To be a forum post

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#1201]
## 👇🏽  What is this issue about? Give as much detail as you can. 
So we don't lose track of it, @GriffGreen! 

Can also be assigned to someone else that can take this on! 

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by tamarandom** [comment]
Nice - that was quick: https://forum.tecommons.org/t/gitcoin-donations-what-should-we-do-with-them/859

**Comment by tamarandom** [comment]
Next step: rank choice voting on Snapshot. 
Will bring up in the Stewards call next week and plan the date for the snapshot vote.

**Comment by tamarandom** [comment]
@Zeptimus to take it on!

**Comment by GriffGreen** [comment]
Voted!

**Comment by mount-manu** [comment]
**Final Update from Zepti:** Done! It's on Snapshot and the community has voted that we shall convert it to WXDAI and send it to the Common Pool.

**Comment by tamarandom** [comment]
Closing.
