### ISSUE TITLE
Tec.eth, tecommons.eth to Lasertag

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#1202]
## 👇🏽  What is this issue about? Give as much detail as you can. 
So we don't lose track of it, @GriffGreen 

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by natenatesoo** [comment]
There were conversations about TEC.eth going to LaserTag, and tecommons.eth going to the translations T.E.A.M. for use in Mirror.

**Comment by tamarandom** [comment]
Confirmed by @Zeptimus
