### ISSUE TITLE
ETHDenver & ETHDenver talk

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#1205]
## 👇🏽  What is this issue about? Give as much detail as you can. 
Finishing up the talk will be the main goal for the first week and being there is the main goal for the second week of this Sprint. 

Note: There are 2 days I am on vacation: Feb 14 & 15. 

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by natenatesoo** [comment]
A++++++++ Talk!  Stewardship for the W!
