### ISSUE TITLE
Update TEC guide bot - add how to buy TEC

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#1207]
## 👇🏽  What is this issue about? Give as much detail as you can. 
![Screen Shot 2022-02-04 at 2.25.27 PM.png](https://images.zenhubusercontent.com/5faaa1d038c6409364f7830c/3080fd53-43cc-4e47-bebd-2f2b77efabe3)

Adding this to the TEC your-guide bot. @Vyvy-vi is this something that can be edited by any Steward or Guide? Or does it require your special skills to update? 

Text:
There are two ways to make an impact: One is to contribute your talent and time. The other is by acquiring $TEC, which allows you to help steer the TEC while directly supporting its mission( https://token-engineering-commons.gitbook.io/tec-handbook/what-is-the-tec/mission-vision-and-values). Here's how.
https://token-engineering-commons.gitbook.io/tec-handbook/how-to-purchase-usdtec. 

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@Vyvy-vi @gideonro @eduardovegap

**Comment by Vyvy-vi** [comment]
Q) Is "invest" the word we'd be comfortable using here? (Legal considerations)

**Comment by gideonro** [comment]
> Q) Is "invest" the word we'd be comfortable using here? (Legal considerations)

It's a fair point. I'm not deep enough on the legal considerations here. But maybe we just phrase the question as, "How do I acquire TEC tokens?"

**Comment by tamarandom** [comment]
Thanks for flagging, @Vyvy-vi. You are correct. And agree with @gideonro on going with acquire.

**Comment by tamarandom** [comment]
Hey @Vyvy-vi - do you know when you will be able to get to this?

**Comment by Vyvy-vi** [comment]
Tomorrow

**Comment by tamarandom** [comment]
Update: @Vyvy-vi plans to deploy tomorrow. 🙌

**Comment by Vyvy-vi** [comment]
The button was added and can be used in the TEC Discord server. Message me or reopen this issue if there are any text changes needed.:+1:
