### ISSUE TITLE
Contributors Agreement for Communitas

### ISSUE THREAD

**Issue by eduardovegap** [CommonsBuild/coordination#1208]
## 👇🏽  What is this issue about? Give as much detail as you can. 

We need a document that can serve as a point of reference for the contributors of the working group. Simple and easy to understand. 

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 🔗  Are there links or docs related to this issue?

https://docs.google.com/document/d/1_KaG2GOk5GnirBSJo2slgQfkoz877E5JRZ0P16cxan4/edit?usp=sharing

## 👀  Who should be in the loop about this issue?
@tamarandom

**Comment by GriffGreen** [comment]
A commitment for contributors :-D!

**Comment by GriffGreen** [comment]
Gravity is doing it organically

The written agreements facilitate off-boarding! 

There might be some resistance to this process if there isn't a clear purpose

We need consistency so we can guarantee people have made clear commitments to fulfill important roles

**Comment by eduardovegap** [comment]
No feedback was provided. Closed until further notice.
