### ISSUE TITLE
Dune analytics coordination

### ISSUE THREAD

**Issue by Zeptimus** [CommonsBuild/coordination#1210]
## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by GriffGreen** [comment]
1st week the goal is to get a polished version

2nd week get feedback and integrate

**Comment by natenatesoo** [comment]
Done! Yay!
