### ISSUE TITLE
FAQ for Gitbook

### ISSUE THREAD

**Issue by eduardovegap** [CommonsBuild/coordination#1211]
## 👇🏽  What is this issue about? Give as much detail as you can. 

We need to update the Gitbook. Content is outdated and new info needs to be added. The priority is to develop a FAQ for guides, so they can have a script to use for replying frequent questions on the Discord. But also, a repository on the TEC Handbook. 

Temporaly assigned to Gideon.

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. Get questions and potential answers.
2. Create a document sync with Gitbook FAQ.
3. Passed it on to Guides and then move on with WG FAQ.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@gideonro 

## 🔗  Are there links or docs related to this issue?

https://docs.google.com/document/d/1jc7DGXWuslPbAGqdte245AW0az8E_7Egzyq1l0hBMek/edit#

https://docs.google.com/document/d/1zU4j_O09VHk9Jd29hIuSCcYfIfHJQ0Lo/edit?usp=sharing&ouid=101908942387065528643&rtpof=true&sd=true

## 👀  Who should be in the loop about this issue?
@

**Comment by GriffGreen** [comment]
WG's FAQ!

What are the common questions we all get?

**Comment by GriffGreen** [comment]
Great for Twitter too

**Comment by Costa91** [comment]
FAQ section added to the TEC Handbook.
