### ISSUE TITLE
Proposal Inverter - TEC deliverables as a PI contributor

### ISSUE THREAD

**Issue by divine-comedian** [CommonsBuild/coordination#1215]
## 👇🏽  What is this issue about? Give as much detail as you can. 
We need to establish clear deliverables that the TEC can contribute to the Proposal Inverter Dogfooding proposal 

This is the current working doc 
https://docs.google.com/document/d/10Yq9LltmqWvX-6Mbki2DEgwfdKaBjRZJMdu8iSQETDQ/edit?usp=sharing

Comms WG @chuygarcia92  has offered to draft a roadmap and some deliverables in the realm of DAO outreach and marketing 

--- 
With assistance from @Mertozdal @LinuxIsCool

**Comment by tamarandom** [comment]
Forum update here: https://forum.tecommons.org/t/dogfooding-the-proposal-inverter-tec-as-a-payer-funder-sponsor/804/7

Hey @divine-comedian is there any other update you want to add to this issue?

**Comment by tamarandom** [comment]
@divine-comedian closing this issue since the proposal is live on Gardens.
