### ISSUE TITLE
Distribute the 1hive video

### ISSUE THREAD

**Issue by GriffGreen** [CommonsBuild/coordination#1218]
## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by mount-manu** [comment]
We've sent this through our bi-weekly newsletter and we also gave it some Twitter exposure so we can consider this done.
