### ISSUE TITLE
Legal WG funding proposal

### ISSUE THREAD

**Issue by iviangita** [CommonsBuild/coordination#1222]
## 👇🏽  What is this issue about? Give as much detail as you can. 
Here's the draft proposal: https://docs.google.com/document/d/1xxgmHVtVX6w3ErP6uw9eKN1yBBja4w31gZOcpsHpOIU/edit?usp=sharing

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@GriffGreen 

## 👀  Who should be in the loop about this issue?
@

**Comment by iviangita** [comment]
Posted on the forum: https://forum.tecommons.org/t/legal-wg-funding-proposal-contingency-fund-and-retroactive-bonus/945

**Comment by tamarandom** [comment]
On gardens! Closing this issue.
