### ISSUE TITLE
Requests to move frozen TEC to new wallet

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#1224]
## 👇🏽  What is this issue about? Give as much detail as you can. 
Hi @liviade1 I am dropping this here so we can keep track of it. Below are the notes from the Stewards' weekly. 

Requests re compromised wallet. Request to move vested, untransferable TEC tokens to diff wallet. 
- Technical feasibility: Yes. mint and burn in one tx
- Request would go to General Magic to execute 
- Social feasibility: able to confirm the requestor is legit 
- Expectation: can take up to a month (priorities, ethDenver, etc)
- Need: someone to own this (get more information, do we do this?, if yes, define process, share, follow-through these cases)
**- Idea: have the requestor make the request directly to the community!**
**--> Livia willing to take this on.** 

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by natenatesoo** [comment]
Needs Update from CommonStack on process and information.

**Comment by liviade1** [comment]
Pineapple said he wants to wait for the tokens to be liquid (he still has access to his wallet even thought it is compromised) 
vyvyvi also wants to change his wallet - he said he would talk to pineapple so perhaps they submit a proposal together

**Comment by tamarandom** [comment]
Update: @liviade1 will create a quick forum post to let community know how to make a proposal for change of wallet address.

**Comment by liviade1** [comment]
https://forum.tecommons.org/t/compromised-wallets-with-vested-tec-tokens-how-to-proceed/944
