### ISSUE TITLE
Monthly compensation distribution 

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#1227]
## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by eduardovegap** [comment]
i recommend to use: https://app.dework.xyz/

**Comment by eduardovegap** [comment]
Most of the active contributors sent their request. The process went smoothly. Today we should be doing the distributions.

**Comment by tamarandom** [comment]
Huge milestone... done!

**Comment by tamarandom** [comment]
@eduardovegap completed for this month!

**Comment by tamarandom** [comment]
Dupe of #1327

**Comment by tamarandom** [comment]
Hey @eduardovegap, passing the torch!

**Comment by eduardovegap** [comment]
Repeated task, closing it now.
