### ISSUE TITLE
Transparency vs privacy arround multisig forum post

### ISSUE THREAD

**Issue by Zeptimus** [CommonsBuild/coordination#1228]
## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by natenatesoo** [comment]
Only thing this needs is a community vote on the issue.

**Comment by Zeptimus** [comment]
done
