### ISSUE TITLE
TEC Website should point to TEC Handbook, not TEC Source

### ISSUE THREAD

**Issue by gideonro** [CommonsBuild/coordination#1229]
## 👇🏽  What is this issue about? Give as much detail as you can. 
Right now the link for Gitbook from the bottom of the page on the TEC website points to TEC Source. It should point to TEC Handbook instead. 
![Screen Shot 2022-02-14 at 4.32.10 PM.png](https://images.zenhubusercontent.com/615b4fece819bd9e3a821b1b/7dfe9d40-8c11-4768-a3c6-4176c7315a86)

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. Link is fixed and points to Handbook
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@natenatesoo 

## 👀  Who should be in the loop about this issue?
@

**Comment by natenatesoo** [comment]
Additionally, the same link is used in the Gardens Wiki link which should be changed to the link for the TEC Handbook.

**Comment by kristoferlund** [comment]
Perhaps [thefredo1000](https://github.com/thefredo1000) or @mount-manu can take this issue?

**Comment by kristoferlund** [comment]
Created an issue in the tec-web repo as well: https://github.com/CommonsBuild/tec-web/issues/40

**Comment by tamarandom** [comment]
This is the link for the handbook: https://app.gitbook.com/@token-engineering-commons/s/tec-handbook/

**Comment by thefredo1000** [comment]
I though I made this change but I only pushed the changes to my fork, the changes to the official repo are in [this PR](https://github.com/CommonsBuild/tec-web/pull/41).

**Comment by tamarandom** [comment]
Looks like that PR is merged so will close this now.
