### ISSUE TITLE
Transparency Audit (Jan-Mar 2022)

### ISSUE THREAD

**Issue by iviangita** [CommonsBuild/coordination#1230]
This issue is about transcribing the data from our Dune Analytics, Snapshot, Dework, and Gardens accounts into the actual audit document that our WG is preparing. More specifically it involves getting each WG's contributors account addresses, cross-referencing that with the actions taken by the user (e.g. votes, bounty disbursements, etc.), and using that to paint a clearer picture of our community's emergent, value-creation processes. 

Tentative date of completion is mid-to-late April.

**Comment by mount-manu** [comment]
**Update from Zepti:** This epic's description has been expanded upon. Worth noting is the fact that this won't be completed for another 1 or 2 more sprints. A friendly reminder to @st8tikratio to sync with Zepti to give the issues within this epic more structure (as you guys were planning to do).

**Comment by Zeptimus** [comment]
epic closed :D https://www.figma.com/proto/JOrcjzjhxVE5s2imJBbnOa/TEC-Transparency-Audit-JAN-MARCH-'22?node-id=219%3A339&scaling=min-zoom&page-id=0%3A1
