### ISSUE TITLE
Transparency Audit - Part 1: Processes

### ISSUE THREAD

**Issue by iviangita** [CommonsBuild/coordination#1231]
## 👇🏽  What is this issue about? Give as much detail as you can. 

This covers most the cultural procedures that are relevant to the community at large, for example:

a. The Advice Process
b. Creating a proposal on Snapshot
c. Submitting funding and cultural proposals
d. Nominating and offboarding stewards
e. Requesting credentials
f. Etc

Information to be included:

a. Documentation of these processes
b. When the process has been created and why
c. When the process has been stopped and why

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@Zeptimus @iviangita 

## 🔗  Are there links or docs related to this issue?
https://forum.tecommons.org/t/transparency-audit-report-a-new-approach/673/3

## 👀  Who should be in the loop about this issue?
@

**Comment by mount-manu** [comment]
**Update from Ivi:** This is still in progress but here's what we've got so far:
https://docs.google.com/document/d/1z2TDCnHKYyiFTvwueBxnt9BC4AYRI504YyduIj19-Go/edit?usp=sharing

**Comment by Zeptimus** [comment]
done https://www.figma.com/proto/JOrcjzjhxVE5s2imJBbnOa/TEC-Transparency-Audit-JAN-MARCH-'22?node-id=219%3A339&scaling=min-zoom&page-id=0%3A1
