### ISSUE TITLE
Transparency Audit - Part 2: Decisions

### ISSUE THREAD

**Issue by iviangita** [CommonsBuild/coordination#1232]
## 👇🏽  What is this issue about? Give as much detail as you can. 
This covers important decisions that don’t go through community voting:

a. Made internally (within smaller groups) that affect the community, for example:

- Choosing and offboarding stewards

- Default values of params in the dashboard

b. Went through the advice process, for example:

- Conducting a transparency audit
- The Covenant

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@Zeptimus @iviangita 

## 🔗  Are there links or docs related to this issue?
https://forum.tecommons.org/t/transparency-audit-report-a-new-approach/673/3 

## 👀  Who should be in the loop about this issue?
@

**Comment by Zeptimus** [comment]
done https://www.figma.com/proto/JOrcjzjhxVE5s2imJBbnOa/TEC-Transparency-Audit-JAN-MARCH-'22?node-id=219%3A339&scaling=min-zoom&page-id=0%3A1

**Comment by Zeptimus** [comment]
done https://www.figma.com/proto/JOrcjzjhxVE5s2imJBbnOa/TEC-Transparency-Audit-JAN-MARCH-'22?node-id=219%3A339&scaling=min-zoom&page-id=0%3A1
