### ISSUE TITLE
Transparency Audit - Part 4. Funding pool and reserve and fund movement

### ISSUE THREAD

**Issue by iviangita** [CommonsBuild/coordination#1237]
## 👇🏽  What is this issue about? Give as much detail as you can. 
This covers the financial specifics pertaining to internal accounting and treasury management. We will use graphs and Dune Analytics to present most of this data.

a. $TEC

- Revenue (inflow) from the Reserve
- Expenses (outflow) from the Commons Pool (fund distribution)
WGs
TE Projects
Rewards
Other ops expenses
Total funding being held in the Commons Pool and Reserve

b. TE Projects

- Funding proposals
- *Results: How are those funds being used after the proposal passed

c. WG and contributors

- Funding proposals
- *Results: How are those funds being used after the proposal passed and what the WG accomplishes
- Excess budget

d. Treasury management and Rewards
(Note: These two projects might turn into a working group later on. Therefore,
this part of the audit will be integrated in 4c.)

- Funding proposals
- *Results: How are those funds being used after the proposal passed
- Excess budget

*Transparency WG is available to help on that matter if the WG/project needs it.

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by Zeptimus** [comment]
done https://www.figma.com/proto/JOrcjzjhxVE5s2imJBbnOa/TEC-Transparency-Audit-JAN-MARCH-'22?node-id=219%3A339&scaling=min-zoom&page-id=0%3A1
