### ISSUE TITLE
Transparency Audit - Part. 5. $TEC holders ranking (data from Blockscout)

### ISSUE THREAD

**Issue by iviangita** [CommonsBuild/coordination#1238]
## 👇🏽  What is this issue about? Give as much detail as you can. 

Wallet addresses holding the top 30% of the total supply of $TEC
- Ranking of addresses with their respective %

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by Zeptimus** [comment]
done https://www.figma.com/proto/JOrcjzjhxVE5s2imJBbnOa/TEC-Transparency-Audit-JAN-MARCH-'22?node-id=219%3A339&scaling=min-zoom&page-id=0%3A1
