### ISSUE TITLE
Transparency Audit - Part 6. Monitoring community buying & selling activities (wallet addresses, no names)

### ISSUE THREAD

**Issue by iviangita** [CommonsBuild/coordination#1239]
## 👇🏽  What is this issue about? Give as much detail as you can. 

a. General view of the $TEC (in graphics)

- Market supply
- Total number of token holders
- Total amount of $TEC in Commons Pool
- Total amount of wxDAI in Reserve
- Anything else?

b. Transactions that move the price by x% in x period of time
c. Top 10 buying and top 10 selling (based on number of $TEC tokens)
d. How much is being bought and sold?
## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by Zeptimus** [comment]
done https://www.figma.com/proto/JOrcjzjhxVE5s2imJBbnOa/TEC-Transparency-Audit-JAN-MARCH-'22?node-id=219%3A339&scaling=min-zoom&page-id=0%3A1
