### ISSUE TITLE
Transparency Audit - Part 7. Governance tokens

### ISSUE THREAD

**Issue by iviangita** [CommonsBuild/coordination#1240]
## 👇🏽  What is this issue about? Give as much detail as you can. 
a. How many governance tokens are minted (total supply)
b. How many governance tokens are available for voting
c. How many governance tokens are being used in farming, LP, etc.
d. Where/how they are used
- proposals voted on using the the tokens
- Farming, LP

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by tamarandom** [comment]
Update: assigned to Enti. ;)

**Comment by Zeptimus** [comment]
done https://www.figma.com/proto/JOrcjzjhxVE5s2imJBbnOa/TEC-Transparency-Audit-JAN-MARCH-'22?node-id=219%3A339&scaling=min-zoom&page-id=0%3A1
