### ISSUE TITLE
Update Working Group on the website 

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#1241]
## 👇🏽  What is this issue about? Give as much detail as you can. 
We can remove:
Parameters
Commmons Swarm

We can add (need a short write-up, @liviade1 is the Steward)
Rewards 

@mount-manu dropping this on you until you casale.eth is on github. 🙏🏼

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by tamarandom** [comment]
Hey @thefredo1000! While you are making those updates, there are two small things to update too:

Soft Gov and Steward weekly meetings are trading places.
Stewards will take place on Tuesdays at 7pm CET. 
Soft Gov will take place on Wednesdays at 7pm CET.

**Comment by gideonro** [comment]
Piling on with 2 more quick fixes to the website @thefredo1000  
On the https://tecommons.org/join page, the Handbook link points to the TEC Source but should point here:
https://token-engineering-commons.gitbook.io/tec-handbook/
Also the Medium link points to our TEC profile, but it should point to our publication, which is here:
https://medium.com/token-engineering-commons

See image
![Screen Shot 2022-04-07 at 1.28.31 PM.png](https://images.zenhubusercontent.com/615b4fece819bd9e3a821b1b/a2bebead-8e91-46f8-82ef-e6d6035b7e10)

**Comment by thefredo1000** [comment]
[This PR](https://github.com/CommonsBuild/tec-web/pull/41) has the changes, it's now live.

**Comment by mount-manu** [comment]
I was lagging on this issue but @thefredo1000 took the initiative and brought it home.
