### ISSUE TITLE
Present at TEA monthly presentation. 

### ISSUE THREAD

**Issue by eduardovegap** [CommonsBuild/coordination#1244]
## 👇🏽  What is this issue about? Give as much detail as you can. 

TEA invites us every month to present at their Monthly Introduction to TE, This time I will be presenting our community.

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by tamarandom** [comment]
Sorry I missed it, I know you did a great job!
