### ISSUE TITLE
Brainstorm on ritualizing "agency" in the community 

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#1246]
## 👇🏽  What is this issue about? Give as much detail as you can. 
How can we develop rituals to help new community members practice agency.
Will flesh this out over the course of the Sprint. What do we currently do?  How can we help bridge the gap better from a permissioned work mindset to a permission-less work mindset.

Get the conversation started .....

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by tamarandom** [comment]
@durgadasji suggestion: "give permission" to show up with autonomy and agency, use liberating structure card for opening WG meetings  

 @eduardovegap volunteers to help bring this into the Orientation call.

**Comment by mount-manu** [comment]
**Update from Edu:** Trying to find ways to create engagement and safe spaces for contributors to develop themselves (technically and socially) on the TEC.

**Comment by tamarandom** [comment]
Do we have next steps on this brainstorm? **Who** will do **what** by **when**? 😇

Maybe this can be a brainstorm in SoftGov or even a discussion group in the Stewards Council? Other ways we can tackle it, @eduardovegap ?

**Comment by eduardovegap** [comment]
We will tackle this, by the member's experience / journey on the TEC. 

Added to the Epic.

**Comment by eduardovegap** [comment]
We have changed the focus, we are no longer looking to onboard "contributros" to WGs. We act more like a social layer that guides folks on the TE ecosystem.
