### ISSUE TITLE
Retro action: Create a Gardens Party where members can discuss and debate on current proposals within Gardens. (Communitas?)

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#1254]
## 👇🏽  What is this issue about? Give as much detail as you can. 
@eduardovegap @liviade1 dropping the retro action in here to be thought through / executed for this Sprint.

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by tamarandom** [comment]
This idea came up again in today's retrospective. 

![Screen Shot 2022-03-17 at 8.39.57 PM.png](https://images.zenhubusercontent.com/5faaa1d038c6409364f7830c/72c3f0dc-d29e-48f0-96b6-284210bb08a7)

**Comment by eduardovegap** [comment]
I have discusses this with Angela, rather than just Garden's parties, it's an educational space that should be running weekly or every two weeks. The only educational space we have at the moment is LABS, so this is still in development, but for next sprint we should have something.

**Comment by tamarandom** [comment]
Next steps:
- @liviade1 and @eduardovegap to sync on accountability + this space for info/debate
- Pick a date, invite proposal sponsors, promote

**Comment by eduardovegap** [comment]
Agreed with @GriffGreen to host it every two weeks, waiting for his agenda to match a time we can do it.

**Comment by GriffGreen** [comment]
Sorted out a time for this week but it's on Friday which is kind of lame for the party people in europe... so then we will move it to right before soft gov every other week.

**Comment by tamarandom** [comment]
Update: Will launch next Friday at 6pm CET!

**Comment by natenatesoo** [comment]
@tamarandom Can this issue be closed?

I will keep in product backlog until more information emerges.

Thanks!

**Comment by tamarandom** [comment]
Closing old issues.
