### ISSUE TITLE
Gravity Q1 2022 blog post

### ISSUE THREAD

**Issue by JuankBell** [CommonsBuild/coordination#1256]
## 👇🏽  What is this issue about? Give as much detail as you can. 
Our last medium article was last year! there are so many things to communicate in this start of 2022 that we need to make a new medium article explaining all what we look forward this year. @gideonro offered to support an we will meet on tuesday 8th

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. Article explaining whats up for gravity and inviting to graviton training in april with clear expectations.
2. Broad distribution of the article
3. Clarity around content creation and synergy with editorial board

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@durgadasji @gideonro 

## 🔗  Are there links or docs related to this issue?
https://hackmd.io/fPQnk34_SmyQWLh8Qepk2A

## 👀  Who should be in the loop about this issue?
@tamarandom

**Comment by JuankBell** [comment]
Moved the development of the article to google docs. Contributors are: @scottbenjd @innov8tor3 @gideonro and @JuankBell  https://docs.google.com/document/d/1hC3CRWzcljSvHQ7iRQ1g_m8uCrPpRQ6Bdu6Ghw5N_jQ/edit

**Comment by mount-manu** [comment]
**Juanka's Update:** Work has been done around this but it's mainly just ideas that need to be polished into something tangible. The topics that will be written about are: Gravity's value proposition; current Gravity events and an invitation to the next Graviton training; and the philosophy behind our trust creation and conflict mediation processes. The tentative date for the completion of this issue, currently, is end of March / beginning of April.

**Comment by JuankBell** [comment]
https://medium.com/p/3afa66e43707
