### ISSUE TITLE
How can TEC support community building for cadCAD and TokenSpice? 

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#1258]
## 👇🏽  What is this issue about? Give as much detail as you can. 
Turn this into actionable items:

@GriffGreen  [Mar 4, 2022 at 12:40:41 AM]:
...Numfocus is a large portfolio of computational science libraries. He thought it would be great to also donate to them.

We should probably aslo find a way to support cadCAD and Token Spice as well... but what they really need are proposals for building Community.

I think we could support a community manager to hold space regularly either via LTF or cadCAD Labs ( @chriscatoya )

GM could probably do the Hiring and find the right person if TEC could pass a proposal and help someone make the skeleton plan

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by mount-manu** [comment]
Update from Edu: They need someone to hold open office hours where people can hack on their stuff and know they have a person around to answer questions. But we just need a way to support the developers of open source models: its probably via a sort of cadCAD mutual aid group. So we need a nerdy community manager to cat herd for an expert to support a weekly (or more) occurring meeting.

**Comment by tamarandom** [comment]
Peter opened a proposal for Advice Process on the forum: https://forum.tecommons.org/t/cadcad-community-funding-proposal-ama-session/938

Closing.
