### ISSUE TITLE
Gitcoin Grants --> GR13

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#1260]
## 👇🏽  What is this issue about? Give as much detail as you can. 
@cranders1 noticed that the TEC grant is inactive. He offered to help.... 

We should also have a templated checklist that is reusable for each round. Something like the one we just made for Commons Stack - https://docs.google.com/document/d/1adbs05kkiS4YTsPryTwT5tPc-enJ3s_TejopjbH0EGU/edit#

And a recurring issue that gets pulled into the first Sprint of the new round.

@cranders1 is it ok that I assign this to you? 

@chuygarcia92 @acidlazzer -- once it is live, we will want to promote it. 

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by tamarandom** [comment]
Looks like it is live now but still saying round 12 ... who is the person taking care of this? @chuygarcia92 ... are you? ;) 

![Screen Shot 2022-03-10 at 7.56.24 PM.png](https://images.zenhubusercontent.com/5faaa1d038c6409364f7830c/0043ac12-5d77-4777-b7f0-3c5fb265851c)

**Comment by cranders1** [comment]
@tamarandom @chuygarcia92 
i updated the grant with a brief blurb and a bunch of links
now live on grants explorer & eligible for matching
will try to revisit later with more thorough update
if anybody has a list or bullets of accomps since dec '21 (GR12) or even a wow factor slide, ill take it.

**Comment by tamarandom** [comment]
THANK YOU to whomever did this!

![Screen Shot 2022-03-11 at 8.39.39 PM.png](https://images.zenhubusercontent.com/5faaa1d038c6409364f7830c/b13f2188-76cc-4920-9799-f218802717b4)

**Comment by tamarandom** [comment]
Wait ... what do we mean by this "Our GR13 updated grant is forthcoming very soon. Apologies for the oversight 😎" ??

@cranders1 @chuygarcia92 ??

**Comment by cranders1** [comment]
I fixed it @tamarandom . Just added a little more relevant info.
Unfortunately & fortunately, I can't just rattle off all the highlights any more ;)
Link checking always a help...Cheers.

**Comment by tamarandom** [comment]
Thank you @cranders1! Closing this issue.

**Comment by cranders1** [comment]
always a pleasure @tamarandom
