### ISSUE TITLE
Create workflows for TEC and its people

### ISSUE THREAD

**Issue by eduardovegap** [CommonsBuild/coordination#1261]
## 👇🏽  What is this issue about? Give as much detail as you can. 

There are 4 keypoints for Gideon's document:

welcoming and orienting
assessing and ushering -> changed potentially to self-assesment. 
supporting working groups
supporting overall community development. 

We need to develop workflows to achieve this 4 points.

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. Action items that are potentially executable 
2. Cohesiveness in between the actions items and the 4 points
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 🔗  Are there links or docs related to this issue?

https://docs.google.com/document/d/1U56cG2uAN2zPpDVEdDwVqlxjSFQMJ2KhDyrbCvdWvcc/edit

## 👀  Who should be in the loop about this issue?
@tamarandom @gideonro

**Comment by tamarandom** [comment]
Update from @eduardovegap : https://www.figma.com/file/W1ZXqBFuE0CHEKZmmgIE8V/WorkFlows-for-TEC?node-id=0%3A1

**Comment by eduardovegap** [comment]
Latest iteration: https://www.figma.com/file/rr2EaII46SP5YOnWzM9tVQ/TEC-Engagement-Processes?node-id=0%3A1

**Comment by mount-manu** [comment]
**Update from Edu:** We're currently elaborating on the progress presented today in the [TEC Engagement Processes Figma file](https://www.figma.com/file/rr2EaII46SP5YOnWzM9tVQ/TEC-Engagement-Processes?node-id=103%3A358). When done, the workflows will have been structured accordingly.

**Comment by eduardovegap** [comment]
We created and epic to recognize this process, I'd close this issue at least until next quarter when we will probably keep adding more workflows.
