### ISSUE TITLE
Update of Communitas Manifesto

### ISSUE THREAD

**Issue by eduardovegap** [CommonsBuild/coordination#1262]
## 👇🏽  What is this issue about? Give as much detail as you can. 

The manifesto has reached a point that it needs update. We are proposing an update based on parts of the document "TEC and it's people".

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. The Manifesto reflects out currently mission and vision.
2. The WG members agree to its content. 
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 🔗  Are there links or docs related to this issue?

https://docs.google.com/document/d/1g9vycoqIZkg83KyRM-7wMeCN-QxZTSfO-Ofq8o7U9pQ/edit#heading=h.i8i7yypx0t4z

## 👀  Who should be in the loop about this issue?
@

**Comment by mount-manu** [comment]
**Update from Gideon:** We're currently elaborating on the progress presented today in the [TEC Engagement Processes Figma file](https://www.figma.com/file/rr2EaII46SP5YOnWzM9tVQ/TEC-Engagement-Processes?node-id=103%3A358). When we're done, we'll update the manifesto accordingly.

**Comment by tamarandom** [comment]
Hey @gideonro - I accepted the edits and @eduardovegap and I updated the rest. If you are happy with the final result, please feel free to close this issue!! 

https://docs.google.com/document/d/1g9vycoqIZkg83KyRM-7wMeCN-QxZTSfO-Ofq8o7U9pQ/edit#

**Comment by gideonro** [comment]
Just updated the doc, per conversation w/ Tam, to reflect the top-level info in the summary page from our collaborations in Figma. Just needs to be reviewed by @tamarandom and @eduardovegap.

**Comment by tamarandom** [comment]
It looks a lot cleaner and easier to read this way. They all look good to me! @eduardovegap I'm going to close this now but please have a look too!
