### ISSUE TITLE
collab with communitas to create awareness to proposals 

### ISSUE THREAD

**Issue by liviade1** [CommonsBuild/coordination#1272]
## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by mount-manu** [comment]
@eduardovegap were there any action points sketched out during this week's Soft Gov call, something for us to bring to Communitas and start getting minds & hearts into proposals?

**Comment by liviade1** [comment]
hey @mount-manu we didn't have time to get to this agenda point last week, but we will today, thanks for checking in

**Comment by tamarandom** [comment]
Update: the piece of work here is to brainstorm ideas of how to get the community more involved / be more informed about proposals. One idea that was raised: set aside a weekly time for debate about proposals on the forum or in CV. Others?

**Comment by liviade1** [comment]
conversation spinned to async work management https://hackmd.io/@lPFQ61eAQAap3vUN520DPw/SkR2rg04q
