### ISSUE TITLE
update the covenant 

### ISSUE THREAD

**Issue by liviade1** [CommonsBuild/coordination#1274]
## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. add period for advice process (5 days unless is urgent?) copy from giveth 
2. cv terms 
3. graduated sanctions for lack of accountability? 

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by mount-manu** [comment]
**Lívia's Update:** @iviangita: a friendly reminder to advance this issue on next week's Legal call 📄  or maybe sync / async with Lívia before if you're feeling bold 😎

**Comment by liviade1** [comment]
https://ipfs.blossom.software/ipfs/QmfLK4DPMUxvbh5N8UkHtk3ZWzdoPpsacfsqhCDqNPHM7i 

https://docs.google.com/document/d/1uBhtYLvx5PIGzYoEDa1HYxxmc9W3pPpP_cXxXfn1IgA/edit @iviangita

**Comment by liviade1** [comment]
include a reputation threshold - bellow certain point people would need an escrow to submit proposals. 
- what info we need to set that up 
graduated sanction - 
if you didn't deliver on a proposal you can't submit a new one unless xyz

**Comment by liviade1** [comment]
add that every content produced in the TEC is open source

**Comment by mount-manu** [comment]
**Update from @iviangita :** CV terms will be done this week and then linked into this issue so that they can be incorporated into the covenant.

(I've also shared a resource with Lívia that might help unblock the graduated sanctions part of this issue, assuming that's still causing friction).

**Comment by liviade1** [comment]
added new period for advice process to the poly gov post that is linked in the covenant

**Comment by liviade1** [comment]
added new period for advice process to the poly gov post that is linked in the covenant https://forum.tecommons.org/t/tec-polycentric-governance-framework/717

**Comment by mount-manu** [comment]
**Update from Ivi**: Final changes have been submitted, @iviangita will be reviewing them and then she'll post the covenant on the forum.

**Comment by tamarandom** [comment]
Hey @iviangita - can this be closed now? Is the covenant final?

**Comment by iviangita** [comment]
Closing! Posted the revised Covenant in the forum https://forum.tecommons.org/t/tec-community-covenant/572/14?u=iviangita
