### ISSUE TITLE
run script to replace quantifiers 

### ISSUE THREAD

**Issue by liviade1** [CommonsBuild/coordination#1275]
## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. add a map for how to automate this process 
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by kristoferlund** [comment]
Replacing quantifiers is not the best of practices. Quant round 3 instead we try assigning 4 quants per praise. If someone drops off that then has less impact on avg praise score. Closing for now.
