### ISSUE TITLE
Add all SourceCred params to period1 template

### ISSUE THREAD

**Issue by kristoferlund** [CommonsBuild/coordination#1278]
## Details

All SourceCred config details should be added to `params.md` of praise round 1. Not only the node weights etc but also other relevant settings the community might want to change in the future.

https://github.com/CommonsBuild/tec-rewards/blob/main/round-1/params.md

![image](https://user-images.githubusercontent.com/9698363/159258288-e48e6b1b-3885-40fa-addf-a27df6fc47c3.png)

**Comment by divine-comedian** [comment]
closing this issue since we won't be using sourcecred params until ~ round 12
