### ISSUE TITLE
Execute quant round 1 payout

### ISSUE THREAD

**Issue by kristoferlund** [CommonsBuild/coordination#1279]
## Details

The RAD Dashboard produces a distribution file. This distribution file is sent to the Reward Board DAO where board votes to approve payout.

⚠️ Only users who have activated their accounts can receive payouts.

## Open questions

**⁉️⁉️⁉️⁉️ How do we handle payouts to users who activate at a later time?**

## 🔗 The links and docs related to this issue

**Comment by divine-comedian** [comment]
waiting for finalization and publication of reward system parameters

**Comment by divine-comedian** [comment]
DONE! 
 
 votes 2 and 3 on the reward board
 https://aragon.1hive.org/#/rewardboardtec/0x83ddc88de748c2389bf4d66f8708434fee599b7b/
