### ISSUE TITLE
Promote first quant payout

### ISSUE THREAD

**Issue by kristoferlund** [CommonsBuild/coordination#1280]
## Details

When the first quant has been paid out we must let the community (and the world) know! 

## Open questions

- 

## 🔗 The links and docs related to this issue

**Comment by divine-comedian** [comment]
we've been using the forum post template drafter and @0xNuggan is taking care of weekly publishin, keeping the community up to date, for every forum post we allow 48 hrs for community review before going to the reward board DAO - calling this issue DONE! 

here's the first forum post for reference: 
https://forum.tecommons.org/t/tec-rewards-distribution-july-2021/1004
