### ISSUE TITLE
Post first quant analysis to forum

### ISSUE THREAD

**Issue by kristoferlund** [CommonsBuild/coordination#1281]
## Details

After first quant payout we need to make the analysis together with some comments available to the community. A forum post?

- Summarise any insights from the quantifier tweak session
- Add insights from the post quant analysis (the RAD Dashboard)
- Link to the RAD Dashboard
- What else?

## Open questions

- 

## 🔗 The links and docs related to this issue

**Comment by Zeptimus** [comment]
Hey Kristofer where can we see the data?

**Comment by kristoferlund** [comment]
@Zeptimus, find the RAD Dashboard here: https://github.com/CommonsBuild/tec-rewards

Check in with @0xNuggan for some RAD Dashboard onboarding. But perhaps we'll wait with the analysis until we have the real SourceCred data?

**Comment by liviade1** [comment]
I think it would still be interesting to have the praise ones there -- @0xNuggan what you think? is there someone that could help you posting the first analysis to the forum?

**Comment by 0xNuggan** [comment]
@Zeptimus , @chuygarcia92  and I are on it!

**Comment by divine-comedian** [comment]
I settled for something a bit simpler given there's quite a bit of overhead to write something so complicated...

https://forum.tecommons.org/t/tec-rewards-distribution-july-2022/1004/
