### ISSUE TITLE
Execute first SourceCred grain distribution

### ISSUE THREAD

**Issue by kristoferlund** [CommonsBuild/coordination#1282]
## Details

- Make a Grain distribution dated July 31 2021
- Export and save data to `sourcecred.csv` in `tec-rewards` repo: https://github.com/CommonsBuild/tec-rewards/blob/main/round-1/sourcecred.csv

## 🔗 The links and docs related to this issue

**Comment by mateodaza** [comment]
Here's the tool to get csv from grain and cred

https://observablehq.com/@mateodaza/cred-and-grain-csv-downloader

**Comment by divine-comedian** [comment]
check w/ kristofer to see if this is done

**Comment by divine-comedian** [comment]
@mateodaza @kristoferlund  is this done?

**Comment by mateodaza** [comment]
@divine-comedian give me green light and I'll do the grain distribution - then we can get the csv

**Comment by divine-comedian** [comment]
@mateodaza assuming everything is done are there any potential dangers until waiting to distribute the gran until when we need to do the quant payout using it - for june 2022.

In my head we can do it now and call it done but this seems like and action hard to undo in the future if something in our plans change.

**Comment by kristoferlund** [comment]
How about doing the first Grain distribution Sunday June 12? The quant period that starts the following Friday, Jun 17, will be the first period to include June data.

**Comment by divine-comedian** [comment]
we made the first grain distro but the results are less than ideal, we need to continue merging sourcecred accounts and tweak some distribution settings in order to get an accurate distribution.

we are able to remove grain distributions and recalculate them as needed before rewards go out.

**Comment by natenatesoo** [comment]
@divine-comedian I will add this to the current sprint! Keep up the good work!

**Comment by divine-comedian** [comment]
We're doing some brainstorming to overcome the technical hurdles on sourcecred, there will be a sourcecred distribution in probably two weeks.

**Comment by tamarandom** [comment]
Closing old issues.
