### ISSUE TITLE
improve the marking of duplicates 

### ISSUE THREAD

**Issue by liviade1** [CommonsBuild/coordination#1287]
## 👇🏽  What is this issue about? Give as much detail as you can. 
it's been time consuming and confusing to mark duplicates, how can we standardize the process a little bit more? 

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. can we have a checkbox to mark multiple duplicates at once? 
2. keyword search? 
3. adjust praise (on duplicate reference) based on impact - i.e increase praise reference value if 10 different people praise the same thing vs 1 person multiple times, or just one or two people praising.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by tamarandom** [comment]
Hey @liviade1 this should be in the Praise repo not Coordination, right? 

https://github.com/CommonsBuild/praise_frontend/issues
