### ISSUE TITLE
Gravity @ devconnect!

### ISSUE THREAD

**Issue by JuankBell** [CommonsBuild/coordination#1294]
## 👇🏽  What is this issue about? Give as much detail as you can.
I will be going to EthAmsterdam and want to schill Gravity, also taking into account that the graviton training will start on the 26th of April. 

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. Presenting Gravity and having contact with people interested and supporting. 
2.  Having new people coming to the graviton training

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@GriffGreen @Zeptimus 

## 👀  Who should be in the loop about this issue?
@Angela

**Comment by mount-manu** [comment]
**Juanka's Update:** No space booked yet but currently in talks with Skylar from Ethereum Foundation to invite all the speakers involved so as to talk about the topics that'll be discussed in the conference. Also: Angela Kreitenweis has opened the doors for TE Academy to assist in providing a platform through which to reach out to potential speakers within our community.

**Comment by JuankBell** [comment]
https://thinkingthursdays.substack.com/p/potential-in-the-ebb-and-the-flaw?s=w

![https___bucketeer-e05bbc84-baa3-437e-9518-adb32be77984.s3.amazonaws.com_public_images_6b5e9286-064f-4b65-899a-f037193a6c8a_4032x3024.webp](https://images.zenhubusercontent.com/5fb57c9c5472cf79e80e7f7e/0afb6bb6-9144-4c5c-9a10-1471962d0823)

![FRCASAwX0AIL5LH.jpeg](https://images.zenhubusercontent.com/5fb57c9c5472cf79e80e7f7e/c72666d9-5658-4279-ad74-3f92e745a2a4)
