### ISSUE TITLE
Coordination with TEA

### ISSUE THREAD

**Issue by eduardovegap** [CommonsBuild/coordination#1296]
## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. Onboarding
2. Presenting TEC 
3. Workshop for TEC? 

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by mount-manu** [comment]
**Update by Edu:** We did the onboarding with Angela K., and now the ball's on @liviade1 court but we'll keep this open so as to continue collaborating with TEA and giving them a spotlight during our Orientation call and Communitas sync.

**Comment by mount-manu** [comment]
**Update from Edu**: Finished! So we closin'
