### ISSUE TITLE
Telegram community security improvements

### ISSUE THREAD

**Issue by chuygarcia92** [CommonsBuild/coordination#1301]
## 👇🏽  What is this issue about? Give as much detail as you can. 
We've been having a growing presence of scammers in the Telegram group we need to address, since it's a factor that puts our community at risk

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. A bot operates the flamethrower now
2. Scammers are instantly banned from the group and their messages deleted
3. Automation makes this prevention less time-consuming

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@zeptimus @tamarandom

## 🔗  Are there links or docs related to this issue?
https://missrose.org/ 

## 👀  Who should be in the loop about this issue?
@griffgreen

**Comment by chuygarcia92** [comment]
next step is requesting @GriffGreen to give miss rose admin access in the TG group

**Comment by GriffGreen** [comment]
> next step is requesting @GriffGreen to give miss rose admin access in the TG group

Done!

**Comment by mount-manu** [comment]
Rose has got this so we close.
