### ISSUE TITLE
Wireframes for the ABC Stats page

### ISSUE THREAD

**Issue by Zeptimus** [CommonsBuild/coordination#1302]
## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by Zeptimus** [comment]
Working on the wireframe

**Comment by mount-manu** [comment]
**Zepti's Update:** Some work has been done on this but we've yet to finish; we aim to finish (the wireframes) before Sprint's end. Here's the current progress: https://miro.com/app/board/uXjVO7-FzCI=/

**Comment by Zeptimus** [comment]
Will do a hack sesh with tam this week probably will get done in that work sesh or that same day

**Comment by Zeptimus** [comment]
Done! https://miro.com/app/board/uXjVO7-FzCI=/
