### ISSUE TITLE
Transparency audit - Stewards milestones

### ISSUE THREAD

**Issue by Zeptimus** [CommonsBuild/coordination#1305]
## 👇🏽  What is this issue about? Give as much detail as you can. 

Review stewards milestones in the audit
## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 🔗  Are there links or docs related to this issue?
https://docs.google.com/document/d/1z2TDCnHKYyiFTvwueBxnt9BC4AYRI504YyduIj19-Go/edit#

## 👀  Who should be in the loop about this issue?
@

**Comment by tamarandom** [comment]
Missed the window to add updates to the audit before it closed. Closing.
