### ISSUE TITLE
Retro action: Finance focused squad or WG. How to get started?

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#1307]
## 👇🏽  What is this issue about? Give as much detail as you can. 

We can just start with a weekly meeting! We need a champion to coordinate (find time, invite the folk, set the agenda, facilitate the call).

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by eduardovegap** [comment]
Sampo was created. This is  closed.
