### ISSUE TITLE
Retro action: Add expected milestones to proposal template so that it can be used in the audit.

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#1308]
## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by mount-manu** [comment]
**Zepti's Update:** will work on finishing this before Sprint's end.

**Comment by mount-manu** [comment]
@Zeptimus  wants to talk to you @iviangita regarding this!

**Comment by Zeptimus** [comment]
Close legal wg is doing it together with soft gov
