### ISSUE TITLE
Dune widgets not complying to start and end dates.

### ISSUE THREAD

**Issue by eenti** [CommonsBuild/coordination#1316]
## 👇🏽  What is this issue about? Give as much detail as you can. 
Some widgets from the TEC Dune Board aren't showing the correct information when using the date filter.

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@Zeptimus 

## 🔗  Are there links or docs related to this issue?
https://dune.com/tecommons/TECommons

## 👀  Who should be in the loop about this issue?
@

**Comment by tamarandom** [comment]
@Zeptimus says done!
