### ISSUE TITLE
Gitbook Editing Permission 

### ISSUE THREAD

**Issue by Costa91** [CommonsBuild/coordination#1317]
## ✨  What does success look like? 
1. Changes accepted by someone with the perms to do it or
2. Perms given to accept them

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by tamarandom** [comment]
I tried to help here, @natenatesoo, but am not able to see how I can approve the merges "in review" status!
