### ISSUE TITLE
plan and have a roadmap for the ecosystem health development 

### ISSUE THREAD

**Issue by liviade1** [CommonsBuild/coordination#1323]
## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by liviade1** [comment]
bends have been working here https://docs.google.com/spreadsheets/d/1jAXe4MhOm6cdL-yjgpk_wUkEGZPCAvpJ-lyp1eLBX4o/edit#gid=0 
he will finish this by the end of next sprint

**Comment by eduardovegap** [comment]
This need someone to execute it, and probably hire someone.
