### ISSUE TITLE
Advice process for Member Experience 

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#1325]
## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by eduardovegap** [comment]
Will be submitted next week, we are waiting only for the Writer's guild budget proposal.

**Comment by eduardovegap** [comment]
https://docs.google.com/document/d/1hxr1WxZPXqZW1D1vd-gEBtBaFPY14sy1nbjRYA1qdd8/edit 

Took longer than expected: Go straight to the section: **Membership at the TEC**

**Comment by natenatesoo** [comment]
@eduardovegap Great work!  I'm going to add this within the current sprint with the objective of finding the best way to distribute this information.  Where do we want to put it?  Gitbook, Website, etc...

Thanks!

**Comment by eduardovegap** [comment]
Process is completed. We implemented the first phase on the beginning of september: Being a member means:

1. The newcomer introduce themselves on the "introduce yourself" channel.
2. Guides welcomes them and invites them to join Orientation call. 
3. Guides praise them.
4. A week after, Guides do follow up.
