### ISSUE TITLE
Praise Transcribing for Newcomers

### ISSUE THREAD

**Issue by mount-manu** [CommonsBuild/coordination#1328]
## 👇🏽  What is this issue about? Give as much detail as you can. 
Teaching new contributors about the Praise transcription process so that they can dish our Community Call's praise while we phase out or iterate on the Praise Transcription task.

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. There's a constant influx of new contributors learning how transcribe praise; I'll teach them.
2. I can progressively delegate the Praise Transcription task to new members of our community and be certain they'll do the task correctly.
3. The Rewards System WG finds a way to eliminate the need for Praise Transcription altogether.

**Comment by tamarandom** [comment]
Now that transcribing praise is over, closing this issue!
