### ISSUE TITLE
New project sign-up. Interview and record project owner's platform sign-up problems.

### ISSUE THREAD

**Issue by clara-zi** [CommonsBuild/coordination#1329]

**Comment by tamarandom** [comment]
Hi @clara-zi 

Can you please give some more context? Is this a piece of work you are recommending for TEC?

**Comment by clara-zi** [comment]
Hi,

I’m really sorry. This issue has been posted in the wrong place (I didn’t even know I had access to TEC github). Please remove/close.

thanks

**Comment by tamarandom** [comment]
Thanks @Clara-zi! I am closing this. ;)

**Comment by clara-zi** [comment]
Thanks
