### ISSUE TITLE
TE governance guild support 

### ISSUE THREAD

**Issue by liviade1** [CommonsBuild/coordination#1331]
## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by natenatesoo** [comment]
@liviade1 I will keep this in product backlog until the issue is more defined.

If you have any updates, or wish to clarify the details of the issue, please feel free to add and move the issue into our current sprint.

Thanks!
