### ISSUE TITLE
Update the tecommons.org website with Sampo as a WG

### ISSUE THREAD

**Issue by mount-manu** [CommonsBuild/coordination#1333]
## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by chuygarcia92** [comment]
WG logo can be found in https://github.com/CommonsBuild/tec-branding-assets once it's done

**Comment by mount-manu** [comment]
Hey there @markoprljic, long time no speak! How are we doing with the logo for the Sampo WG?

**Comment by markoprljic** [comment]
Updated the repo with the logo 
https://github.com/CommonsBuild/tec-branding-assets

**Comment by chuygarcia92** [comment]
DONE!

![image.png](https://images.zenhubusercontent.com/6000e68bc28f519103606a04/1b1f97b5-ca6f-44a0-9d45-9b5c3d0fa61b)
