### ISSUE TITLE
Reimagining the Community Call's Format 

### ISSUE THREAD

**Issue by mount-manu** [CommonsBuild/coordination#1334]
## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by tamarandom** [comment]
Notes from the last Steward weekly:

Community call runs long (again)… 
What is the main purpose of the community call?
Timbox each WG presentation.
Add 15 minutes to the end of the call? Make it a 75 minute call. (two calls that are impacted)
Ok for Gravity
Praise quant 
Give spotlight a separate time 
Make efforts towards async collaboration 
Community call evolve into way to showcase TE projects, having the WG coordination take place within the Scrum events….
Slide that shows when each WG is meeting, take that out of the WG presentations on the community call 
Announcements slide (for Legal bc they need contributors)

**Comment by natenatesoo** [comment]
I'm going to close this issue do to lack of need/interest/progress.

Adjustments to community call format seems to happen naturally.  If this needs to be re-opened, please feel free to do so.  @mount-manu @tamarandom
