### ISSUE TITLE
2022 Stewards POAP 

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#1335]
## 👇🏽  What is this issue about? Give as much detail as you can. 
We want to come up with a theme for this year's Stewards POAP!

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by mount-manu** [comment]
@acidlazzer how we doing on this, tocayo?

**Comment by tamarandom** [comment]
Hey @acidlazzer I will take this on while @mount-manu is taking some time off.

**Comment by natenatesoo** [comment]
@tamarandom Are there any updates here?

I will place this issue within the current sprint.  Please feel free to update or close when you have time!

Thanks!

**Comment by acidlazzer** [comment]
The design is done, but don´t know if @tamarandom did the POAP event :)

**Comment by tamarandom** [comment]
Done and sent! Thanks to @Zeptimus for helping distribute them!
