### ISSUE TITLE
Retro action: get in contact with tokenomics DAO - they are doing something we should have available for TEs

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#1337]
## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by tamarandom** [comment]
Adding to the Stewards weekly agenda to next step this!

**Comment by tamarandom** [comment]
Note: reach out to Angela who may already be in touch with them too.

**Comment by eduardovegap** [comment]
This was accomplished by @liviade1 and they presented on the Community Call spotlight.
