### ISSUE TITLE
Build deck in Spanish for presentation next month 

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#1345]
## 👇🏽  What is this issue about? Give as much detail as you can. 
Related to #1200

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 🔗  Are there links or docs related to this issue?
This is the orientation deck: https://docs.google.com/presentation/d/1K5oKo43MVLGrwQrgRyHMbGaGUU5m2Up6/edit#slide=id.p5

This is the former Intro to TEC deck for this (but it needs to be updated!) https://docs.google.com/presentation/d/1itLeveA9vXmaN9hXVVELZ_i4oFklr8RZpSxE1E1Vhqc/edit

## 👀  Who should be in the loop about this issue?
@

**Comment by eduardovegap** [comment]
@Zeptimus presented and one.

**Comment by Zeptimus** [comment]
https://docs.google.com/presentation/d/1EFwNqx6ENlxgb12DnCFnpFKt7vNnkHFcSdO1PMuDXqM/edit#slide=id.g127ec27dc23_0_3  Close
