### ISSUE TITLE
Reward Distribution Catchup - July 2021 - June 2022

### ISSUE THREAD

**Issue by divine-comedian** [CommonsBuild/coordination#1351]
## 👇🏽  What is this issue about? Give as much detail as you can. 
Execute reward distributions weekly until we arrive at June 2022 via the Reward Board.

1. Post forum post w/ rewards distribtuion - 48hrs advice?
2. Create tx with Transactions app in Reward Board
3. get people to vote, pass vote, execute

We'll need to reasses how much funds we want to release after this point and we will likely need to draft a new request for funds to proceed after this point.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@kristoferlund @0xNuggan @liviade1 @Zeptimus 

## 🔗  Are there links or docs related to this issue?
https://forum.tecommons.org/t/rewards-budget-distribution/992

## 👀  Who should be in the loop about this issue?
@

**Comment by divine-comedian** [comment]
we are currently at January - Should be done in about 5 weeks!

**Comment by natenatesoo** [comment]
@divine-comedian I will place this issue into the Repeating  pipeline with tag until we have confirmation of June distribution.

Feel free to close this issue when completed.

Thanks!

**Comment by divine-comedian** [comment]
two more weeks and this should be done at the current pace.
