### ISSUE TITLE
Execute first payout w/ sourecred params

### ISSUE THREAD

**Issue by divine-comedian** [CommonsBuild/coordination#1353]
June 2022 will be the first quant payout utilising sourcecred params.

We'll need to add the sourecred params into our distribtuion files and ensure the calculations execute successfully.

This will involve coordination between source-cred, RAD dashboard and the tec-rewards repo.

**Comment by kristoferlund** [comment]
See also #1282

**Comment by tamarandom** [comment]
Closing old issues.
