### ISSUE TITLE
Retro action: Boost token holder and contributor confidence with outline of plans for what's next 

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#1365]
## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by tamarandom** [comment]
Leaving without a owner. @eduardovegap suggests a combined effort between Sampo and Communitas. 
CC @gideonro @liviade1

**Comment by eduardovegap** [comment]
The result of this was to send and share a Token Holder message. 

Forum post: https://forum.tecommons.org/t/june-2022-update-to-tec-token-holders/1058
Token Holder message: https://docs.google.com/document/d/1D0lwEXWm37COQGU5aE9UpMNkjO1m-xP12jVPoMUxLHs/edit#
