### ISSUE TITLE
Evolution of Stewardship and Stewards WG 

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#1366]
## 👇🏽  What is this issue about? Give as much detail as you can. 
What is the next phase of Stewards in the TEC? 

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by tamarandom** [comment]
This is the only thing I am taking into this Sprint.

**Comment by natenatesoo** [comment]
@tamarandom I assume this is an ongoing effort as Advice Process, and Feedback continues to come in.  I will add a repeating tag until we get more clarity on next steps.

Thanks!

**Comment by tamarandom** [comment]
The proposal is on the forum for community advice process. 
Next step will be to create a snapshot vote. 
https://forum.tecommons.org/t/the-steward-wg-transformation-proposal-for-community-advice-process/1118/2
