### ISSUE TITLE
Forum post to improve praise

### ISSUE THREAD

**Issue by divine-comedian** [CommonsBuild/coordination#1372]
## 👇🏽  What is this issue about? Give as much detail as you can. 
@Zeptimus and others mentioned dissatisfaction with the distribution of praise rewards and mentioned that there are many things currently not working with the way praise is being handled, perhaps inclding the quantification process.  Some more existential questions exist as well as in, what is the point of praise, what role do these rewards play in or commons?

The purpose of this issue is to create a forum post that invites a discussion to find solutions to this problem

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.Forum Post is up 
2. The community is sufficiently made aware of its existence
3. We begin receving feedback, advice and ideas

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@liviade1  @divine-comedian 

## 🔗  Are there links or docs related to this issue?
https://forum.tecommons.org/t/tec-rewards-distribution-september-2021/1017/4?u=divine_comedian

## 👀  Who should be in the loop about this issue?
@kristoferlund

**Comment by Zeptimus** [comment]
Done!
