### ISSUE TITLE
Crossreferencing information on the TEC sources. 

### ISSUE THREAD

**Issue by eduardovegap** [CommonsBuild/coordination#1381]
## 👇🏽  What is this issue about? Give as much detail as you can. 
As usages of common/shared information have evolved synchronization issues have been exposed. This task is to provide a simple inventory of the most frequent overlaps and where consistency is most critical. 

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. Urgent issues can be identified (much like the Discord pinned messages) and prioritized 
2. More data about current challenges is fed into the longer term conversation about synching and managing all of this content
3. This document can be used as a base for ongoing analysis and new work

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 🔗  Are there links or docs related to this issue?
https://docs.google.com/spreadsheets/d/1AeElM6Ff3kLKiicoWNjHDF6L0VYgeQMFvhd4mmP3ms4/edit#gid=0

## 👀  Who should be in the loop about this issue?
@

**Comment by jasontphelps** [comment]
I've made the re-organizations that came out of the 5/30 meeting and added both new sources and new categories of information. I've also noted where some of the urgent issues with dates/times have been corrected since this was first compiled

**Comment by eduardovegap** [comment]
This has been accomplished! Thanks @jasontphelps
