### ISSUE TITLE
Communitas spending spreadsheet 

### ISSUE THREAD

**Issue by eduardovegap** [CommonsBuild/coordination#1397]
## 👇🏽  What is this issue about? Give as much detail as you can. 

Transparency requested the filling of the spreadsheet that will be used for keeping track of spending on the Communitas WG. 

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 🔗  Are there links or docs related to this issue?
https://docs.google.com/spreadsheets/d/1SH-GRl2sDtOo4Ui7LmmB06a4_cEC7uIm5qpRDTgafp0/edit#gid=963243346

## 👀  Who should be in the loop about this issue?
@

**Comment by Zeptimus** [comment]
Done! praise Costa
