### ISSUE TITLE
Write the ABC advance page budget 

### ISSUE THREAD

**Issue by Zeptimus** [CommonsBuild/coordination#1402]
## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by eduardovegap** [comment]
We have a rough estimate on numbers, will type them and putting them on a document.

**Comment by Zeptimus** [comment]
Done and passed on cv already :D
