### ISSUE TITLE
Draft advisory board responsibilities, pilot the idea

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#1403]
## 👇🏽  What is this issue about? Give as much detail as you can. 
One of the clear outputs of the Stewards pol.is report is near consensus on the idea of an advisory board to support the Stewards. 
https://pol.is/report/r3wy7bkc3bmkxdar5stcn

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. Draft responsibilities & benefits of being on the board
2. Advice process with Stewards on whom to ask/recruit 
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by natenatesoo** [comment]
@tamarandom Not sure of the entire scope of this effort.  I know its a lot, but perhaps we can close it and create an epic to consolidate some of the issues!

I will bring this issue into the next sprint and allow for modification if need be.

Thanks!

**Comment by tamarandom** [comment]
This is part of the Steward Transformation proposal. 
https://forum.tecommons.org/t/the-steward-wg-transformation-proposal-for-community-advice-process/1118/2
