### ISSUE TITLE
Transparency Audit Part 1: Processes (Apr-Jun 2022)

### ISSUE THREAD

**Issue by iviangita** [CommonsBuild/coordination#1415]

**Comment by natenatesoo** [comment]
@iviangita Any updates?

I will add this to current sprint, please feel free to alter.

Thanks!

**Comment by Zeptimus** [comment]
https://www.figma.com/file/09F0cOEtObOsINqSInLokH/TEC-Transparency-Audit-Apr-Jun--%2722?node-id=21%3A1044
