### ISSUE TITLE
Transparency Audit Part 2: Voting Schema and Results (Apr-June 2022)

### ISSUE THREAD

**Issue by iviangita** [CommonsBuild/coordination#1416]
## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@Zeptimus 

## 👀  Who should be in the loop about this issue?
@

**Comment by natenatesoo** [comment]
@iviangita Any updates on this issue?  Very similar to previous issue. Do you want to develop an epic?

I will add this issue to current sprint, please feel free to alter.

Thanks!

**Comment by Zeptimus** [comment]
https://www.figma.com/file/09F0cOEtObOsINqSInLokH/TEC-Transparency-Audit-Apr-Jun--%2722?node-id=21%3A1044
