### ISSUE TITLE
Transparency Audit Part 4: TEC Analytics (Apr-Jun 2022)

### ISSUE THREAD

**Issue by iviangita** [CommonsBuild/coordination#1418]
## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by natenatesoo** [comment]
@iviangita :) Adding to current sprint!

**Comment by Zeptimus** [comment]
https://www.figma.com/file/09F0cOEtObOsINqSInLokH/TEC-Transparency-Audit-Apr-Jun--%2722?node-id=21%3A1044
