### ISSUE TITLE
Write mapping specs that match the ABC and CV Solidity Contracts

### ISSUE THREAD

**Issue by GriffGreen** [CommonsBuild/coordination#174]
## 📋   Anything to add?

Talking with Z, for picking the Parameters for the ABC and CV... we should really have some SIMPLE! (NOT AGENT BASED) Models that can show what the results of the different parameter choices are.

You have this solidity code... with these param options... what happens when people choose specific params

NEXT LEVEL! (not critical to hatch)

You have these desires: 

I want CV to take 60 days to reach 80% voting power

I want post hatch, i want it to take 1 million dai to double the price

What params do i need to make that happen

There are soooo many links i can add... for CV and ABC... will have to do later!

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by tamarandom** [comment]
Griff says done. Closing!
