### ISSUE TITLE
Proposal / Token Kitchen 

### ISSUE THREAD

**Issue by jessicazartler** [CommonsBuild/coordination#198]
Reviewers
@eduardovegap

**Comment by jessicazartler** [comment]
Working with Shermin V to submit a proposal - sending her directions and offering to set up a work sesh to do it first week in January
And will invite her to present at a TEC community call

**Comment by jessicazartler** [comment]
I have a call scheduled with Shermin for this Friday, due to personal reasons, she had to cancel her presentation this Thursday, will reschedule

**Comment by jessicazartler** [comment]
Shermin said she is working on a draft - have a check in with her next week

**Comment by eduardovegap** [comment]
@jessicazartler if Shermin propose, please update on TEC Curate: https://docs.google.com/spreadsheets/d/1RJK8gPqUoRfehX9e60sTCMAM_R1rI2CuiV1r-i3wAXQ/edit#gid=875503092

thanks!

**Comment by jessicazartler** [comment]
Sure, just dropped the proposal link in there - thanks Edu! <3
