### ISSUE TITLE
Hatcher Outreach

### ISSUE THREAD

**Issue by iviangita** [CommonsBuild/coordination#207]
This is the epic for Hatch Outreach

All Hatch Outreach is being tracked in the [TEC_Curate xls](https://docs.google.com/spreadsheets/d/1RJK8gPqUoRfehX9e60sTCMAM_R1rI2CuiV1r-i3wAXQ/edit#gid=0). Please update there.

The document of reference is: https://docs.google.com/document/d/1DBirw9I3VlwK5Ai6F-oAcY4fHPEAIC6gZ3m7yY_9PlM/edit

[Hatch FAQ
](https://docs.google.com/spreadsheets/d/1RJK8gPqUoRfehX9e60sTCMAM_R1rI2CuiV1r-i3wAXQ/edit#gid=0)

**Comment by eduardovegap** [comment]
I think we can close this issue. The hatch has been completed and the outreach is done.
