### ISSUE TITLE
Praise Case Study

### ISSUE THREAD

**Issue by GriffGreen** [CommonsBuild/coordination#211]

**Comment by tamarandom** [comment]
@ataberkcasur @liviade1 @GriffGreen , this is closed now, right? Now it's just a matter of formatting it into the pdf. Can we close this one this Sprint?

**Comment by ataberkcasur** [comment]
@tamarandom correct. We just need to grind on the visuals and that's it.

**Comment by tamarandom** [comment]
Hey @ataberkcasur Cool. And that's being tracked in
https://github.com/commons-stack/iteration0/issues/574#issuecomment-790922827
So I will close this on. 

GREAT WORK, Ata!

**Comment by GriffGreen** [comment]
More blasts from the past

**Comment by tamarandom** [comment]
heh, yeah. A trip down memory lane .....
