### ISSUE TITLE
Praise Quant / News Blog (Repeating every Sprint!)

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#220]
## 📋 Anything to add?

Every two weeks : praise post!!

## 🤼‍ Reviewer

@GriffGreen @tamarandom @jessicazartler 

## 🔗 Work doc - inspirational links

https://docs.google.com/document/d/1YsukZdnwmejmx8h_-qjq_NGr8i5vk46qEeH0eF2cCVo/edit

**Comment by jessicazartler** [comment]
https://medium.com/token-engineering-commons/the-tec-builds-momentum-gravitons-hatch-daos-indigenomics-and-dandelions-87c3e43d8ee0

Distributed in communities/Twitter also

**Comment by cranders1** [comment]
Thnx @jessicazartler 

My personal sprint 2 goal is to become more active in PM :)

**Comment by jessicazartler** [comment]
@tamarandom I am still confused.. are we using this same issue every time? or should we make a new one every time?

**Comment by tamarandom** [comment]
Hey @jessicazartler generally it makes sense to use the #repeating label for repeating tasks. They don't fall off the board that way. After they are closed, we resurrect them for the next Sprint.

 For example, after we close this one, before the Sprint Planning we will reopen it and bring it back into the Sprint. That's a lot less work that maintaining a list of repeating tasks and making new ones every sprint. So feel free to close these after they are done!!!

**Comment by jessicazartler** [comment]
Ahhhhh okay, thank you for clarifying, I feel like you have explained but it had been confusing me - got it now - THANK YOU! :D

**Comment by tamarandom** [comment]
Yay! 🙏🏼

**Comment by tamarandom** [comment]
Update : In draft & going through reviews now.

**Comment by cranders1** [comment]
Published, just not yet pushed through socials yet. Ivy forthcoming.
https://medium.com/token-engineering-commons/co-laborations-the-great-discord-migration-params-params-params-459c70bd686b

**Comment by tamarandom** [comment]
Nice!

**Comment by markoprljic** [comment]
@jessicazartler Can you paste the link to the doc here and @cranders1 can distribute it?
Thanks.

**Comment by jessicazartler** [comment]
Craig is writing and has link once he's finished

**Comment by cranders1** [comment]
https://medium.com/token-engineering-commons/the-tec-presents-dashboards-gitbooks-grants-festivals-d050b1fe640e

**Comment by tamarandom** [comment]
@cranders1 ! Awesome article & you can close this issue every sprint! (As long as it's tagged #repeating, we will bring it back into the next Sprint automatically)

**Comment by jessicazartler** [comment]
@cranders1 just checking - did you send to @iviangita to do the Tweet already - do you already do this every time? Thank you, looks awesome!!

**Comment by tamarandom** [comment]
@jessicazartler The blog post is already in the schedule for every other Friday. @cranders1 and I were chatting about whether we should move it to Wed (or Tues, if that's not too tight a schedule) though.

**Comment by tamarandom** [comment]
For Sprint 6, we will have @natenatesoo covering while @cranders1 enjoys a much deserved family vacation.

**Comment by tamarandom** [comment]
Published! Confetti, confetti! 
https://medium.com/token-engineering-commons/tec-mission-vision-and-values-introducing-1st-gen-gravitons-a4822eb6d769

**Comment by jessicazartler** [comment]
WHOA! SMASHING job @natenatesoo !!!!!! It is a masterpiece!!!

**Comment by tamarandom** [comment]
The hero @cranders1 is taking it on again this time! 🙏🏼

**Comment by cranders1** [comment]
Here's a draft. Hack away.
https://docs.google.com/document/d/1WobIOMjad_bcSdf9qn23QlWRP2xV1iGqZB09VikJtEs/edit?usp=sharing

Info requests for @GriffGreen @danelsuga
Own language or a link or a no go will work. 

Also opened a new, duplicate issue in C&D repo. Unsure if PQ blog desired to go through C&D process, so threw it in there just in case. Duplicate w/ [#39](https://app.zenhub.com/workspaces/tec-content-production-and-distribution-60549332d7d741001bbea827/issues/commonsbuild/content-distribution/39)

Also a draft in Medium w/ intact formatting etc
https://medium.com/p/4f7c9fb42d99/edit
https://app.zenhub.com/workspaces/tec-content-production-and-distribution-60549332d7d741001bbea827/issues/commonsbuild/content-distribution/39

**Comment by tamarandom** [comment]
@cranders1 @danelsuga Thanks! It makes sense to move this to the C&D repo, thanks for setting the issue up there! 

https://app.zenhub.com/workspaces/tec-content-production-and-distribution-60549332d7d741001bbea827/issues/commonsbuild/content-distribution/39

Closing this one.

**Comment by tamarandom** [comment]
Closing again. But this time removed the #repeating label so it will stay closed. ;)
