### ISSUE TITLE
TEC Sprint Facilitation  

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#221]
## 📋 Anything to add?

Sprint Planning
Sprint Retrospective
Sprint Review

& team support all along the way  🦋  🐝  

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by tamarandom** [comment]
Thinking about how to make this better. I feel like I have not touted strong enough the actions we bring into every sprint. Somehow encouraging those actions along the two weeks we have them. I plan to do that better next Sprint. Hold me to it, folks.

**Comment by tamarandom** [comment]
![slay.jpeg](https://images.zenhubusercontent.com/5faaa1d038c6409364f7830c/a7d32291-afdf-4b7d-a491-19b73f5f6cc5)

**Comment by tamarandom** [comment]
Hey @mount-manu, passing this one over to you!

**Comment by mount-manu** [comment]
Yes ma'am, [I want it that way](https://www.youtube.com/watch?v=4fndeDfaWCg)

**Comment by tamarandom** [comment]
@eduardovegap volunteered to take this on for the next Sprint!

**Comment by tamarandom** [comment]
You've been doing a bang-up job, @eduardovegap! You mind if I take my name off this one now!? Or did you want to just take the wheel for one Sprint? 😆

**Comment by eduardovegap** [comment]
We are going to start rotating this. Proposal will come up soon.

**Comment by eduardovegap** [comment]
@natenatesoo supported on the sprint retrospective since i was at the conference.
Sprint planning was also accomplished this sprint

**Comment by natenatesoo** [comment]
@tamarandom I think this is something that will happen as you say, naturally! :)

I'm going to close it just for the sake of organization!  If you want it to stay open, please feel free to alter.
