### ISSUE TITLE
All the Terms & Conditions 

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#228]
## 📋 Anything to add?

Want: comprehensive list of what the T&C touch points are. 
This is in a [miro board](https://miro.com/app/board/o9J_kkC0kIM=/) <-- Look for Agreements Box 

T&C required :
See the issues in this epic. 

Review by required:
SoftGov
Gravity
Legal 

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by natenatesoo** [comment]
Great Job!
