### ISSUE TITLE
Legal / T&C TEC Convert/ABC

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#245]

**Comment by Santigs** [comment]
Here's the draft doc we will start with
https://docs.google.com/document/d/1hhUISETCrlPiW0PQGO35ksOFfQyM6CVVUesGdw6SPBA/edit?usp=sharing

**Comment by tamarandom** [comment]
Thank you @Santigs!  I just requested access to the file.

**Comment by Santigs** [comment]
I gave you access and changed the link.
Hopefully everyone will have comment access now

**Comment by tamarandom** [comment]
There is a new one. Here is the link that you should use: https://docs.google.com/document/d/1YmbGQhGspIlxhFzmzc1saWG0wzPLwz42lOF2E5NDXXk/edit

**Comment by tamarandom** [comment]
Update from Santi: Document finished just waiting for bonding curve parameters and shape to be voted by the community to implement those variables into the document and final touches Shawn will introduce after today's meeting

**Comment by iviangita** [comment]
Griff and I have added the chosen parameters to the ABC Terms - it's ready! Next step would be to upload it to IPFS (Zep will coordinate with Sem) 

https://docs.google.com/document/d/1YmbGQhGspIlxhFzmzc1saWG0wzPLwz42lOF2E5NDXXk/edit

**Comment by iviangita** [comment]
Closing! Uploaded on IPFS https://gateway.pinata.cloud/ipfs/QmSYHg3Vthf8JGxHbDauWohy7aRKn3X2esHTWofVv4ei1A
