### ISSUE TITLE
Legal / T&C TEC CV Proposals

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#246]

**Comment by iviangita** [comment]
WIP -  https://docs.google.com/document/d/1BltyTWMCkyJZktdEZu7o7hM1vI8v_JJmqhX74LNGNFM/edit?usp=sharing

**Comment by tamarandom** [comment]
Update: there is no way to do this in Gardens atm. This is something that has to be addressed w/Gardens before we can complete. cc @divine-comedian @GriffGreen @laurenluz 

Follow the request to Gardens here: https://github.com/1Hive/gardens/issues/500

**Comment by iviangita** [comment]
The content is ready, here's the [link ](https://docs.google.com/document/d/1BltyTWMCkyJZktdEZu7o7hM1vI8v_JJmqhX74LNGNFM/edit?usp=sharing)to the final version.

Already added it to Gitbook as well, waiting for @liviade1 to approve my submission. Once it's published, we will integrate the link into the Covenant.

**Comment by laurenluz** [comment]
This is amazing Ivy!! Thank you!

**Comment by GriffGreen** [comment]
YAY! Great work Ivy!

And now this works for Gardens so no technical blockers for doing this. Praise Mitch!

Amazing that you saw this @laurenluz Giveth is everything cause of you ❤️

**Comment by iviangita** [comment]
Closing! This is now on [Gitbook ](https://token-engineering-commons.gitbook.io/tec-handbook/voting-templates-and-the-bonding-curve/terms-and-conditions-for-submitting-and-challenging-proposals)
