### ISSUE TITLE
Gravity / T&C CV Proposals

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#255]

**Comment by JuankBell** [comment]
https://forum.tecommons.org/t/monitoring-proposals/154 <- Discussion initiated here

& also we have been discussing about this on the soft gov agenda & notes :D
https://docs.google.com/document/d/1R8yLfht6GvGHr8VDvyZ-sVP1s54rPLY4MtXPBOqHtO0/edit#

To consolidate in the TEC Handbook 
https://token-engineering-commons.gitbook.io/tec-handbook/

**Comment by JuankBell** [comment]
Ok from Gravity! :)
