### ISSUE TITLE
Reward system holistic overview 

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#272]
## 📋 Anything to add?

High level look at Praise system overall.

## 🎉 Subtasks

integrate praise with sourcecred 

## 🤼‍ Reviewer

@

**Comment by liviade1** [comment]
- how to reward source cred 
- how to integrate source cred with praise

**Comment by liviade1** [comment]
@Santigs do you think we need the source cred proposal to be approved for us to move forward with a plan for contribution reward after the hatch?

**Comment by Santigs** [comment]
Yes, I'd like to share all the parameters as they are now, and vote them. There are lots of things which could be changed and that affect the outcome, last thing I want is someone not liking the outcome and not have gone through voting.
