### ISSUE TITLE
TEC HatchDAO Params Decision Making Process

### ISSUE THREAD

**Issue by GriffGreen** [CommonsBuild/coordination#276]
## 📋 Anything to add?

Check out https://docs.google.com/document/d/1q2lzJxoVNPBxX7MIqBHsbXJgA7Dgs3cK71VCajRj91w/edit

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

## 🔗 Work doc - inspirational links
https://docs.google.com/document/d/1q2lzJxoVNPBxX7MIqBHsbXJgA7Dgs3cK71VCajRj91w/edit

**Comment by tamarandom** [comment]
Backlog refinement. Closing this Epic for the Hatch Params.
