### ISSUE TITLE
Encourage people to create their own parameter proposals for the TEC HatchDAO

### ISSUE THREAD

**Issue by GriffGreen** [CommonsBuild/coordination#284]

**Comment by freedumbs00** [comment]
@GriffGreen   I don't think this is the direction we are heading.  Encouraging to vote is more appropriate.

**Comment by tamarandom** [comment]
@GriffGreen I don't know if you could have been any more successful on this. These Param parties and debates were key. It was especially great that Niran from Panvala joined yesterday and said "history is being made" and that Ronald from positiveblockchain also shared his high regard for this approach after having attended a session this week.
