### ISSUE TITLE
Encourage people to vote with Tokenlog on TEC HatchDAO

### ISSUE THREAD

**Issue by GriffGreen** [CommonsBuild/coordination#285]

**Comment by tamarandom** [comment]
Update : for after the proposals are sumbitted.

**Comment by tamarandom** [comment]
I used all my voting power!!! Need more voting power!! 😂

**Comment by tamarandom** [comment]
![photo_2021-05-13_23-04-45.jpg](https://images.zenhubusercontent.com/5faaa1d038c6409364f7830c/729b986a-2123-4c38-bb09-e5109a82bb52)
