### ISSUE TITLE
Proposal / Commons Swarm

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#333]

**Comment by tamarandom** [comment]
Hey @GriffGreen ! Are you the person to own this? @eduardovegap and I are using the same assignments as were on the tec_curate xls here.

**Comment by GriffGreen** [comment]
oh yeah!

I am down to make a Commons Swarm proposal.

**Comment by tamarandom** [comment]
Closing these Proposal Squad issues as the strategy and workload is evolving. We can open new issues when needed.
