### ISSUE TITLE
Proposal / Near Protocol

### ISSUE THREAD

**Issue by eduardovegap** [CommonsBuild/coordination#340]

**Comment by tamarandom** [comment]
Hey @knobsdao  ! Are you the person to own this? @eduardovegap and I are using the same assignments as were on the tec_curate xls but things may have shifted.

**Comment by knobsdao** [comment]
Hey @tamarandom. Yes, I'm in contact with them thanks Jess. We disconnected a bit, but I can circle back and take this forward.

**Comment by tamarandom** [comment]
@knobsdao Awesome! Thank you!

**Comment by eduardovegap** [comment]
Updated the status on TEC Curated. If this gets follow up or submitted, please update here: https://docs.google.com/spreadsheets/d/1RJK8gPqUoRfehX9e60sTCMAM_R1rI2CuiV1r-i3wAXQ/edit#gid=875503092
