### ISSUE TITLE
TBC Proposal / MetaGov

### ISSUE THREAD

**Issue by eduardovegap** [CommonsBuild/coordination#352]

**Comment by tamarandom** [comment]
Hey @liviade1 ! Adding you as assigned so it stays on your radar. Drop updates here as they come.

**Comment by tamarandom** [comment]
Proposals outreach is being tracked in this xls. https://docs.google.com/spreadsheets/d/1RJK8gPqUoRfehX9e60sTCMAM_R1rI2CuiV1r-i3wAXQ/edit#gid=1523587366

I just moved this to that sheet and closing it here.
