### ISSUE TITLE
TBC Proposal / PrimeDAO.

### ISSUE THREAD

**Issue by eduardovegap** [CommonsBuild/coordination#354]

**Comment by tamarandom** [comment]
@Zion-code I'd like to assign this to you but you're not in our repo! Doh! I just added you.

**Comment by tamarandom** [comment]
Until @Zion-code is in the TEC repo, I'm syncing with him on Telegram and assigning this to myself so it stays on my radar.

**Comment by tamarandom** [comment]
Proposals outreach is being tracked in this xls. https://docs.google.com/spreadsheets/d/1RJK8gPqUoRfehX9e60sTCMAM_R1rI2CuiV1r-i3wAXQ/edit#gid=1523587366

I just moved this to that sheet and closing it here.
