### ISSUE TITLE
Griff / Get 5 new Soft Commits from big CSTK Holders

### ISSUE THREAD

**Issue by GriffGreen** [CommonsBuild/coordination#374]
## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by GriffGreen** [comment]
80% Got Soft commits from 
Lorelei
David HQ
Zargham
Eden

Wasnt able to get commits from Owocki or Cassady... but will follow up

**Comment by GriffGreen** [comment]
Got one from Gus!

**Comment by tamarandom** [comment]
Update: closing!
