### ISSUE TITLE
Create Story board for Onboarding video (Hatch App)

### ISSUE THREAD

**Issue by jessicazartler** [CommonsBuild/coordination#377]
## 📋 Anything to add?

We have the concept, now we need Marko/Sem/Jess to meet to map out storyboard

## 🎉 Subtasks

- [ ] Set up meeting & draft
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@markoprljic @tamarandom @sembrestels

**Comment by jessicazartler** [comment]
Meeting scheduled for Friday with Sem / Marko

**Comment by markoprljic** [comment]
Jess is working on storyboard/formulating questions.

**Comment by markoprljic** [comment]
Someone made this https://eth10k.surge.sh/ and that made me think we could cut out interview audio in a similar fashion and have bg images, short clips accompany the narrative. 

@jessicazartler @sembrestels @freedumbs00

**Comment by freedumbs00** [comment]
I think thats awesome

**Comment by jessicazartler** [comment]
Yeah of course, we can add a music track, audio effects and I can add images/graphics/subtitles over stuff

**Comment by markoprljic** [comment]
@jessicazartler Any progress or update on this?

**Comment by tamarandom** [comment]
Hello @mount-manu ! Will you please drop an update in here. We're going to do our Sprint Planning tonight and it will be helpful to have a status. 🙏🏼

**Comment by mount-manu** [comment]
It'll be ready this sprint.

**Comment by markoprljic** [comment]
This issue can be closed because it relates to the WHY video Manu is working on and examples have been provided and clarity has been provided from Manu on our weekly call. 

Storyline:

1. Introductions
2. Problems
3. Solutions
4. Community 

Short version and long version to be created.
