### ISSUE TITLE
Review and gather info for an to update : Onboarding resources and guide 

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#381]
## 📋 Anything to add?

Update the onboarding resources and guide doc. AND add this to Gitbook. ;)
https://docs.google.com/document/d/1UDnf26QQqqc77mnhn80MLCVzJU6IdvouT-OXPrIVXCg/edit#heading=h.tpx9g4b760ky

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@liviade1

**Comment by tamarandom** [comment]
Hey @liviade1 - it looks like beyond updating this, is should be moved to gitbook, right?

**Comment by liviade1** [comment]
@danelsuga can we take a look at this together?

**Comment by danelsuga** [comment]
That would be great. Thx @liviade1

**Comment by liviade1** [comment]
https://app.gitbook.com/@token-engineering-commons/s/tec-handbook/
