### ISSUE TITLE
New Discord / Implement SourceCred

### ISSUE THREAD

**Issue by markoprljic** [CommonsBuild/coordination#390]
## 📋 Anything to add?

SOURCE CRED EXPLORER https://tecommons.github.io/tec-sourcecred/#/explorer
Get someone from 1Hive to help with this.

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@markoprljic

**Comment by metaverde** [comment]
We won't be implementing SourceCred on the Discord server at this time.
And the Discord server is up.

**Comment by tamarandom** [comment]
Update : too early! We are reviewing and testing. Then a decision will be made about whether or not to use it. Closing!
