### ISSUE TITLE
How to Become a Hatcher forum post/blog

### ISSUE THREAD

**Issue by jessicazartler** [CommonsBuild/coordination#418]
## 📋 Anything to add?

Drafting a piece for How to Become a Hatcher

-Rehashing legal rec & proposal/vote
-FAQ from onboarding group
-Point to CSTK dapp article when finished

## ⏰ Urgency/Due Date/Blockers?

Dependency is the CTSK token dapp being done

## 🎉 Subtasks

- [x] Write draft
- [ ] Get feedback from Griff/Craig/Eduardo
- [ ] Post & distribute 

## 🤼‍ Reviewer

@GriffGreen @eduardovegap

**Comment by GriffGreen** [comment]
https://docs.google.com/document/d/1jJAlLi6zE4lktvnzyloscNyyDc9UHPy6BuhI7yT-Qv0/edit

Reviewed and improved

**Comment by jessicazartler** [comment]
Awesome thank you! Let me know when it's ready for me to go in

**Comment by jessicazartler** [comment]
@tamarandom is it this doc for FAQs?
https://docs.google.com/document/d/1JWZ2ZXlh4oyIvUWgN9Dg8CdSuExh0Mn_Fq1adJ9W1Pw/edit#

Lemme know when you get there and I'll include it in the content - thanks for the idea!!

**Comment by tamarandom** [comment]
Hey @jessicazartler ! That is the one for Proposal!! This is the one for Hatchers which you can see is just starting : 
https://docs.google.com/document/d/16FYhIodALP2tDldtuxuDbg-3Q4E7llgSatdlhHO6Sos/edit#heading=h.8mwcgxmyttz8

**Comment by jessicazartler** [comment]
Thank you! I will be working on this next week when Kris' CS blog about dapp is done - thanks!

**Comment by GriffGreen** [comment]
I don't think the Swiss Membership DApp will change... while we are still working on the final little bugs... i think its good enough to have screen shots... still needs some work before the video tho :-/

**Comment by markoprljic** [comment]
Updated FAQ doc https://docs.google.com/document/d/16UI-EfD4qcwBaAv3Eexlv01SOK7oiDt4gkVT5rEY6X4/edit#heading=h.t62y5prlm779

Hatch TL;DR for potential hatchers https://docs.google.com/document/d/1Ji2vV5c_PCXt2q0G-1wTddyOaUp5ESKWht2UKcoE7S0/edit

**Comment by markoprljic** [comment]
Hatcher Campaign Content https://docs.google.com/document/d/1uwklhfJyGKoiVSC3yQTRL4y-Az_QaLOx3nWGctVeDCg/edit

**Comment by tamarandom** [comment]
Update : Eduardo's latest : https://docs.google.com/document/d/1tsEPNb-gLEh9FKOGLBPt0prfWrOwjmnnjtPdCpy8lxo/edit

**Comment by tamarandom** [comment]
Update : Issue #419 tracking review and distribution. Closing this now.

**Comment by eduardovegap** [comment]
This is issue can be closed, @GriffGreen finish this article and post it: https://forum.tecommons.org/t/how-you-can-hatch-the-tec/328

Thank you Griff <3
