### ISSUE TITLE
Update Welcome to TEC Forum Section with How to Become a Hatcher info

### ISSUE THREAD

**Issue by jessicazartler** [CommonsBuild/coordination#419]
## ⏰ Urgency/Due Date/Blockers?

Dependent on #418

**Comment by eduardovegap** [comment]
https://docs.google.com/document/d/1tsEPNb-gLEh9FKOGLBPt0prfWrOwjmnnjtPdCpy8lxo/edit 

Currently work in progress document for this piece.

**Comment by tamarandom** [comment]
Update : @griff doing final edit before passing.

**Comment by markoprljic** [comment]
@GriffGreen Just for the heads up :)
