### ISSUE TITLE
Deploy the Commons Upgrade vote and Demo it.

### ISSUE THREAD

**Issue by GriffGreen** [CommonsBuild/coordination#423]
## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by tamarandom** [comment]
Update : the vote passed. Will be closed on Sunday!

**Comment by tamarandom** [comment]
@GriffGreen before closing this I just want to check the result. Is there any reason to leave this open?
