### ISSUE TITLE
SEO

### ISSUE THREAD

**Issue by markoprljic** [CommonsBuild/coordination#429]
## 📋 Anything to add?

Establish SEO keywords and best practices.

## ❓ Why is it important?

Reach!

## 🤼‍ Reviewer

@eduardovegap @rosamoc @jessicazartler

**Comment by tamarandom** [comment]
Woot! All the issues in this Epic are closed.  🤙🏽  🏄🏽 

Closing this one now as we are kicking off a new SEO initiative and it's covered in a new Epic,  #636 

https://app.zenhub.com/workspaces/tec-coordination-workspace-5fad0d3fbbe4da0011c2f40d/issues/commonsbuild/coordination/636
