### ISSUE TITLE
Disputable Voting Params Blogposts Epic

### ISSUE THREAD

**Issue by GriffGreen** [CommonsBuild/coordination#468]

**Comment by divine-comedian** [comment]
This is the current working doc for the undisputed disputable blogposts - https://docs.google.com/document/d/1__kysKxgqtArILNc-1bJ6i8Oxq_ogrq7NEg1ZGS8hx8/edit?usp=sharing 

agreement parameters are still in the works
Please add content, review and suggest edits!

@GriffGreen
