### ISSUE TITLE
TEC Swag shop & TECLOVE token for Hatchers

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#481]
## 📋 Anything to add?

Someone else's idea but as it came up, we can follow the pattern we are using for Commons Stack.
In brief, this: 

swag.<url> = on rinkeby network only accepts SWAGTEC tokens

Token that is airdropped to Hatchers.
They can use that token to acquire swag at the swag shop.

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by tamarandom** [comment]
Our main dev on this has been highly focused on a project he's getting off the ground and the gitcoin grant process. We should be able to finish this in the next Sprint though.

**Comment by chuygarcia92** [comment]
hatch swag is up so maybe this epic can be closed?

**Comment by tamarandom** [comment]
@chuygarcia92 Yes we can! Closing.  🥳
