### ISSUE TITLE
Discord : Roles and Perms 

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#484]
## 📋 Anything to add?

Note: Pulling this out of #319 to be addressed  as a separate issue. 

I am thinking that the TEC Team should include *at least* all of the TEC Stewards (I will create a separate issue for @Vyvy-vi to do that now) but the think work around whom else and what perms is still an open question as far as I know. 

---
Hey @JuankBell !

@vyvy-vi would like to know whom to set as the moderators and role permissions for TEC Team on our new Discord :

Moreover, on which classification should the following roles be assigned:

Moderators(I suppose ppl will volunteer) ( moderators might have ban, mute, kick permissions on the server and maybe on the bots )

TEC Team (I am not sure regarding the role and what power levels should this role be assigned- Should this include message pin perms and message deletion perms along with moderation permissions?)

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by Vyvy-vi** [comment]
#485 Added stewards to TEC Team role.
The powers included with that role:
PIN permissions in channels
DELETE messages
*Note- these permissions are grouped together by discord 😅

**Comment by Vyvy-vi** [comment]
The current list of moderators: 
![Uploading Screenshot 2021-03-02 at 1.42.35 PM.png…]()

**Comment by tamarandom** [comment]
hey @liviade1 @JuankBell does it make sense for Soft Gov to take on the Roles and Permission as they are related to Ostrom's principle on boundaries?

**Comment by tamarandom** [comment]
Hey @JuankBell - Confirmed with @liviade1 that this can be taken on by Soft Gov.

**Comment by JuankBell** [comment]
Yes! until now the initial criteria I have been thinking to apply to distribute roles is this:

- To receive praise: people must check the rules and have the role of verified CC
- To give praise, admins must give the role of praise giver.
- Make all Stewards TEC Team, 
- Community moderators are people with activities related to the Discord/forum/Working groups maintenance.
- Admins: Griff (project lead), Livi (soft gov), Zeptimus (transparency), Juan (gravity), Vyvy (helping with the bots), Jessica (comms)

All members with Verified CC can post in café
Only TEC team members can see/ post in the stewards channel

**Comment by Vyvy-vi** [comment]
> Only TEC team members can see/ post in the stewards text channel and the stewards vc

I have put the role restrictions for this, now only TEC Team and Admins can see the Stewards channel :+1:

**Comment by tamarandom** [comment]
Hi @Vyvy-vi ! The Stewards channel should be open to all to see/post as it's one of the Working Groups and practicing transparency along with others.

@JuankBell The conversation around a separate communication channel for Stewards' communications of a more private nature would be separate from the public WG channel.

**Comment by Vyvy-vi** [comment]
@tamarandom The restrictions have been removed :+1:

**Comment by liviade1** [comment]
Hi @Vyvy-vi is it possible to have a role that lasts a certain period of time? Like a month? 
So new members could be assigned with a "incubator" role?
I created this incubator chat under onboarding to help with new members

**Comment by liviade1** [comment]
My thought is that we don't need a TEC Team role, but just incubator, stewards, contributors, subject matter experts and praise givers. 
I'm happy to chat about this too!

**Comment by Vyvy-vi** [comment]
We could have such a role.
By certain period of time, is it that after a month or something, the role gets removed from the people, who were assigned it OR does it rely on the role being deleted altogether from the server?

I think both of the above can be set up. (However, I am not sure if any of the existing bots handle that. If needed, we could set up a new one)

**Comment by liviade1** [comment]
Ah, that's not a big, only if it was easy :) 
It would still be nice to have the incubator role tho so stewards can know who are the new people that might need help with onboarding.

**Comment by liviade1** [comment]
**New Member**
- automatically assigned when someone joins the server
**Community Stewards**
 - Can give praise powers
 - delete messages from users 
- mute mics 
**Contributors** 
**Subject Matter Experts**
**Gravitons**
- delete messages 
- ban users
- mute mics 
**Praise Givers** 
**Admin** 
- ban users 
- create, delete and modify channels 
- can give praise powers

**Comment by Vyvy-vi** [comment]
There is a special consideration needed for the new bot(the one that can ban multiple users) and the power permissions to be given to the bot, as well as the people who could use the bot.
@JuankBell @liviade1 Their is a new issue regarding some of the security discussions needed for the bot - #562

**Comment by Vyvy-vi** [comment]
The roles have been set up-!
The `New Member` role is auto-assigned to everyone on joining(it can be removed by `stewards`, `gravitons`, `Admins`)
Moreover, 3 more roles have been made-
`Can Edit Server` - This is for cases when Stewards or a Working Group needs to make a new channel or tweak the server a bit. (Can be assigned by `Admins`)
`Can Ban` - This allows use of the multi-ban bot(`TEC Automation`). Currently, this role is given to Juan, me. (We might need to discuss, to whom should this role be assigned)
`Can view logs` - This allows to view the audit logs, and the bot setup and logging channels(should this be an opt-in open for all role, or should this be given to specific WGs like Transparency, soft-gov, gravity and to stewards???)

**Comment by Vyvy-vi** [comment]
> @Vyvy-vi Ah, that's not a big, only if it was easy :)
It would still be nice to have the incubator role tho so stewards can know who are the new people that might need help with onboarding.

@liviade1, In what time-frame, should the `New Member` ('incubator') role be removed by the bot?
I think a few weeks should be good or maybe more

**Comment by tamarandom** [comment]
Hey @Vyvy-vi you never cease to amaze! 

My input would be that we keep it simple. 

Let's say 5 weeks knowing 1) we can always change if need be and 2) we can add/remove the role manually for edge cases.

**Comment by liviade1** [comment]
Hey @Vyvy-vi amazing work with the roles 😍 thanks so much
Is it possible for us to have a "time spent in the server" as a parameter?
If so, it would be nice to have like 40 hours
Otherwise 5 weeks should be fine.

**Comment by Vyvy-vi** [comment]
40 hours can be set up :+1:

**Comment by liviade1** [comment]
perfect! thanks!!

**Comment by Vyvy-vi** [comment]
I think this can be closed
(Besides the role automation, all the roles have been created)
I think Admins and Stewards can assign the respective `Gravitons` and `Subject Matter Experts` and `Contributors` roles

**Comment by tamarandom** [comment]
Thanks @Vyvy-vi! The role automation part refers to the "new member' role being assigned for 40 hours on Discord or something else?

**Comment by Vyvy-vi** [comment]
Yes, I am working on that.
I think I'll get enough time next week(or around 18th to move forward with other bot functionality)

**Comment by Vyvy-vi** [comment]
I think this can be closed :)
