### ISSUE TITLE
SEO - Adapt contents (social media, blog...) to SEO Keyword list

### ISSUE THREAD

**Issue by markoprljic** [CommonsBuild/coordination#491]
## 📋 Anything to add?

Increase SEO on existing publications. 

## 🎉 Subtasks

- [ ] Check the [SEO Keywords list ](https://github.com/TECommons/coordination/issues/490)
- [ ] Go through all existing content on Medium and Social media profiles and update where possible based on the defined SEO Keywords

## 🤼‍ Reviewer

@markoprljic @rosamoc 

## 🔗 Work doc - inspirational links

SEO Keywords Issue https://github.com/TECommons/coordination/issues/490

**Comment by jessicazartler** [comment]
I would prefer to ask a contributor to do this as my plate is full and now PMing Gitcoin Grants Round 9 for CS ecosystem

Perhaps Nate has bandwidth? Also onboarding/sending you a new contributor for Comms - Thank you!

**Comment by markoprljic** [comment]
Thanks @jessicazartler .

@natenatesoo would you be up for this?

**Comment by natenatesoo** [comment]
Yeah, I can help with this! I am almost done with the FAQ gitbook page, and once its done, I will work on the SEO for content.  Do I have access to all relevant information?

**Comment by markoprljic** [comment]
Thanks @natenatesoo :)

Right now we have the SEO keywords (waiting for the list to be uploaded to the corresponding issue). Once that is up you could start working on it. The task would be to go through all existing content on Medium and Social media profiles and update where possible / needed based on the defined SEO Keywords. 

I'll tag this for the next sprint and we can discuss it further. Thanks again!

**Comment by rosamoc** [comment]
@markoprljic @natenatesoo I have to make a document with the SEO recommendations to do in each social network and on the website. I am also elaborating the list of keywords. To do the SEO you have enough with the list or you also need the document with the recommendations?

**Comment by markoprljic** [comment]
Recommendations would be extremely useful, yes.

**Comment by rosamoc** [comment]
OK

**Comment by natenatesoo** [comment]
So, it is my understanding that a Keywords List has already been made.  This is just to evaluate and update the Keywords List and apply them to our Blog Posts/Social Media Channels. If this is correct, can we append this issue with the Keyword List/Intent document?  Also, Do we have any Search Analytics tools available?

**Comment by markoprljic** [comment]
> So, it is my understanding that a Keywords List has already been made. This is just to evaluate and update the Keywords List and apply them to our Blog Posts/Social Media Channels. If this is correct, can we append this issue with the Keyword List/Intent document? Also, Do we have any Search Analytics tools available?

That is correct @natenatesoo Once @rosamoc finishes the final editing of SEO Keywords and recommendations doc she will provide it to you and update the [linked issue ](https://github.com/TECommons/coordination/issues/490)in the description of this one. 

The analytics tool is being set up by @rosamoc as well. We use Google Analytics. If you want to be added to the GA account please send @Zeptimus your email address.

**Comment by Zeptimus** [comment]
@rosamoc She should have full access by now if there's anything else i can help let me know :)

**Comment by rosamoc** [comment]
@Zeptimus I have access as an editor, yes  but I can not see the "GA Tracking ID", please could you send me this information? For now I only need this. Thank you!

**Comment by markoprljic** [comment]
@natenatesoo There has been an update for this issue. Rosa has submitted the[ SEO keywords list](https://github.com/TECommons/coordination/issues/490#issuecomment-795400021), you can take it from here. Let me know when you start working on this.

Thanks.

**Comment by tamarandom** [comment]
Hey @natenatesoo @markoprljic Will you drop an update in this issue so it's clear to all where we are and what are the next steps? 🌸

**Comment by tamarandom** [comment]
Hey @rosamoc ! Thanks for this list! I copies the xls into a google sheets so it's more easily accessible for everyone! 

Here it is : https://docs.google.com/spreadsheets/d/1P9DQkB-tvyGIaVaNR4Bdfkg3mhwDwDmMm66WwF3dcBw/edit#gid=0

This effort will be pulled into a SEO project we are initiating to take a holistic look at SEO - determine what our end goal is and then plan the pieces of work necessary to get there. 

This will be covered in the Epic #636 
https://app.zenhub.com/workspaces/tec-coordination-workspace-5fad0d3fbbe4da0011c2f40d/issues/commonsbuild/coordination/636

Closing & THANK YOU SO MUCH for this work!!

**Comment by tamarandom** [comment]
Hey @rosamoc ! Thanks for this list! I copies the xls into a google sheets so it's more easily accessible for everyone! 

Here it is : https://docs.google.com/spreadsheets/d/1P9DQkB-tvyGIaVaNR4Bdfkg3mhwDwDmMm66WwF3dcBw/edit#gid=0

This effort will be pulled into a SEO project we are initiating to take a holistic look at SEO - determine what our end goal is and then plan the pieces of work necessary to get there. 

This will be covered in the Epic #636 
https://app.zenhub.com/workspaces/tec-coordination-workspace-5fad0d3fbbe4da0011c2f40d/issues/commonsbuild/coordination/636

Closing & THANK YOU SO MUCH for this work!!
