### ISSUE TITLE
Jake / Hatch Outreach (see Epic for details)

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#495]

**Comment by freedumbs00** [comment]
Where is this epic?

**Comment by tamarandom** [comment]
https://app.zenhub.com/workspaces/tec-coordination-workspace-5fad0d3fbbe4da0011c2f40d/issues/tecommons/coordination/207

Though it bears mentioning that Epics are a Zenhub feature. So you will not see it directly on github.com. 🙏🏼
