### ISSUE TITLE
Make an open list of TEngineers and TE projects to pass around

### ISSUE THREAD

**Issue by markoprljic** [CommonsBuild/coordination#497]
## 📋 Anything to add?

Make a list of TEngineers and TE projects. Find people and projects all over the internet, telegram, discord, social media.
Where to find people and projects:

- The cadCad group (@cadCAD_org for telegram)
- TE academy group 
- The commonstack telegram 
- BlockScience

## ⏰ Urgency/Due Date/Blockers?

The sooner the better.

## ❓ Why is it important?

We need this to reach out and onboard more TEngineers to TEC.

## 🎉 Subtasks

- [x] Create a Google Sheet for People and Projects
- [ ] Submit in Comms Discord channel
- [ ] Close issue

## 🤼‍ Reviewer

@markoprljic @freedumbs00

**Comment by mount-manu** [comment]
I claim this @markoprljic, would you please assign it to me?

**Comment by markoprljic** [comment]
Thanks @mount-manu this is great!

@freedumbs00 @liviade1 Tagging you here for assistance and instructions on how Manu should proceed with this, what is the deliverable of this issue and what are the next steps after completion? Please let us know and I'll update the issue description.

Thanks!

**Comment by freedumbs00** [comment]
The TEC Lab calls on Fridays are full of the right people.  The cadCad group and TE academy.  @cadCAD_org for telegram.  The commonstack telegram has quite a few.  Anyone with BlockScience

**Comment by eduardovegap** [comment]
@mount-manu check https://docs.google.com/spreadsheets/d/1RJK8gPqUoRfehX9e60sTCMAM_R1rI2CuiV1r-i3wAXQ/edit#gid=0 this is our curated original list that we are using for onboarding hatchers, in case you wanna use it as reference.

**Comment by mount-manu** [comment]
Awesome! Will incorporate it into the one I've been working on, thanks for the heads up

**Comment by mount-manu** [comment]
Here it is:
https://docs.google.com/spreadsheets/d/1e57AY4x-UHAeJblp1rykqS1JQEITjJhQlzY1vFJEFzo/edit?usp=sharing

(Needless to say, this is a reiterative task which I assume responsibility for and as such I'll keep adding, refining, and updating it every 3 days. I'm posting the link now so that other people can access it and progress is established).

**Comment by tamarandom** [comment]
Update : Can these two xls tracking proposals / projects be merged into one?

**Comment by markoprljic** [comment]
@mount-manu Can you please see if we can merge the two sheets that Tam asked above? Also, I would like to finalize this task and close it, please let me know when this can be done. Thanks!

**Comment by mount-manu** [comment]
Yes, I'll merge the two sheets into one, I just didn't know how to do it on the google docs spreadsheet. I'll figure it out, update it, and keep adding more TEs as well as TE projects. This will be ready to be closed by late next week, before the end of the sprint.

**Comment by tamarandom** [comment]
Hey @mount-manu !

I copied your two sheets into the Curate doc so they are handy to the Hatch outreach and Project Swat team to see and incorporate into our planning. So they're now merged here:
https://docs.google.com/spreadsheets/d/1RJK8gPqUoRfehX9e60sTCMAM_R1rI2CuiV1r-i3wAXQ/edit#gid=1251782427

Feel free to keep updating them there as needed. I think we can close this issue, right? Unless there is any thing else to consider before we do.

**Comment by mount-manu** [comment]
Yes, we can close it, I'll be diligent in it being kept updated!

**Comment by tamarandom** [comment]
🤙🏽

**Comment by tamarandom** [comment]
Hey @Ekeneodigwe! This is the contact list that the TEC has built a number of months ago. Please see if it can help you with the Commons Stack partnership db!
