### ISSUE TITLE
Designs for swag for TEC shop

### ISSUE THREAD

**Issue by freedumbs00** [CommonsBuild/coordination#505]
## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by freedumbs00** [comment]
Should I submit those ideas for designs here or in the Telegram channel for the Swag shop?

**Comment by tamarandom** [comment]
@freedumbs00 The shop ;)

**Comment by tamarandom** [comment]
Hey @freedumbs00 Do you have higher rez images that the batch that threw a warning in the printful design tool? The store is ready for your l33t design skillz.

**Comment by tamarandom** [comment]
@markoprljic @freedumbs00 - A special Hatcher T-shirt design would rock. We have a default version with just the TEC logo but can we kick it up a notch? Is this something realistic for this Sprint?

**Comment by markoprljic** [comment]
Let's do it!

**Comment by markoprljic** [comment]
Some ideas...

![Image 2021-04-16 at 3 39 21 pm](https://user-images.githubusercontent.com/5704285/115032767-fae72700-9ec9-11eb-80d7-ff0f8c675f73.jpg)

![Image 2021-04-16 at 3 39 34 pm](https://user-images.githubusercontent.com/5704285/115032783-fe7aae00-9ec9-11eb-954e-9382c8585bd4.jpg)

![Image 2021-04-16 at 3 39 40 pm](https://user-images.githubusercontent.com/5704285/115032793-01759e80-9eca-11eb-9bc1-c5e0708b8768.jpg)
