### ISSUE TITLE
Setup hack sesh for review of Gitbook - where does it need help? 

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#512]
## 📋 Anything to add?

Create a list of areas where Gitbook needs filling, create Epic+ issues & assign them to contributors. 

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by tamarandom** [comment]
@liviade1 Where is the best place for me to start filling sections related to each Working Group? One of these two places (see image below)? Or somewhere else?

 ![Screen Shot 2021-03-23 at 7.38.15 PM.png](https://images.zenhubusercontent.com/5faaa1d038c6409364f7830c/e65720d0-1c23-41c0-a84c-4cc25ed5170b)

**Comment by chuygarcia92** [comment]
we will take a look into this issue next Monday at 12PM PST at the content workshop
