### ISSUE TITLE
Review/feedback on Shermin's TEC blog

### ISSUE THREAD

**Issue by jessicazartler** [CommonsBuild/coordination#517]
## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@Jeff-Emmett @tamarandom 

## 🔗 Work doc - inspirational links
https://docs.google.com/document/d/1g6JNGcXeUOm31SY56TSP1d2uzO4GXM-ke3OzMkHmGBM/edit?usp=sharing

**Comment by jessicazartler** [comment]
I need to catch back up with Shermin, I had suggested she wait a bit until the hatcher content is fleshed out a bit more.. but will continue this and check in with her now - also, she requested being invited to the Comms meetings so I will send her a calendar invite for that to join next week

**Comment by tamarandom** [comment]
Hey @jessicazartler Is there anything left to do with this one?

**Comment by markoprljic** [comment]
Hi again @jessicazartler Any update on this?

**Comment by tamarandom** [comment]
Hey @jessicazartler! I'm reading the doc now and am thinking that as 1) it's already quite out of date regarding the Hatch and 2) you and Jeff published the What is a Hatch article by Commons Stack and 3) we have the visual explainers - that this subject is already well covered. 

That said, a guest blog from Shermin would be enormous! And we should make the effort to make that happen.  @chuygarcia92 and I are thinking we close this issue and then you and he can reach out to Shermin to see what other subject might be a good match. Does that sound good to you?

**Comment by jessicazartler** [comment]
I contacted Shermin, she is no longer available to contribute. She has moved on to writing a new book. Closing.
