### ISSUE TITLE
5 Steps TEC Hatch

### ISSUE THREAD

**Issue by markoprljic** [CommonsBuild/coordination#518]
## 📋 Anything to add?

High Level Simplified piece on the hatch for "busy Token Engineer audience"
Medium/forum post with graphic/visual (egg diagram)

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@jessicazartler 

## 🔗 Work doc - inspirational links
https://docs.google.com/document/d/1Ji2vV5c_PCXt2q0G-1wTddyOaUp5ESKWht2UKcoE7S0/edit

**Comment by markoprljic** [comment]
@jessicazartler Here's the issue. Can you update the description and provide more context on design needs? Thanks.

**Comment by jessicazartler** [comment]
Added doc/note @eduardovegap is taking this forward thanks!

**Comment by tamarandom** [comment]
Update : done by @divine-comedian & closing!
