### ISSUE TITLE
Content Distribution Process

### ISSUE THREAD

**Issue by markoprljic** [CommonsBuild/coordination#523]
## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by markoprljic** [comment]
@natenatesoo You want to look at the repo I created specifically for content distribution and check the flow in columns https://github.com/tecommons/content-distribution#workspaces/content-production-and-distribution-60549332d7d741001bbea827/board?repos=349409011 Let me know what you think.

**Comment by tamarandom** [comment]
Update : Testing the process that was created.
