### ISSUE TITLE
DISTRIBUTION - How to Become a Hatcher 

### ISSUE THREAD

**Issue by markoprljic** [CommonsBuild/coordination#525]
## 📋 Anything to add?

Eduardos peice needs distribution. 
https://app.zenhub.com/workspaces/tec-coordination-workspace-5fad0d3fbbe4da0011c2f40d/issues/tecommons/coordination/418

## 🤼‍ Reviewer

@eduardovegap 

## 🔗 Work doc - inspirational links
https://docs.google.com/document/d/1tsEPNb-gLEh9FKOGLBPt0prfWrOwjmnnjtPdCpy8lxo/edit

**Comment by markoprljic** [comment]
cc/ @eduardovegap

**Comment by tamarandom** [comment]
Hey @markoprljic My opinion is that this piece is not ready for distribution. Has someone else already signed off on it? Can we please hold off until we have a process in place which includes reviewing and approving prior to distribution. 

As @jessicazartler takes on leading partnerships and ecosystem among her other crucial tasks, we will need to put into place the process for content distribution in TEC. Scaffolding, editing, sign-offs and, ultimately, selection of distribution channels with consistent messaging. @natenatesoo is working on this but in the mean time I suggest we have myself or Griff sign off on readiness for distribution. As a stop-gap measure. Personally, I would be checking with @jessicazartler under advice process until we have something else in place.

**Comment by tamarandom** [comment]
Update : this piece has gone through an edit by @GriffGreen and is now going through a revision by @eduardovegap. Not ready for distribution yet but hopefully soon. 🌺

I've modified the title to reflect it's a revision (not distribution) issue and changed ownership to @eduardovegap so it's on his workload of this Sprint.

**Comment by tamarandom** [comment]
Actually, there is already #418 open for the editing process. Closing this one to keep things simple.
