### ISSUE TITLE
Paramms Audit

### ISSUE THREAD

**Issue by Zeptimus** [CommonsBuild/coordination#528]
## 📋 Anything to add?
@iviangita @freedumbs00 

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by Zeptimus** [comment]
Audit its done, @freedumbs00 its going to add it  to advice process and we can close this issue

**Comment by tamarandom** [comment]
Update : @freedumbs00 to post to the forum and then close this issue?

**Comment by freedumbs00** [comment]
Posted and closing.
