### ISSUE TITLE
Legal audit

### ISSUE THREAD

**Issue by Zeptimus** [CommonsBuild/coordination#529]
## 📋 Anything to add?
@iviangita @Santigs 

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by Zeptimus** [comment]
Audit its done, @Santigs its going to add it  to advice process Friday morning (CET) and we can close this issue

**Comment by iviangita** [comment]
Closing! Posted on the forum:

https://forum.tecommons.org/t/legal-working-group-audit/319
