### ISSUE TITLE
Hatch Swag / doc the process to later hand off

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#534]

**Comment by tamarandom** [comment]
We turned a corner on this, finally! 

Thanks to @krisjpi @kristoferlund  and @Vyvy-vi! But it's still quite perplexing to all. 

Will document the details and strange backend mystery as best as I can. 

The skeleton is up but not yet accepting our custom token. There are still steps to do. Anyone know anyone that knows the dShop code and how it works? We could really use that help on this project. 

https://swag.tecommons.org/#/

Will be updating this doc as things move forward over the next Sprint:
https://docs.google.com/document/d/107mG7Rx_Hi5i098Z6Y8EtnltqukjeYhif8LMiOVDGBc/edit

**Comment by tamarandom** [comment]
With help from @kristoferlund @Vyvy-vi and geleeroyale, progress was made (again) this Sprint but the token is the last piece to be done. And, a good documentation of how to edit the code and deploy for the next to need to know.

**Comment by kristoferlund** [comment]
There is now a short doc on how to update the server: https://github.com/commons-stack/cslove-dshop/blob/main/devops/README.md

**Comment by tamarandom** [comment]
@kristoferlund this is excellent! Thanks! Once we have the token issue solved we can add that piece to this doc and close this issue for good!

**Comment by natenatesoo** [comment]
Update: Still waiting for Confirmation @kristoferlund.

**Comment by kristoferlund** [comment]
@natenatesoo The Swagtec token is now fully implemented and working if that is what you mean. This issue can probably be closed unless there is something I have missed.

**Comment by natenatesoo** [comment]
@kristoferlund @tamarandom Just looking to confirm that there is documentation on the token issuance?/problems, if we want that to be published within the cslove/devops repo. If not, lets go ahead and close the issue!

**Comment by kristoferlund** [comment]
The issue was the token and the shop not working together in a good way. Now they do. Closing issue.
