### ISSUE TITLE
Validate the Dashboard with the Newest Deployment of the TEC Hatch DAO

### ISSUE THREAD

**Issue by GriffGreen** [CommonsBuild/coordination#537]
## 📋 Anything to add?

@marthendalnunes is on this with @sembrestels 

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by freedumbs00** [comment]
@GriffGreen  Lets fucking do this

**Comment by tamarandom** [comment]
Update : ready, set, close.
