### ISSUE TITLE
FREEEEEZE THE GOD DAMN HATCH!!

### ISSUE THREAD

**Issue by GriffGreen** [CommonsBuild/coordination#538]
## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by tamarandom** [comment]
🧊  🧊  🧊  🧊  🧊  🧊  🧊  🧊  🧊  🧊  🧊  
 ❄️ ❄️ ❄️ ❄️ ❄️ ❄️ ❄️ ❄️ ❄️ ❄️ ❄️ ❄️ ❄️ ❄️ 
    🍧 🍧 🍧 🍧 🍧 🍧 🍧 🍧 🍧 🍧 🍧 🍧 🍧 🍧 
       🧊  🧊  🧊  🧊  🧊  🧊  🧊  🧊  🧊  🧊  🧊  🧊 
           ❄️ ❄️ ❄️ ❄️ ❄️ ❄️ ❄️ ❄️ ❄️ ❄️ ❄️ ❄️ ❄️ ❄️ 
              🍧 🍧 🍧 🍧 🍧 🍧 🍧 🍧 🍧 🍧 🍧 🍧 🍧 🍧 
                 🧊  🧊  🧊  🧊  🧊  🧊  🧊  🧊  🧊  🧊  🧊

**Comment by tamarandom** [comment]
!!!! Closing!
