### ISSUE TITLE
Find the part of Cryptosnews talk where Griff talks about Token Engineering and link it and put it in the Twitter content list

### ISSUE THREAD

**Issue by GriffGreen** [CommonsBuild/coordination#542]
## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@chuygarcia92

**Comment by markoprljic** [comment]
@chuygarcia92 Update on this? Will this be close before tomorrow?

**Comment by tamarandom** [comment]
@chuygarcia92 will check with the new contributors with video editing experience if they want to take this on.

**Comment by tamarandom** [comment]
@chuygarcia92 I'm on a sync with Fahern (on discord, @lucashygate on github) and he is happy to take this on. He will reach out to you if he has any questions. 

Here is what I shared:

- Turn the highlights of this video into 2-3 minute "highlight" 
- https://www.youtube.com/watch?v=ShUSPMONPS8
- ![unknown.png](https://images.zenhubusercontent.com/5faaa1d038c6409364f7830c/bcd3ebd7-b568-442b-a5d6-a172ea61d0b6)

**Comment by tamarandom** [comment]
Done by fahern!

**Comment by natenatesoo** [comment]
Update: @chuygarcia92 still working on it.

**Comment by chuygarcia92** [comment]
Uploaded!
https://youtu.be/0GCei891fm8
