### ISSUE TITLE
Find the part of Griff's Metafest talk where Griff talks about Token Engineering and link it and put it in the Twitter content list

### ISSUE THREAD

**Issue by GriffGreen** [CommonsBuild/coordination#544]
## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by chuygarcia92** [comment]
This is the final 2 min clip of Griff talking about TEC in his MetaFest presentation:

https://drive.google.com/file/d/116hZjJJl9mvHH-zKw1Ml2Dd_Ea6bqi93/view?usp=sharing
