### ISSUE TITLE
Create a list of useful links for new Discord members

### ISSUE THREAD

**Issue by markoprljic** [CommonsBuild/coordination#554]
## 📋 Anything to add?
Hy guys. I'm just thinking loud. How about a URL collection? Maybe in the #🏁start-here  channel?
I'm pretty new here, trying to wrap my head around all the topics being discussed in this community. And I'm jumping around between discord, github, the forum, googledocs... At the beginning it would have been nice to have kind of a collection of usefull links, at least for me...
But all in all, yeah, I'm excited man_dancing

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by Vyvy-vi** [comment]
That would be great-!

**Comment by baartch** [comment]
May I shortly tell my story about my first contact with the TEC? :) I found a link to the Commons Stack Simulator on twitter. Wow, this was awesome and I was very excited! Then, after the simulation, there was a link to the _CS dDEV_ Telegram channel, so I joined, and had no clue where I am and what it is about. I felt like I was climing someone else's fence in the backyard. I wasn't sure if I was wanted to be there. But it made me very curious so I started sniffing around :-) And then I found discord and the forum and so on....

Some questions:

- Where do you want to lead first visitors to, to gain more insight?
I know about two options. One is the [forum](https://forum.tecommons.org/c/welcome-to-the-tec/12) and the other, I just discovered today, is the [gitbook](https://token-engineering-commons.gitbook.io/). The latter is awesome prepared and very comprehensive. Definitely my favorite. Even though unfortunately the [mission](https://token-engineering-commons.gitbook.io/tec-handbook/what-is-the-tec/mission-vision-and-values) is currently missing.

- How about leading from every communication media to this same introducion? Maybe with welcome-bots on Telegram and discord?

- Who does the TEC want as new members?
To be honest, the answer to this question is still not very clear to me. Is TEC looking for people with specific skills or is anyone interested welcome? I mean, I was asking this myself for a long time. I'm very interested and curious, but I have absolutely no clue about Token Engineering. So can I be of value to this community?
This is something that maybe could be placed a little more infront? I just today found a paragraph about this in the [forum](https://token-engineering-commons.gitbook.io/tec-handbook/hatch-101/welcome-hatchers/hatcher-outreach#why-should-i-become-a-hatcher).


With my modest knowledge today, if I would have to introduce someone new, I would point to these three resources:
- the gitbook
- the calender (with mentioning the AMA)
- [Griff's speach](https://www.youtube.com/watch?v=ofa9QSqQXf8&t=132s) on the metafest. Even if it's more about Commons Stack than TEC, watching this was very enlightening to me.

**Comment by markoprljic** [comment]
Amazing feedback @baartch Thank you!

**Comment by tamarandom** [comment]
Thank you @baartch for sharing your experience and recommendations. The good news is that only the truly dedicated, like you, make their way in. But we can do better. The even more good news is that we are onboarding an onboarding coordinator this week. We are aware that there is a gap here and that we would very much like to make the journey from TEC-curious to TEC-active-contributor as frictionless as we can.

**Comment by markoprljic** [comment]
@Vyvy-vi Will add links to get started to the Discord onboarding channel.

**Comment by Vyvy-vi** [comment]
Should these be added to the bot's message?

**Comment by markoprljic** [comment]
Yes, and meybe it wouldn't hurt to add them in start here channel permanently.

**Comment by tamarandom** [comment]
Update : Closed by Marko.

**Comment by Vyvy-vi** [comment]
![Screenshot 2021-04-05 at 5 40 11 PM](https://user-images.githubusercontent.com/62864373/113572539-ff901d80-9635-11eb-9cc3-76930f83640f.png)
Added some of the links mentioned
