### ISSUE TITLE
Praise bot issue - apostrophes

### ISSUE THREAD

**Issue by iviangita** [CommonsBuild/coordination#563]
## 📋 Anything to add?

Praise bot doesn't recognize my praise with apostrophes

![image.png](https://images.zenhubusercontent.com/5fb5cba95f94b9eb73a91fe5/de60d7b5-fff2-42d8-89c4-a25d80a90ce8)

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by iviangita** [comment]
Hi @Vyvy-vi hope you can give us updates on this? :D

**Comment by Vyvy-vi** [comment]
I reached out to `rdfbbx#6437` about this. They told me this is a known bug, but they're not sure if this is an issue on their bot's side.
They said they would look into this issue in holidays.

**Comment by tamarandom** [comment]
@iviangita is this a new phenomenon or has it always been this way? 

I wonder if there is an escape char that can be used "treat" the originals with a simple copy and replace?

**Comment by iviangita** [comment]
@tamarandom it has always been like that for me. @Vyvy-vi also tried it and he encountered the same issue. Just worried that praises from other users will not go through if they have apostrophes and they don't realize it.

**Comment by Vyvy-vi** [comment]
I think this can be fixed in a quick Hack Sesh, if `rdfbbx#6437` is available(The Praise Bot isn't opensource, so can't really look for any solutions or debug it)

**Comment by tamarandom** [comment]
Was this fixed? I just tried on CS and TEC discord servers. 
![Screen Shot 2021-04-20 at 12 13 55 PM](https://user-images.githubusercontent.com/703624/115379514-e361b400-a1d1-11eb-9c40-9eef35040627.png)

**Comment by iviangita** [comment]
@Vyvy-vi  the apostrophe issue still isn't fixed on my end, do other people also get this issue or is it just me? :(

![image.png](https://images.zenhubusercontent.com/5fb5cba95f94b9eb73a91fe5/c3a8ec74-7a82-4dbb-b7d6-ddb04247ff25)

**Comment by Vyvy-vi** [comment]
@hurek 
Maybe we can do a hack sesh in this issue, this week

**Comment by hurek** [comment]
Solved on dev side. Just need to update bot.

**Comment by Vyvy-vi** [comment]
Solved by https://github.com/hurek/Praise-Bot-Discord/commit/e992d77264e89a528e7cb5295e775fe135f5a056 thanks to @hurek 
It might take some time for the fix to be reflected(until the bot is updated, but it's fixed)

**Comment by iviangita** [comment]
@hurek @Vyvy-vi THANK YOU!!!!

**Comment by tamarandom** [comment]
Excellent!! 🥳
