### ISSUE TITLE
TWEET: Call Recorders and Comms Contributors

### ISSUE THREAD

**Issue by iviangita** [CommonsBuild/coordination#568]
## 📋 Anything to add?

- [x] Volunteers wanted for Transparancy WG // Recorders
- [x] Volunteers wanted for Communications WG // Project Managers, Writers, Editors, Social Media managers

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@markoprljic @tamarandom

**Comment by iviangita** [comment]
Call recorders:

https://twitter.com/tecmns/status/1375432457441341440?s=20

**Comment by iviangita** [comment]
Draft for Comms - for editing/review please :)

Wordsmiths, WE WANT YOU! We’re looking for writers, editors, social media managers and project managers to support our content production & distribution 📝📣

Share your skills with us & help us advance token engineering!

To volunteer, DM our Communications Steward @markop 📩

![image.png](https://images.zenhubusercontent.com/5fb5cba95f94b9eb73a91fe5/2c992062-ac9f-4b37-bb50-c3a556cba0fd)

**Comment by markoprljic** [comment]
Great @iviangita Push the button :)

**Comment by iviangita** [comment]
Done! Closing!
