### ISSUE TITLE
Change auto image for Forum

### ISSUE THREAD

**Issue by jessicazartler** [CommonsBuild/coordination#571]
## 📋 Anything to add?

On Twitter, the Forum image card that automatically pops up for forum links is not super great, would be awesome if we can change it to a nicer image

You can check the image here https://cards-dev.twitter.com/validator or see below

Thank you for all your hard work!

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@tamarandom @markoprljic 

## 🔗 Work doc - inspirational links

<img width="425" alt="Tweet" src="https://user-images.githubusercontent.com/43972522/112864275-ab10ff00-9085-11eb-87b8-7c58c4003d89.png">

**Comment by tamarandom** [comment]
This would be great @jessicazartler !

@freedumbs00 Can you take ownership of this one? I took @iviangita off as an assignee so we stick to the one issue = one person responsible to ensure it gets done.

**Comment by markoprljic** [comment]
@freedumbs00 I pushed Marketing folder with graphic assets to the branding repo https://github.com/TECommons/tec-branding-assets

You can grab the Open Graph image from there and update the forum preview image.

**Comment by freedumbs00** [comment]
Closing issue.  Made changes
