### ISSUE TITLE
Create Teams to simplify tagging in github issues

### ISSUE THREAD

**Issue by divine-comedian** [CommonsBuild/coordination#572]
Following the discussion between @markoprljic  @natenatesoo  and I today we have begun refining the process for our content distribtution, focusing on the zenhub board -https://github.com/TECommons/content-distribution/issues

Creating Teams within the TEC organization will help us to keep things moving down the pipelines, the idea is being able to tag entire working groups to review or add commentary and hopefully to approve content to be published. 

I've created all the teams based on the working groups outlined in our community call documents. Please feel free to add yourself if you haven't already been added to your respective teams.  - https://github.com/orgs/TECommons/teams

**Comment by markoprljic** [comment]
Excellent!

**Comment by natenatesoo** [comment]
I added the teams for our CPD process!
