### ISSUE TITLE
Design Criteria for CDP Content Selection Process

### ISSUE THREAD

**Issue by divine-comedian** [CommonsBuild/coordination#575]
We need to make some guideline documentation for the metrics by which we would choose or choose not to approve an idea or requested content to be written. 

Recognizing this will be a constantly evolving set of criteria but it's good to get some stuff on paper!

**Comment by markoprljic** [comment]
Maybe a checklist we can run through that is embedded in the issue template? Still, criteria to be defined and I may not be the best person to define those :/

**Comment by natenatesoo** [comment]
@divine-comedian ....After putting some thought into this, I think it's important to ask where approval is actually needed?  If we look at the sources for our content, we have internal content that is created on behalf of Working Groups to achieve a communication goal, and we have external content that can be submitted to re-enforce our communication goals.  

The external content doesn't need approval to be written, it just needs approval to be published.  The internal content is requested by WG Leads and therefore is implicitly approved.  For members who _want_ to write on behalf of a Working Group, it should naturally be proposed and approved within the WG itself before it hits the ZenHub Board.

So, I propose that we treat external content (ex: Zarghams blog post) a little differently by having the content creator just submit their content for review by the Stewards -- who are generally the most informed on our Communication Goals (This includes Stewards soliciting content from specific individuals in the TE Community).  This also provides an opportunity for Stewards to build a relationship with new potential content creators.  If the content is approved by the Stewards, they can place the content in the appropriate place (to be edited, or to be published based on the Stewards discretion).

**Comment by natenatesoo** [comment]
We can still maintain our pipeline for Ideas & Requests, but I suggest that Working Groups should be conscious of their messaging needs and use that pipeline as a source of inspiration for content ideas to be produced.  We should make sure that all issues within the ideas & requests pipeline are properly tagged with the relevant working group(s) upon submission, so relevant WG members can collectively decide what they like and who may be well placed to create that content according to their communication goals.

**Comment by divine-comedian** [comment]
Yeah that makes lots of sense. I think it's a lot easier to ask WGs to self-manage than to find another group to shoulder that. I do think given your suggestions it would be good to have a couple housekeepers just to keep the board functional. making sure things are in the right pipeline, right tags and following up with idle issues to keep them moving.

**Comment by tamarandom** [comment]
@divine-comedian @natenatesoo @markoprljic Are there any next steps for this issue? Or should be be closed?

**Comment by chuygarcia92** [comment]
the C&D process has been covering this, so closing issue
https://hackmd.io/@1sBtuDmrRBG360k8-EXf2A/BJ1ZYSl5_
