### ISSUE TITLE
Create Template for Ideas and Requests on CDP 

### ISSUE THREAD

**Issue by divine-comedian** [CommonsBuild/coordination#576]
nate has already made a pretty good template that we can plug in

suggestions and modifcations welcome. https://docs.google.com/document/d/1wdLEpfVIpcm6w1PdglyY0V2R_6s5E-lIiuWuUoyXIvo/edit

**Comment by divine-comedian** [comment]
@natenatesoo any updates on the template? If you have something ready I'd be happy to plug it in on github for ya.

**Comment by natenatesoo** [comment]
I will create the template. Is there any way to limit the options of issue creation to the templates we offer?

**Comment by divine-comedian** [comment]
You can set the default template that will pop up automatically when an issue is created.

**Comment by tamarandom** [comment]
Oooh this is the week of github issue templates!! There is a new one for Default Issues and Contributor Issues too!! (#663 and #658)

Would love your input on them @natenatesoo and @divine-comedian : https://docs.google.com/document/d/1r1D0ZTbOCf3RQs2K6W-uOWniqzvJo5WDASmo5pYyArU/edit

**Comment by natenatesoo** [comment]
Update: Done.

**Comment by chuygarcia92** [comment]
we have a working template on the C&D repo, so closing :)
