### ISSUE TITLE
Need to change the icons and links in github to be Commons Stack not TEC

### ISSUE THREAD

**Issue by GriffGreen** [CommonsBuild/coordination#581]
## 📋 Anything to add?

![Screen Shot 2021-04-02 at 8 10 15 AM](https://user-images.githubusercontent.com/14945613/113418368-a3bf5d80-93c5-11eb-9d79-014ddb13ee4a.png)

## ⏰ Urgency/Due Date/Blockers?

this sprint

## ❓ Why is it important?

legal

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by markoprljic** [comment]
Done. I put it on a dark background to distinguish it from the Commons Stack repo.

![Image 2021-04-02 at 4 09 56 pm](https://user-images.githubusercontent.com/5704285/113422989-fe5cb780-93cd-11eb-9378-cd5f7857a943.jpg)
