### ISSUE TITLE
Update the transparency audits from Soft Gov, Hatcher Outreach and Gravity WGs

### ISSUE THREAD

**Issue by iviangita** [CommonsBuild/coordination#612]
## 📋 Anything to add?

Looping @iviangita 

## 🎉 Subtasks

- [ ] Soft Gov
- [ ] Hatch Outreach
- [ ] Gravity

## 🤼‍ Reviewer

@

**Comment by Zeptimus** [comment]
Gravity Done
Soft gov, livi reach out and she is doing it

**Comment by Zeptimus** [comment]
All of them updated: https://docs.google.com/spreadsheets/d/12_PK_G9-gGxPOm-mdl5dlfdh9GSZGuI5gkTLkWlfNcY/edit#gid=674364535
