### ISSUE TITLE
Proposal Squad kickoff 

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#613]
## 📋 Anything to add?

From our last retrospective... forming this squad to devise the procedures to do outreach to Projects/Proposals.
Main task here : to have the kickoff session.

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by eduardovegap** [comment]
Squad is complete: Jess, Jake, Griff y Eduardo.
