### ISSUE TITLE
How to outreach to proposals 

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#614]
## 📋 Anything to add?

Answering these questions, among others : 
- what is the best way to communicate the TEC to these projects
- develop script or deck to have a common, unified message
- create list of additional links/materials to share 
- follow-up and tracking progress of the projects 

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by eduardovegap** [comment]
Closed. 

Document of reference: https://docs.google.com/document/d/1KeMBHxQMjy9WuoFbnjzJP84KYt_qbPFlXiF-ZeVv5cQ/edit
