### ISSUE TITLE
Jess / Proposal squad outreach 

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#615]

**Comment by tamarandom** [comment]
Closing. 
As there are new ideas and new proposals, share with @eduardovegap and Hatch Outreach team.

**Comment by jessicazartler** [comment]
Thanks Tam, Jeff and I are due to submit a few proposals with Z - it's backlogged but we'll try to get it in end of hatch / before the Commons Upgrade - otherwise, I don't see a need for more proposals, they will come when there is $ 
Thank you for everyone's hard work!

**Comment by tamarandom** [comment]
Sorry bout that! Some closed issues still had a repeating tag and came back to life! Fixing them now.
