### ISSUE TITLE
Bug : submitting MVV proposal without title causes the issue to disappear 

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#619]
This has happened to @eduardovegap and @markoprljic - to get in touch with them for more details. 
Might this be template related, @kristoferlund

**Comment by kristoferlund** [comment]
@eduardovegap @markoprljic can you detail, when and how did this happen? Does the issue disappear from GitHub or only from the TokenLog interface?

I tried to recreate the scenario but creating an issue without title does not seem to be possible on GitHub.

**Comment by markoprljic** [comment]
I wish I could provide more details but that's all I got. I don't think my title was empty, instead I just left the default one there.

**Comment by tamarandom** [comment]
We should close this if we can't recreate it. Any objections? Who wants the satisfaction to hit close? 🏄🏽

**Comment by markoprljic** [comment]
You! 🙂

**Comment by tamarandom** [comment]
🏄🏻‍♀️
