### ISSUE TITLE
Process to praise the Working Group attendees after each call 

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#622]
## 📋 Anything to add?

Thanks @Zeptimus and @iviangita for suggesting to take this one. I'm opening this issue to give you time to think about how is best to do it. I assigned it to Ivy as the Master Praise Giver.

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by iviangita** [comment]
Assuming that the TEC call protocols are being followed (specifically having a moderator in WG sync calls), this is the suggestion that came out from our discussion in the previous Transparency call:

- Moderator helping to list out the names of the people attending the call. (Juan in community calls & stewards) but we need a clear list of monitors for calls -Tag team (speak about it with stewards)
- Giving the responsibility of praising attendees to the moderator.

cc: @Zeptimus @JuankBell

**Comment by iviangita** [comment]
Closing! We'll let anyone in the community dish the praise, but @Zeptimus and I will be monitoring/ensuring that WG attendees receive praise after each call. If no one gives the praise, Zep and I will do it.
