### ISSUE TITLE
Have a published step-by-step conflict mgt process connected with the graduated sanctions

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#628]
## 📋 Anything to add?

🤙🏽  Our Sprint 7 retrospective action! 🤙🏽

@JuankBell, please feel free to update this issue body as it makes sense for you on how to best address this. 

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by JuankBell** [comment]
https://forum.tecommons.org/t/gravity-easy-step-by-step/354 :D
