### ISSUE TITLE
Update the final Hatch T&C after the Parameter vote is final.

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#629]
## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by Santigs** [comment]
Updated the doc with the params
https://docs.google.com/document/d/1miPZG3UcYPml_bwjloMwB0OwXh9TBbD1kE_UBNMdIBc/edit

**Comment by Santigs** [comment]
[https://app.zenhub.com/files/306706322/77da9fcc-b3a7-4ac4-800f-e56eaf75860f/download](https://app.zenhub.com/files/306706322/77da9fcc-b3a7-4ac4-800f-e56eaf75860f/download)

**Comment by tamarandom** [comment]
Update: this is done and being included in the final review of all docs.
