### ISSUE TITLE
Create the guidelines on how to onboard new community members 

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#646]
## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by danelsuga** [comment]
There are now two brief documents to support this need for onboarding guidelines:

1) Onboarding Journey: a brief how-to guide including a message pinned on Discord for new folks (and ideally also sent by anyone who is the first to encounter some one new)
https://docs.google.com/document/d/1EiQTPNKANGwPiofEfHe-BVTzecA9vrNYPjrOt7umCXE/edit?ts=6074165a

2) Onboarding in the TEC: a short slideshow to aid in the onboarding process. 
https://docs.google.com/presentation/d/1K-pRAOGffyv9vNZ7bYGx-xb-PMq3_qKlbTZmyzvL-as/edit#slide=id.gd2d529e02f_0_66

**Comment by danelsuga** [comment]
Closing!
