### ISSUE TITLE
Incorporate user testing from Nathan and Craig to Hatch Config Dash

### ISSUE THREAD

**Issue by GriffGreen** [CommonsBuild/coordination#648]
## 📋 Anything to add?

https://docs.google.com/document/d/13sTO3eSs9IDde_g3P-5qpdNz4oumUhMQH17r0r9XbMc/edit?usp=sharing

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by freedumbs00** [comment]
These issues have been made and are in the Changing the Technocracy Repo.   Closing this
