### ISSUE TITLE
Close all the Hatch Issues!

### ISSUE THREAD

**Issue by GriffGreen** [CommonsBuild/coordination#651]
![Screen Shot 2021-04-16 at 9.16.40 AM.png](https://images.zenhubusercontent.com/597b3dc4f8b79f8376e1224b/b98901a4-ab9d-4bb0-9d6c-d26d4a8ebc5f)

Work is happening in https://app.zenhub.com/workspaces/commons-swarm-workspace-5fe322aef3aab0001be1d518/board?repos=302764557,307524707,307465991,307811091,315995540,302769969,315489302,314825972,312708148,322581189,320314688,322963181,317923305,315581225

**Comment by GriffGreen** [comment]
Still need to finish the vote and get Adria's sign off

**Comment by tamarandom** [comment]
Update: close
