### ISSUE TITLE
Proposal deck 

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#652]
## 📋 Anything to add?

@eduardovegap to fill in the details here 

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by eduardovegap** [comment]
Done, updates and comment check: 
https://docs.google.com/presentation/d/1L5eudOvAvNY9dtwh8C6TR05CJnezmajbjkGsuYH5Do8/edit?usp=sharing
