### ISSUE TITLE
Meet with all the Stewards to gather insight and feedback about Onboarding in the TEC 

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#653]
## 📋 Anything to add?

Criteria for success:
-[ ] Katy will have had 1-1 with all the Stewards for advice process to inform the onboarding journey 

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by danelsuga** [comment]
Two tomorrow and done.

**Comment by danelsuga** [comment]
Done! :)
