### ISSUE TITLE
No one uses the Github template - make it shorter and include "Definition of done"

### ISSUE THREAD

**Issue by GriffGreen** [CommonsBuild/coordination#658]
Look... another empty template... smh

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by tamarandom** [comment]
@danelsuga and I both has templates to update (see # 663) so we worked on it together. 

Here is the draft: https://docs.google.com/document/d/1r1D0ZTbOCf3RQs2K6W-uOWniqzvJo5WDASmo5pYyArU/edit#

Asking for Advice Process from all the Stewards but especially @liviade1 @chuygarcia92 @natenatesoo @markoprljic @Zeptimus  --> Are there any components that could be added or altered to make the template more useful?

**Comment by markoprljic** [comment]
I think these look great! Love to see success criteria incorporated. Thumbs up from me.

**Comment by tamarandom** [comment]
Excellent, @markoprljic. Thanks for the feedback!

Passed to @Vyvy-vi to deploy. (#710)
