### ISSUE TITLE
What is the email situation for the TEC?

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#659]
## 📋 Anything to add?

Looking for some information about what email capabilities we have at the TEC now. 🙏🏼

Looping in the two people who might know best : @cranders1 and @knobsdao 

Criteria for success:
-How are we collecting email? 
-How many emails do we currently have?
-Who has access to the email system (and is it all in Hubspot now?)

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by tamarandom** [comment]
Hey @cranders1 ! Since you tested out an email I'm thinking some good progress was made. Are there any outstanding items to do? Can you drop a short update here before our Sprint planning tomorrow, please?

**Comment by cranders1** [comment]
Hubspot is now active. Dan has migrated the appropriate CSTK records. 
We have approx 125 email addresses from individuals who authorized info transfer from CSTK to TEC.

Currently testing. 
Working on design, SEO, and overall utilization strategy at SEO work session fri 5/14.
More to come soon.

**Comment by tamarandom** [comment]
💚 💙 💜 💛 🧡

**Comment by tamarandom** [comment]
I think it's safe to say we can close this now ....

EXCELLENT for our future email campaigns!
