### ISSUE TITLE
Change medium link on website

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#660]

**Comment by tamarandom** [comment]
Should direct people to the "feature" medium link: 
https://medium.com/token-engineering-commons

 ![Screen Shot 2021-04-20 at 10.37.38 PM.png](https://images.zenhubusercontent.com/5faaa1d038c6409364f7830c/a666760a-3c95-4b72-aaaa-a07ae5fb9081)

**Comment by tamarandom** [comment]
Hey @kristoferlund can you please make this small change?

**Comment by kristoferlund** [comment]
✅   Forgot about this one but fixxed it now.

**Comment by tamarandom** [comment]
Awesome, thanks @kristoferlund !
