### ISSUE TITLE
Issue template for pieces of work that should be tagged "For Contributors"

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#663]
## 📋 Anything to add?

See the Commons Stack "for contributor" issue template as a model. 

## 🤼‍ Reviewer

@liviade1

**Comment by Vyvy-vi** [comment]
Is there any reason, that we're using the old issue_template location?

**Comment by tamarandom** [comment]
Hey @Vyvy-vi !! No good reason other that it's a very old template. ;) We'll be using the new template workflow now that we're taking the opportunity to refresh them.

**Comment by tamarandom** [comment]
See update to #658!

**Comment by tamarandom** [comment]
Passed to @Vyvy-vi to deploy. (#710)
