### ISSUE TITLE
Support T Wells with onboarding module framework

### ISSUE THREAD

**Issue by danelsuga** [CommonsBuild/coordination#665]
## 📋 Anything to add?

https://docs.google.com/document/d/1ct8K4AMqiHJHkF9NfkK03EaVacoLnecUJrDfkarhJXY/edit?ts=60888640

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by JuankBell** [comment]
I shared with him this repository that has great links for each Wg! https://github.com/CommonsBuild/tec-info/tree/main/wg-digest

**Comment by tamarandom** [comment]
Hey @chuygarcia92 @danelsuga  I'm doing the Transparency audit and just got to the question "Are the main tasks clearly assigned/owned by only one contributor in Github issues?"

This is the only issue the tarnishes an otherwise perfect record. 😂   I've added @chuygarcia92 as a reviewer but this task is specific for @danelsuga !!

**Comment by danelsuga** [comment]
I synced with T Wells on Tuesday, May 4 and am syncing with @chuygarcia92 today, May 6.

**Comment by danelsuga** [comment]
Actively working on this! Hope to have something to show for it shortly.

**Comment by danelsuga** [comment]
Coming along nicely! Realistically, the full structure can be complete by the Hatch but probably not in this sprint. T Wells just finished his teaching semester. He can now devote more time. He has shared a template with me today.

**Comment by danelsuga** [comment]
We've made some great progress. Rolling in @markoprljic to implement it on the website now.

**Comment by markoprljic** [comment]
I created the issue in Website repo and assigned to @kristoferlund https://github.com/CommonsBuild/tec-web/issues/33

**Comment by danelsuga** [comment]
It's also here https://github.com/CommonsBuild/tec-web/issues/32
and almost done! We can close it here, I think.
