### ISSUE TITLE
 community support around post hatch changes discussions

### ISSUE THREAD

**Issue by JuankBell** [CommonsBuild/coordination#677]
## 📋 Anything to add?

Talk with the stewards to identify the key changes and how to prepare the community.

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@liviade1

**Comment by liviade1** [comment]
@JuankBell is there anything still needed in this issue?

**Comment by natenatesoo** [comment]
Update: Closing, and reintroducing the subject via Forum.
