### ISSUE TITLE
Make Icebreakers and hangout spaces!

### ISSUE THREAD

**Issue by JuankBell** [CommonsBuild/coordination#678]
## 📋 Anything to add?

Make more icebreakers to build community relationships and incentivize communication

https://icebreaker.video/events/GRgR0mLvZk3CaYKMpOBO (update questions)

Proposed schedule, and link with onboarding process @danelsuga so that new members can participate.

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by Vyvy-vi** [comment]
I have a proposal here -
Since there's a discord bot being made, perhaps we can use the bot to host icebreakers in the discord itself. (might need a little work, but totally possible)

It's just that the icebreaker platform is a bit too buggy(and not opensource = A deal breaker :P)

**Comment by JuankBell** [comment]
That would be great @Vyvy-vi ! We were talking about start making them in the AMA calls during wednesdays. if there is a way we could pair randomly people for 1 on 1 in the Discord that would be amazing. But if its too hard we could give another try to the platform, I edited the questions of the past game with new ones!! :D https://gatheround.com/events/GRgR0mLvZk3CaYKMpOBO

**Comment by JuankBell** [comment]
This is in the icebox because will have a bigger impact after the hatch. Then it will me assigned to a new sprint.

**Comment by JuankBell** [comment]
We will have our first TEC lounge Today, Co-hosted between @eduardovegap and me :D

https://calendar.google.com/calendar/u/0/r/eventedit/copy/NTdjN3JiY2lpNWVnY2dodDVlMWdoYWU5ODAgNW1rZXAxYWQxajg2MGs2ZzdpN2ZyOHBscTBAZw/YmVsbC5qdWFuLmNhcmxvc0BnbWFpbC5jb20

We hope this can become a weekly activity in the TEC calendar so that we can continue building strong community relationships between contributors.

**Comment by natenatesoo** [comment]
Update: Creating some dates within the TEC Calendar for the Lounge.  Needing help managing the calendar.

**Comment by JuankBell** [comment]
![Captura de Pantalla 2021-08-06 a la(s) 8.23.46 p. m..png](https://images.zenhubusercontent.com/5fb57c9c5472cf79e80e7f7e/12d24258-a9cc-4fb5-a286-8a6ad2004439)

Thanks to @iviangita the TEC lounge is now a recurring event in the TEC calendar! We will be having this spaces all Fridays before the meme parties!

And also thanks to @eduardovegap for being supportive of this spaces in the TEC and other communities!
