### ISSUE TITLE
Update & add What's in a Hatch link to Forum Posts / Update Glossary Hatch term

### ISSUE THREAD

**Issue by jessicazartler** [CommonsBuild/coordination#681]
## 📋 Anything to add?

Adding CS blog on "What's in a hatch to the two forum posts below.. also, @tamarandom the glossary definition of "Hatch" needs to be updated as it used to mean when the bonding curve got initiatilized.. now because of launching in two parts, we have changed the definition of the Hatch

Also then, the Hatch definition should be updated in the glossary of the forum/Gitbook
https://forum.tecommons.org/t/2-glossary-of-terms/114

## 🎉 Subtasks

- [ ] Add CS hatch blog to two forum posts "Become a Hatcher" and Griff's Step by Step Guide
- [x] Fix hatch definition in Glossary & Gitbook
- [ ] 

## 🤼‍ Reviewer

@tamarandom @markoprljic 

## 🔗 Work doc - inspirational links
https://forum.tecommons.org/t/how-you-can-hatch-the-tec/328
https://forum.tecommons.org/t/3-become-a-hatcher/101
https://medium.com/commonsstack/whats-in-a-hatch-3799a398243a

**Comment by markoprljic** [comment]
@CommonsBuild/communications Does this need to go to the CD pipeline?

**Comment by tamarandom** [comment]
Thanks @jessicazartler !

I quickly fixed the Hatch definition in the Glossary since referring to initializing ABC as part of the Hatch is false. I left the link to the debate about the Hatch phases and added a link to the What is a Hatch article. It is just a quick fix.

**Comment by jessicazartler** [comment]
Thanks Tam you da best! @markoprljic up to ya'all to decide the rest thanks so much you two!!

**Comment by eduardovegap** [comment]
Shall we fusion this issue or create a new one regarding the updates of the gitbook/forum and so on?

**Comment by natenatesoo** [comment]
Update: Still a work in progress.

**Comment by tamarandom** [comment]
We can close this. The high priority issue was fixed. The lesser priority one is ok to let go of.
