### ISSUE TITLE
Create transparency on the process of the credentials 

### ISSUE THREAD

**Issue by Zeptimus** [CommonsBuild/coordination#691]
## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by iviangita** [comment]
Hi @Zeptimus I think we can close this? We've updated the access document and added it to Gitbook. Is there anything else that needs to be done? :)

**Comment by Zeptimus** [comment]
yeah! thanks ivi :D

**Comment by Zeptimus** [comment]
yeah! thanks ivi :D
