### ISSUE TITLE
Forum : latest posts are not latest 

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#693]
## 📋 Anything to add?

When I go to the forum to look for the latest posts, I often come across these older posts that have been "automatically bumped" (see pic). 

Right now, the #3 "latest post" is from Dec 2020. This is not a good UX for someone wanting to see the real latest posts from our community. 

![Screen Shot 2021-05-14 at 2.09.08 PM.png](https://images.zenhubusercontent.com/5faaa1d038c6409364f7830c/bb824fa3-4318-406c-9381-78a09861728e)

![Screen Shot 2021-05-14 at 2.11.26 PM.png](https://images.zenhubusercontent.com/5faaa1d038c6409364f7830c/9b5e056b-9780-4ced-bf05-e6a8b9af3629)

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@chuygarcia92

**Comment by Vyvy-vi** [comment]
I think this discussion refers how to disable the auto-bumping feature: https://meta.discourse.org/t/how-to-disable-discourse-automatic-bump-for-topics/116460

**Comment by tamarandom** [comment]
Excellent, @Vyvy-vi, yes!

**Comment by tamarandom** [comment]
@chuygarcia92, @Vyvy-vi agreed to take this on. I added you as the reviewer so this issue shows up in your Mentions on github.com/notifications.

@Vyvy-vi 🙏

**Comment by Vyvy-vi** [comment]
I think it should be fixed now, however, to verify maybe monitor - https://forum.tecommons.org/c/defi-legos-and-how-they-work-together/9/l/latest for a while to see if it automatically bumps anything

**Comment by tamarandom** [comment]
That's great! Thanks, @Vyvy-vi ! I tried to delete the bumps on a handful of articles but it's a very painful to do manually. Do you happen to know is they can be automatically deleted from the posts?

**Comment by Vyvy-vi** [comment]
Even after delating the bumps, I don't think that would affect the relative placement of the posts in the featured section 🤔

**Comment by tamarandom** [comment]
Yep. I manually deleted them from a few posts and, you're right, that didn't change their order in the Latest section. It just looks better! If there isn't an easy way to do this then let's accept that some of the older posts will have the bumps and that's ok.

**Comment by tamarandom** [comment]
Closing! Thanks for all @Vyvy-vi! Who's better than you?

**Comment by Vyvy-vi** [comment]
> Who's better than you?

Everyone 🙃
