### ISSUE TITLE
Blog post using Mitch's forum post: How do the Hatch Param Proposals Stack up?

### ISSUE THREAD

**Issue by danelsuga** [CommonsBuild/coordination#705]
## 📋 Anything to add?

Griff asked me to modify Mitch's forum post on the run-off vote and proposal comparison to get it on the Medium blog before this weekend. 

Briefly to my eyes, it doesn't need a lot of editing. Mitch, @divine-comedian, can you support me on this issue with your thoughts? I'd like to give credit to you as the writer and also anyone else who worked on it with you. Anything else?

## ⏰ Urgency/Due Date/Blockers?

This needs to be done today! Thanks!

## ❓ Why is it important?

This is to publicize the run-off vote over the weekend. 

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@divine-comedian 
@GriffGreen

**Comment by divine-comedian** [comment]
It looks good! Don't forget to give credit to griff, nathansuits and juankbell for their contributions as well.

Have you edited into medium yet? It could be tricky going from the markdown document.

**Comment by danelsuga** [comment]
Hi Mitch @divine-comedian! I haven't touched your post yet. I wasn't clear. Yes, it looks good! Is it OK with you if I run through it and tweak if needed? 

Yes, I've edit into Medium, and it's not the best, but I'll figure it out. It's sort of piece by piece and all that. 

Thanks! And great to all mentioned!

**Comment by danelsuga** [comment]
Done! Great job, @divine-comedian!

https://medium.com/token-engineering-commons/how-do-the-hatch-param-proposals-stack-up-e2f9696d02f4
