### ISSUE TITLE
Critical bug, Forum, oh noes.

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#708]
![Screen Shot 2021-05-25 at 12.02.37 AM.png](https://images.zenhubusercontent.com/5faaa1d038c6409364f7830c/bf46ed7a-0447-49d1-a4e5-08649f650b95)

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by Vyvy-vi** [comment]
It looks like someone would have to update this manually.
For this, we would need someone who has access to the Server/VM/Docker container that's running this, and run the commands-
```sh
cd /var/discourse
git pull
./launcher rebuild app
```

For more info - https://meta.discourse.org/t/how-do-i-manually-update-discourse-and-docker-image-to-latest/23325

**Comment by tamarandom** [comment]
Circle'd round with @krisjpi who might be able to do it but the longer term solution is to ask Kay (geleeroyale) if you can also have access to run this yourself.
