### ISSUE TITLE
Make #orientation a fun, warm channel for new members 

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#712]
## 👇🏽  What is this issue about? Give as much detail as you can. 
#orientation is the home of Onboarding and orientation. A fun, warm place for new members to ask questions or leave comments. 

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. New members are active and engaged in the channel
2. Plans for what to share there when and how to create more engagement 

##🧍🏻‍♀️🧍🏻‍♂️ Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@liviade1

**Comment by danelsuga** [comment]
I've started by updating a Forum post on WG's and contributing and posted it to the orientation channel. 

https://forum.tecommons.org/t/how-to-join-contribute/98

The hope is to have more regular posts and to encourage more new-joiners to reach out.

**Comment by danelsuga** [comment]
This is an active, ongoing project. I would like to regularly post Stewards contribution requests. I will start with posting the last one, but maybe we can create a new one this week? I suppose they don't change much?

**Comment by danelsuga** [comment]
Orientation is more active now with announcements for weekly Orientation meetings and new joiners interacting with one another We also have the Communitas WG. 

This is an ongoing project.
