### ISSUE TITLE
Pinned Discord message for 0mega

### ISSUE THREAD

**Issue by danelsuga** [CommonsBuild/coordination#713]
## 👇🏽  What is this issue about? Give as much detail as you can. 

New joiners do not see any info about 0mega when they join Discord. It's hard to find information about 0mega on Discord. 

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. Add a pinned message to the 0mega channel similar to the other WG's. 

##🧍🏻‍♀️🧍🏻‍♂️ Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@Sebnem

## 👀  Who should be in the loop about this issue?
@liviade1

**Comment by danelsuga** [comment]
Working on this with @solsista.

**Comment by danelsuga** [comment]
I've added a simple pinned message. @solsista , what do you think?

**Comment by tamarandom** [comment]
Looks good. Wouldn't hurt to add the agenda so it's within easy reach when people hop on the call but it' really up to each WG what to keep pinned there. So closing ....
