### ISSUE TITLE
Make Transparency Audit a big thing

### ISSUE THREAD

**Issue by iviangita** [CommonsBuild/coordination#716]
## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

##🧍🏻‍♀️🧍🏻‍♂️ Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by Zeptimus** [comment]
Do you think announce it every month like we did on the last community call would be enough to close this issue?
