### ISSUE TITLE
Figure out if we can cut Celeste from the Scope of the Commons Config Dashboard

### ISSUE THREAD

**Issue by GriffGreen** [CommonsBuild/coordination#723]
## 👇🏽  What is this issue about? Give as much detail as you can. 

There is a lot to design with this dashboard... the ABC, CV and dV are all very complicated... lock up is also critical... Celeste is the 5th set of decisions but maybe we can pull it out and have these params decided in a separate process. 

It could be a mix of working groups: Params, Legal, Gravity and Soft Gov could all weigh in.

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. The decision making process is finalized AND CLEAR... either it's in the dashboard or someone else has it. 

##🧍🏻‍♀️🧍🏻‍♂️ Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@mzargham

## 🔗  Are there links or docs related to this issue?

https://docs.google.com/document/d/1fLqlfMyQgUr8U6zZogu9NyTFAU6GxrzrygZRrxVIg90/edit#heading=h.7auf81fxc1vg

## 👀  Who should be in the loop about this issue?
@sembrestels @JuankBell @liviade1 @Santigs

**Comment by tamarandom** [comment]
Being replaced by #756. Closing.
