### ISSUE TITLE
Invite as many people into Params Parties as possible

### ISSUE THREAD

**Issue by GriffGreen** [CommonsBuild/coordination#726]
## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

##🧍🏻‍♀️🧍🏻‍♂️ Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by tamarandom** [comment]
Excellently done! Closing.
