### ISSUE TITLE
SAVE THE DATES JULY 19th-23rd PARIS ETHCC

### ISSUE THREAD

**Issue by GriffGreen** [CommonsBuild/coordination#727]
## 👇🏽  What is this issue about? Give as much detail as you can. 

https://ethcc.io/

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

##🧍🏻‍♀️🧍🏻‍♂️ Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by Zeptimus** [comment]
yaaaaaaaaaaaay! :D

**Comment by Santigs** [comment]
Nice!

**Comment by tamarandom** [comment]
update closing!

Come join us!
