### ISSUE TITLE
Membership dApp Bugs. 

### ISSUE THREAD

**Issue by eduardovegap** [CommonsBuild/coordination#729]
## 👇🏽  What is this issue about? Give as much detail as you can. 

Two people have tried to sent DAI to pay the membership dues, and they got different problems:

1. If you don't have gas, it "allows" you to pay, but it doesn't get reflected on the Score, unless you add the gas later.
![photo_2021-06-01 17.31.08.jpeg](https://images.zenhubusercontent.com/5fb59e0d956d0a522cd3101d/405f9216-31cb-46a1-bc2e-aabcf7ad1e88)
2. The second case could be related to the first case, but it's just a loop and that screen never changes no matter how many times she tries. 

![photo_2021-06-01 17.30.56.jpeg](https://images.zenhubusercontent.com/5fb59e0d956d0a522cd3101d/610fa075-a6ef-49ce-89ef-e38003c4a862)

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

##🧍🏻‍♀️🧍🏻‍♂️ Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@GriffGreen 

## 👀  Who should be in the loop about this issue?
@

**Comment by eduardovegap** [comment]
This issue belongs to the Swiss Membership repository, so I am moving it there.

**Comment by tamarandom** [comment]
Closing. Taken care of in the Swiss Mem dApp repo.
