### ISSUE TITLE
Follow TEC Hatchers, DAOs, and other token engineers

### ISSUE THREAD

**Issue by iviangita** [CommonsBuild/coordination#730]
## 👇🏽  What is this issue about? Give as much detail as you can. 

This is part of our strategy to increase Twitter engagement as we discussed in our last Twitter sync. 

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. Create a list of DAOs and token engineers who are on Twitter and start following them 
2. Follow TEC Hatchers who gave soft commits
3. Increase followers if they follow us back (this is also an increase in awareness and engagement)

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)

@chuygarcia92  

## 👀  Who should be in the loop about this issue?
@lEscanore

**Comment by lEscanore** [comment]
Create a list of DAOs and token engineers who are on Twitter and start following them (Done by lEscanore)
Follow TEC Hatchers who gave soft commits (Done by Ivi)
Increase followers if they follow us back (this is also an increase in awareness and engagement) (Done)

We will continue to follow Token engineers and DAOs, we already followed 33 Token Engineers from different projects and 16 DAOs. The list keeps growing
