### ISSUE TITLE
TEC Swag (assigned to acidlazzer)

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#735]
## 👇🏽  What is this issue about? Give as much detail as you can. 
We need swag. 
t-shirts, hats, coffee cups, frisbees? 

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. A special design Hatch t-shirts (that all Hatchers will receive free)
2. There are multiple swag products available for the ethCC conference in Paris (July 20-22) 
3. There is choice swag on the cross brand store 

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@chuygarcia92 @tamarandom  @GriffGreen

**Comment by tamarandom** [comment]
Hey @chuygarcia92! I'm assigning to you until acidlazzer is on github! 🙏🏼

**Comment by chuygarcia92** [comment]
The hatch swag is up and running!

https://swag.tecommons.org/#/
