### ISSUE TITLE
Hatcher Handbook

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#736]
(@eduardovegap - please make changes to this issue as you see this!)

## 👇🏽  What is this issue about? Give as much detail as you can. 
Parameters #83 won the vote! What does that mean from a Hatcher's POV? 

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. Article/post describing what the parameters mean for an individual Hatcher
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@GriffGreen @divine-comedian  @natenatesoo 

## 👀  Who should be in the loop about this issue?
@tamarandom @chuygarcia92

**Comment by tamarandom** [comment]
Added @natenatesoo to the advice process list!

**Comment by eduardovegap** [comment]
Document of reference (still work in progress): https://docs.google.com/document/d/19OYvbzJ9-UEVonCJGtFz2PCGSV1PhMxTfVFnS6EwvXc/edit

**Comment by tamarandom** [comment]
Update: check latest legal docs on the legal WG agenda.

**Comment by tamarandom** [comment]
@natenatesoo's progress https://docs.google.com/document/d/1suk07MBVMKPj9cQDeINC1G9nvE_8HL_HtzmL0iGS6lo/edit?usp=sharing

**Comment by natenatesoo** [comment]
Update: Comprehensive Version still in progress.

**Comment by tamarandom** [comment]
Awesome work! Closing!
