### ISSUE TITLE
Gitcoin Grants - Round 10! 

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#738]
## 👇🏽  What is this issue about? Give as much detail as you can. 
Round 10 of Gitcoin Grants are coming up:
June 16 - July 1 - proposed dates for Gitcoin Grants Round 10

Putting this on our radar for TEC and TEC affiliated groups that want to submit for grants in this round.

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. One or more Gitcoin grants are submitted from TEC/TEC-affiliated groups 
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@GriffGreen @jessicazartler @liviade1 @cranders1 

## 👀  Who should be in the loop about this issue?
@Everyone

**Comment by GriffGreen** [comment]
I will ask @sembrestels to redeploy the cv.commonsstack.org

**Comment by GriffGreen** [comment]
@sembrestels and at @geleeroyale are rockstars 

https://cv.commonsstack.org/#/ is deployed with a clean fresh dao, when we have the blog post we can change the "learn more" button too

:-D

**Comment by jessicazartler** [comment]
Commons Stack is coordinating here https://github.com/commons-stack/iteration0/issues/658
Had kickoff meeting today
Lead :
heater#9765

**Comment by tamarandom** [comment]
Update: Done!
