### ISSUE TITLE
Periodic orientations

### ISSUE THREAD

**Issue by danelsuga** [CommonsBuild/coordination#739]
## 👇🏽  What is this issue about? Give as much detail as you can. 
New-joiners need orientation on a variety of subjects concerning the TEC. We would like to implement periodic orientations for things like using GitHub for new contributors, how to find the appropriate documents (agendas and works in progress, etc.), how to navigate the community, who is doing what, etc. 

While the AMA can be useful (that needs separate modification tba), it cannot fulfill the role of really orienting new-joiners and giving them clarity, direction and purpose. Due to the nature of the design, the TEC in general needs more explaining (more orientation),* and a series of different projects such as this one could be implemented and trialed. 

*Regular new-joiner feedback. 

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. Stewards or other available contributors offer 15 minute orientations perhaps once a month. New-joiners find this information on the Orientation channel and sign up (or drop-in). 
2. Orientations may become regular ("TEC new contributors GitHub overview" once a month, etc.) or may be offered as needed/available. 
3. New-joiners will be integrated into the TEC with much more clarity, direction and speed and will be able to participate confidently and productively. 

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@tamarandom 
@liviade1 
@GriffGreen 

## 👀  Who should be in the loop about this issue?
@
Anna-Marie and I came up with this project. I will loop her in once she gets a GitHub orientation. ;)

**Comment by danelsuga** [comment]
@MrsBadgerface! I've found you! :D

After some advice process, Lívia offered the suggestion of doing short videos for these orientations to reduce unnecessarily repeated sessions. 

@tamarandom, would you be interested, for example, in providing a short video on how new-joiners can use zenhub (in particular to find issues for new contributors)?

Through new joiner feedback, I have found that github/zenhub is a bit of an impenetrable enigma for new joiners without some guidance.

**Comment by danelsuga** [comment]
@tamarandom - just an additional comment: of course I could do the zenhub/github video and/or all the possible orientation videos, and indeed as orientation coordinator, maybe I should be the one to start (as a university professor, I have a lot of experience in how to present as an educator); however, I am not a github/zenhub expert by any means! 

Your feedback is welcome. :)

My vision was also that stewards would jump in with their expertise on certain topics eventually as well. 

Some ideas include:

Zenhub
Discord
Praise
Tokenlog
Forum 
Ostrum
Gravity
TEC design (WG's and stewards)

**Comment by MrsBadgerface** [comment]
Hey @danelsuga Thank you for looping me in! I think short videos are an excellent idea. Yesterday, when I was trying to vote it wasn't working (it wouldn't let me vote), and one of the first things I did was to head to YouTube to see if there was a 'voting on tokenlog' video, to see if I was missing something obvious before asking for help. So! If there had been a short 'here's how to vote' video in some TEC orientation library, that would have been brilliant (there wasn't anything on YouTube).

**Comment by tamarandom** [comment]
Some backlog refinement, closing this epic.
