### ISSUE TITLE
Orientation: Using Zenhub in the TEC 

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#740]
## 👇🏽  What is this issue about? Give as much detail as you can. 
(specifics coming soon)

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@tamarandom 

## 👀  Who should be in the loop about this issue?
@

**Comment by danelsuga** [comment]
I have not had time for this yet.

**Comment by danelsuga** [comment]
Closing this issue, as active issue #778 discusses the same topic.
