### ISSUE TITLE
FAQ forum post for Orientation channel

### ISSUE THREAD

**Issue by danelsuga** [CommonsBuild/coordination#741]
## 👇🏽  What is this issue about? Give as much detail as you can. 
Implementing different useful activities on the Orientation channel to orient new joiners. This one will be writing a forum post full of FAQ's that can be used elsewhere but in particular the Orientation channel. 

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. The forum will become a centering point for new-joiners to find TEC information. Focus on the forum. And find answers on the forum. 
2. New-joiners will be engaged through the Orientation channel.  
3. 

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@tamarandom 
@liviade1

## 🔗  Are there links or docs related to this issue?
There will be a forum post that can be shared with new-joiners on the Orientation channel  

## 👀  Who should be in the loop about this issue?
@chuygarcia92 
@Vyvy-vi

**Comment by danelsuga** [comment]
I ended up editing a post by Jess for now and will continue to develop another one (and/or will edit a lot of the useful but older ones). 

https://forum.tecommons.org/t/5-how-to-join-contribute/98

**Comment by Vyvy-vi** [comment]
@danelsuga 
When we make that FAQ post, perhaps we could also mirror some contents from there to the Discourse FAQ page on the forum-
https://forum.tecommons.org/faq

**Comment by danelsuga** [comment]
Let’s do it! Thx, @Vyvy-vi.

**Comment by tamarandom** [comment]
This is being rolled into the new onboarding journey. Will be a #help FAQ channel with static content.
