### ISSUE TITLE
Creating rules for every platform

### ISSUE THREAD

**Issue by Zeptimus** [CommonsBuild/coordination#745]
## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.  To have a list of actions possible on our platforms to then inform our Code of Conduct 
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by Zeptimus** [comment]
We are meeting 1h every week https://docs.google.com/document/d/1hnwSQn4vxboxazraX2qPwa25bBBrvk3TpXsSDkXhqCM/edit

This last week we were working on YouTube, the idea its to get 1 platform every week and when we have them all, we start to work on the rules, but that would be something we should coordinate specially with cons since are going to be the ones using those platforms most of the time.

**Comment by natenatesoo** [comment]
Update: Still needs Hubspot, Medium, and Gitbook.  Finish this sprint.

**Comment by Zeptimus** [comment]
First draft done a week or 2 ago, legal its reviewing it now

**Comment by Zeptimus** [comment]
Done, already reviewed by legal and after review by softgov we will add to the Gitbook
