### ISSUE TITLE
Labs WG transparency audit

### ISSUE THREAD

**Issue by Zeptimus** [CommonsBuild/coordination#746]
## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by natenatesoo** [comment]
Update: Needs to collaborate with YGG.

**Comment by Zeptimus** [comment]
Close, we are proposing a new process for the audit.
