### ISSUE TITLE
Make progress on the Covenant 

### ISSUE THREAD

**Issue by liviade1** [CommonsBuild/coordination#748]
## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. work on the doc Shawn has started and have a draft for us to hack on the next legal call 
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by liviade1** [comment]
Hoping to have a draft to share this friday in legal

**Comment by tamarandom** [comment]
Hey @liviade1  I'm looking for a copy of the covenant. I found this link in the Legal agenda but don't have perms to open it. 

Is the draft something that can be shared publicly? 

https://docs.google.com/document/d/1inHqkkQuZzWQQhuq5A6sVwV0a3oQwfuDRv5nctYj8IE/edit#
