### ISSUE TITLE
Prepare ETH Paris presentation 

### ISSUE THREAD

**Issue by liviade1** [CommonsBuild/coordination#752]
## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by tamarandom** [comment]
Brain time given this sprint, usually during walks or washing the dishes.
