### ISSUE TITLE
Onboard a Product manager for Commons Swarm

### ISSUE THREAD

**Issue by GriffGreen** [CommonsBuild/coordination#758]
## 👇🏽  What is this issue about? Give as much detail as you can. 

We have a promising candidate :-D

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. Someone feels authorized to make it happen!
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by GriffGreen** [comment]
Got bradley going, still onboarding him to the payment process and all the things

He is doing one on one's but still hasn't taken on the board... I will close thiswhen he has taken on the board

**Comment by tamarandom** [comment]
Closing!
