### ISSUE TITLE
Post and debate proposals for IH analysis results

### ISSUE THREAD

**Issue by JuankBell** [CommonsBuild/coordination#759]
Post from a neutral the different strategies and prepare a voting process. 
We will use tokenlog for this vote.

## 👇🏽  What is this issue about? Give as much detail as you can. 
Decision taking on Ih analysis 

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. People is aware and informed of the different proposals to improve the IH distribution
2. The proposals are representative of multiple alternatives 
3. There is participation and recognition from the community to vote and debate.
4. Implementation of the proposal happens with good feelings.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@liviade1 @GriffGreen @tamarandom @Zeptimus @Jeff-Emmett @jessicazartler

**Comment by JuankBell** [comment]
15 closed issues after voting, https://github.com/CommonsBuild/IH-intervention/issues?q=is%3Aissue+is%3Aclosed


runoff posted by one person, and after the runoff the top 2 authors are invited to a hack session to merge their proposals together and commit to a collaborative result.

https://forum.tecommons.org/t/pre-hatch-impact-hours-distribution-analysis/376/50#what-if-there-is-a-polarized-scenario-where-2-different-proposals-have-an-evenly-split-majority-of-votes-in-the-run-off-8

**Comment by tamarandom** [comment]
Junkka says close.
