### ISSUE TITLE
Kickoff meeting with the TEC Scouts 

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#763]
@eduardovegap to update the details. 

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by eduardovegap** [comment]
I think we can close this one, and create new issues for the new action points.

The agenda for further reference is here: https://docs.google.com/document/d/18PKsdmm59GfQdqflpTIgO4aL-174xJIKQL2Gf__8aUw/edit

**Comment by tamarandom** [comment]
Done!
