### ISSUE TITLE
TOS, Policies and FAQs for TEC's forum

### ISSUE THREAD

**Issue by Vyvy-vi** [CommonsBuild/coordination#765]
## 👇🏽  What is this issue about? Give as much detail as you can. 
The [Terms Of Service(TOS)](https://forum.tecommons.org/tos) page and the [Frequently Asked Questions(FAQ)](https://forum.tecommons.org/faq) page on the Forum(https://forum.tecommons.org) are outdated, and hold the default content from Discourse. Perhaps this could use a tweak to better convey TEC's messaging.

Moreover, since the Forum might act as an Information Hub for the TEC, it would be probably great to have some TEC info like FAQ on the site. Also, the wording on the default forum FAQs/TOS are not compliant with the TEC(esp. since those were made with regard to companies, rather than a Commons or a DAO), and there might be some legal consideration here(?)

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. Having a specific and clearly made TOS(Terms Of Service), which is compliant with our MVV/Code Of Conduct/etc., as well as counts in general discourse TOS.
2. A better FAQ page, that actually answers stuff about the TEC, rather than the default Discourse FAQ page.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
(*I'm not 100% sure about who all should be consulted) - @Santigs @danelsuga @GriffGreen 

## 🔗  Are there links or docs related to this issue?
https://forum.tecommons.org/tos
https://forum.tecommons.org/faq

## 👀  Who should be in the loop about this issue?
@tamarandom

**Comment by tamarandom** [comment]
Closing old issues.
