### ISSUE TITLE
Forum Post: Disputable Conviction Voting

### ISSUE THREAD

**Issue by laurenluz** [CommonsBuild/coordination#766]
## What is this issue about?

Make forum post explaining:

- Conviction Growth (Voting Power Appreciation) 
- Relative Spending Limit
- Minimum Conviction(Minimum Threshold)

## 🔗  Are there links or docs related to this issue?
List of forum posts: https://docs.google.com/document/d/1Y2b5ZbiU405Efh4RYWx0Tm0F2ZAWqRgOWTbAmQOebDQ/edit
Starting draft post: https://docs.google.com/document/d/17DsZR8Ut-mru2YaOhJrRR3ehGwZBcg9v5Yn72_2vBWo/edit?usp=sharing

## 👀  Who should be in the loop about this issue?
@GriffGreen @divine-comedian @natenatesoo @chuygarcia92

**Comment by laurenluz** [comment]
Ok I wrote about:

- proposal deposit
- challenge deposit
- settlement offer
- settlement period

https://docs.google.com/document/d/17DsZR8Ut-mru2YaOhJrRR3ehGwZBcg9v5Yn72_2vBWo/edit

@divine-comedian @natenatesoo @GriffGreen - any of you wanna QA?

**Comment by divine-comedian** [comment]
put in some QA! 

I noticed there's lots of parenthesis, I suggested moving some into their own proper sentences. 

When you're comparing the high vs. low parameter values add in the cons and not just the pros for each end (if any), otherwise it feels a bit bias and not quite the whole picture.

**Comment by laurenluz** [comment]
Thanks @divine-comedian, I updated it based on your suggestions

**Comment by laurenluz** [comment]
New post on Spending Limit (formerly, Max Ratio/Beta) - ready for review @divine-comedian @natenatesoo @GriffGreen 

https://docs.google.com/document/d/1NIIXO0czLgMRtwSMIQK8J7jGUSazqwOAsjoGCsGN6Hw/edit#
