### ISSUE TITLE
Help? Could stewards or anyone: please update WG Forum pages

### ISSUE THREAD

**Issue by danelsuga** [CommonsBuild/coordination#767]
## 👇🏽  What is this issue about? Give as much detail as you can. 

Hi! I recently updated an orientation page on the Forum, which links to all the WGs and stewards. Could the stewards check their respective pages if they have a moment and make sure all's well? I'll have a pass too! Thank you. 

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. Updated individual WG pages on the forum
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@chuygarcia92 
@sembrestels 
@JuankBell 
@eduardovegap 
@tamarandom 
@Santigs 
@LinuxIsCool 
@solsista 
@GriffGreen 
@liviade1 
@iviangita 
@Zeptimus 

## 🔗  Are there links or docs related to this issue?

https://forum.tecommons.org/t/how-to-join-contribute/98

Comms
https://forum.tecommons.org/t/comms-working-group/162

Commons Swarm
https://forum.tecommons.org/t/gardens-swarm-working-group/159

Gravity WG
https://forum.tecommons.org/t/gravity-working-group/177

Hatcher Outreach WG
https://forum.tecommons.org/t/onboarding-working-group/166

Labs WG
https://forum.tecommons.org/t/labs-working-group/410

Legal WG
https://forum.tecommons.org/t/legal-working-group/178

0mega
https://forum.tecommons.org/t/mega-working-group/334

Params WG
https://forum.tecommons.org/t/tec-parameters/185

Soft Gov WG
https://forum.tecommons.org/t/soft-gov-working-group/163

Stewards WG
https://forum.tecommons.org/t/community-stewards-wg/260

Transparency WG
https://forum.tecommons.org/t/transparency-working-group/197

## 👀  Who should be in the loop about this issue?
@chuygarcia92 
@sembrestels 
@JuankBell 
@eduardovegap 
@tamarandom 
@LinuxIsCool 
@Santigs 
@solsista 
@GriffGreen 
@liviade1 
@iviangita 
@Zeptimus

**Comment by danelsuga** [comment]
Comms
https://forum.tecommons.org/t/comms-working-group/162

Commons Swarm
https://forum.tecommons.org/t/gardens-swarm-working-group/159

Gravity WG
https://forum.tecommons.org/t/gravity-working-group/177

Hatcher Outreach WG
https://forum.tecommons.org/t/onboarding-working-group/166

Labs WG
https://forum.tecommons.org/t/labs-working-group/410

Legal WG
https://forum.tecommons.org/t/legal-working-group/178

0mega
https://forum.tecommons.org/t/mega-working-group/334

Params WG 
https://forum.tecommons.org/t/tec-parameters/185

Soft Gov WG
https://forum.tecommons.org/t/soft-gov-working-group/163

Stewards WG
https://forum.tecommons.org/t/community-stewards-wg/260

Transparency WG
https://forum.tecommons.org/t/transparency-working-group/197

**Comment by eduardovegap** [comment]
Done! Thanks Suga!

**Comment by Santigs** [comment]
Hey Suga, @santigs is my Twitter handle, the telegram one is @Santigs67.
Not sure what you wanted to add in the post.
Content is fine for legal
Thank you!

**Comment by danelsuga** [comment]
Thanks, @Santigs   
I just wanted to make sure each page was up to date since some things have changed since first posted.

**Comment by tamarandom** [comment]
I really liked the phrasing made for the Youtube WG list .... it feels more up to date than the ones here. Any reason not to use those?

**Comment by danelsuga** [comment]
I can change those. 

The purpose of this issue was just to see if any of the details needed updating (call times, contact info, etc.). 

Thanks!

**Comment by tamarandom** [comment]
@danelsuga is this done?

**Comment by danelsuga** [comment]
Yes.
