### ISSUE TITLE
Community sync livestream URL 

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#770]
## 👇🏽  What is this issue about? Give as much detail as you can. 
When the Community Sync call is full, people are not able to enter. @GriffGreen mentioned we could/do have a way to livestream but I wasn't able to find the URL! 

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.  People who are not able to get into the Community Sync call know where to go to watch it in livestream
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@Vyvy-vi @GriffGreen 

## 👀  Who should be in the loop about this issue?
@Zeptimus

**Comment by Zeptimus** [comment]
I was not streaming just recording to be more safe  on the praise if internet fails on the uploads (and i still fucked it up :/). I think one solution would be have someone recording it and i could stream it. Norally everything will go well but if something fails on the stream have a back up i feel its important for this call, specially for ivy to dish the praise.

**Comment by Zeptimus** [comment]
@JuankBell @LinuxIsCool @Vyvy-vi @chuygarcia92 Anyone would like to take responsibility for the backup? 🙏🙏

**Comment by Vyvy-vi** [comment]
I think for the praise backup, using the audio recorder bot might be a good backup(It should work in most cases, with the relevant praise)

**Comment by Zeptimus** [comment]
I still think a second recorder would be the best, PAWA takes one slot on the call and don't get the video which Ivy uses for the praise attendance. I could also stream and record but i still think having someone backing it up would save some trouble normally i wont miss it but for example today i literally got distracted and didnt press record until we finish praise and i look to OBS for the timesamp and saw it was not recording it felt very bad :(

**Comment by natenatesoo** [comment]
Update: Needs Confirmation.  Explore YouTube options.

@Zeptimus 
@Vyvy-vi 
@chuygarcia92 
@JuankBell

**Comment by Zeptimus** [comment]
Done! https://www.youtube.com/c/TokenEngineeringCommons this is our new URL and also added a slide on the c.call presentation
