### ISSUE TITLE
Removing the Hatch AMA weekly call 

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#771]
## 👇🏽  What is this issue about? Give as much detail as you can. 
Deleted from the calendar but now what? 

- Twitter (@iviagita)
- Discord call announce bot @vyvy-vi)

Where else?

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. There aren't places where the cancelled Hatch AMA call is still being brodcast 
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by Vyvy-vi** [comment]
The hatch-ama call reminder has been removed :+1:

**Comment by tamarandom** [comment]
That was fast! Exellent!

**Comment by eduardovegap** [comment]
Done.
