### ISSUE TITLE
Create Manifesto for TEC Scouts. 

### ISSUE THREAD

**Issue by eduardovegap** [CommonsBuild/coordination#772]
## 👇🏽  What is this issue about? Give as much detail as you can. 
We need to layout a draft for the Manifesto of the Scouts, that outlines: mission, vision, short / mid term objectives and goals. 

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. Having a Manifesto for next sprint. 
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@chuygarcia92 @tamarandom 

## 🔗  Are there links or docs related to this issue?

The agenda has some key points of reference: https://docs.google.com/document/d/18PKsdmm59GfQdqflpTIgO4aL-174xJIKQL2Gf__8aUw/edit

## 👀  Who should be in the loop about this issue?
@

**Comment by eduardovegap** [comment]
Working document: https://docs.google.com/document/d/1APB06u7WpbjPjTN6ovLyyfyuBkWEYvG8ou807cNqKCM/edit#

**Comment by natenatesoo** [comment]
Update: Review the Manifesto, but it is completed. Follow WG creation process.
