### ISSUE TITLE
integrate feedback in the covenant 

### ISSUE THREAD

**Issue by liviade1** [CommonsBuild/coordination#776]
## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by natenatesoo** [comment]
Update: Review for the proposal.  Adding Transparency Links.
