### ISSUE TITLE
Video: Coordination in the TEC

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#778]
## 👇🏽  What is this issue about? Give as much detail as you can. 
Linked to #740 

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. People new to the TEC know the basics of using Zenhub and can quickly jump in
2. There exists instructions on how we use use Zenhub in the TEC
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@Zeptimus @danelsuga 

## 👀  Who should be in the loop about this issue?
@

**Comment by natenatesoo** [comment]
Update: Very Important!  Possibly having a video tutorial of the Zenhub Board and related mechanics.

**Comment by danelsuga** [comment]
@tamarandom has been doing a couple Zenhub onboarding calls. One thought has been to record one of those as a future tutorial. My feeling is that running it cleanly and concisely without an audience would be best.

**Comment by tamarandom** [comment]
Practicing the content in the live "TEC Coordination" sessions. There are still some kinks to work out.

**Comment by natenatesoo** [comment]
@tamarandom This seems like it should be an epic.  I will work on developing one with the current outline within this issue.  I will keep this issue in the Product Backlog, and develop an epic.

Thanks!

**Comment by tamarandom** [comment]
Coordination will change based on the Steward WG transformation. Closing this issue!
