### ISSUE TITLE
Hatch 1st day outreach campaign 

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#782]
## 👇🏽  What is this issue about? Give as much detail as you can. 
When we Hatch - it's time to tell all the people we've talked to. 

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. messaging for the 1st day of Hatch (1st week!)
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@eduardovegap

**Comment by tamarandom** [comment]
This will be the Hatch Checklist + Params as they relate to a Hatcher with a personal message! 
We will use the IH + curate list.

**Comment by natenatesoo** [comment]
Update: Few people remaining, searching for usernames.  Dan is finding usernames for those who are remaining.  90%

**Comment by eduardovegap** [comment]
MISSION ACCOMPLISHED!

**Comment by tamarandom** [comment]
🤸  🤸  🤸
