### ISSUE TITLE
Comms Hatch campaign plan 

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#783]
## 👇🏽  What is this issue about? Give as much detail as you can. 
For the specific Hatch comms related to Hatch 

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. Media planner for the hatch capaign
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by tamarandom** [comment]
@chuygarcia92 will post the campaign plan and close this issue!

**Comment by chuygarcia92** [comment]
Still a WIP but @acidlazzer will be working in an improved and updated design. 

![Hatch-July-21-Calendar_01.jpg](https://images.zenhubusercontent.com/6000e68bc28f519103606a04/efb03772-0ce0-4e22-95c1-4824f3650182)
