### ISSUE TITLE
Nuggan making a POAP for Hatchers

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#785]
(by Nuggan)
## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by natenatesoo** [comment]
Update: Nuggan working oni it.  Perhaps collaborate with Juan and Gravity POAP.

**Comment by tamarandom** [comment]
We have the POAP for Hatchers. There might be a second one done by Nuggan. @GriffGreen will check with Nuggan.

**Comment by chuygarcia92** [comment]
Nuggan made the POAP:
https://poap.delivery/hatch-tech-holder
