### ISSUE TITLE
SWAGTEC airdrop logistics 

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#792]
## 👇🏽  What is this issue about? Give as much detail as you can. 
Can the Hatch dApp airdrop SWAGTEC at the time of funding?
---> @GriffGreen @sembrestels 
if not, work out manual process for this (where to get the addresses, contact info, etc)
Way to check only 1 T is sent per address (even if multiple sends to the Hatch)
Is there a minimum required (e.g., > 20 wxdai) or not?

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. Answers to above questions rolled up into an airdrop plan 
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@GriffGreen @sembrestels @iviangita @tamarandom 

## 👀  Who should be in the loop about this issue?
@

**Comment by tamarandom** [comment]
@iviangita and I jotted down some requirements and open questions about this: 

SWAGTEC Airdrop 

Requirements
-No more than 1 token should be sent to each address, regardless of the amount. So multiple fundings will not result in multiple airdrops to the same address.
-There is no minimum fund requirements. (So if someone funds only $1, we still send them the shirt even though it would be at a loss to us. The reason is that we don’t think with the Trusted Seed being the only Hatchers, this is a big risk for us).
-As a Hatcher, I want to be informed of how to collect my swag. 

Open questions:
-Can this be done automatically via the Hatch app redirecting to the swag shop after the funding is complete?
-If not, Will be able to generate a csv report like the one from Giveth dApp?

**Comment by sembrestels** [comment]
Just talked with @iviangita. Changing the hatch app now is out of the scope for us, so I would suggest going the traditional manual way of sending SWAGTEC tokens using disperse.app.

The hatch contract transactions can be monitored and once a week collect the addresses that have minted TECH tokens. This can be done using [blockscout itself](https://blockscout.com/xdai/mainnet/csv-export?address=0xB14D3da084Ab02b9C3b52974b03B4079d706a4E9&type=transactions) (use 2021-06-02 to 2021-06-06 for this example, as this is the hatch dress rehearsal address). The `FromAddress` field contain the baker addresses, and `UnixTimestamp` the date. Duplicates should be managed so SWAGTEC is not sent multiple times.

**Comment by tamarandom** [comment]
Thanks @sembrestels. That's what we thought and this csv solution will work. It's only 30 days!

**Comment by iviangita** [comment]
Here's the updated link of data source from @sembrestels :) 

https://blockscout.com/xdai/mainnet/csv-export?address=0xda58e84fdea0e5d11c380e78888e3239761b4a61&type=transactions

**Comment by iviangita** [comment]
CLOSING!

Here's the airdrop tracker: https://docs.google.com/spreadsheets/d/1G5srPuTKHLnFa0CGUmGBVrm47hRCQeZfMFGaErHn7cs/edit?usp=sharing
