### ISSUE TITLE
Do an audit on the credentials management

### ISSUE THREAD

**Issue by Zeptimus** [CommonsBuild/coordination#797]
## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by iviangita** [comment]
Happening on Thursday, Aug 5, 3pm CET

**Comment by Zeptimus** [comment]
Done!

**Comment by Zeptimus** [comment]
Done!
