### ISSUE TITLE
Privacy policy Doc

### ISSUE THREAD

**Issue by Zeptimus** [CommonsBuild/coordination#798]
## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by GriffGreen** [comment]
Just make sure we get something up on the gitbook before the Hatch... even if its not done completely

**Comment by Zeptimus** [comment]
Here we have a first draft https://docs.google.com/document/d/1x0wpkV2i6FFBw7w7qNJCH6n49zKtQK0J1jOJS9Jgwd4/edit

**Comment by Zeptimus** [comment]
Closing, one step close to hatch :D https://app.gitbook.com/@token-engineering-commons/s/tec-handbook/hatch-101/privacy-policy
