### ISSUE TITLE
Hatch Terms final edits, put in the Gitbook, make PDF, pass to Commons Swarm

### ISSUE THREAD

**Issue by GriffGreen** [CommonsBuild/coordination#800]
## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by GriffGreen** [comment]
Complete on my end.... but waiting for confirmation that Vitor has added it.

**Comment by tamarandom** [comment]
Hi @marthendalnunes! Has these final Hatch Terms been added to gitbook and the dApp?

**Comment by tamarandom** [comment]
Update: closing
