### ISSUE TITLE
Bringing TEC Lounge to other communities! 

### ISSUE THREAD

**Issue by eduardovegap** [CommonsBuild/coordination#802]
## 👇🏽  What is this issue about? Give as much detail as you can. 
We have done our first test doing a lounge at Metagame. Next ones are: 1HIVE and a pick from the Highlights previously showcased on the community call.

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. One more test.
2. Having a list and contacts to the nexts lounges.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@natenatesoo @chuygarcia92 @laurenluz 

## 🔗  Are there links or docs related to this issue?
https://www.youtube.com/watch?app=desktop&v=JlnzXAmQ5NQ&ab_channel=TokenEngineeringCommons

## 👀  Who should be in the loop about this issue?
@

**Comment by natenatesoo** [comment]
Update: Identify new communities to create new lounge space.

**Comment by eduardovegap** [comment]
We are going to add the new targets from highlights to the TEC Curate: https://docs.google.com/spreadsheets/d/1RJK8gPqUoRfehX9e60sTCMAM_R1rI2CuiV1r-i3wAXQ/edit#gid=755600565

cc: @natenatesoo

**Comment by eduardovegap** [comment]
So, we are trying to evolve the idea of the TEC Scouts. @Vyvy-vi proposed the idea of doing the TEC lounge through twitter spaces, and @chuygarcia92 added to the agenda for the next week agenda, to improve it.

**Comment by chuygarcia92** [comment]
I feel this issue can be solved with the "Social Fridays" idea, where the TEC, Metagame and 1Hive will promote the same content inviting newcomers to the DAO space to engage with these 3 communities on Fridays.
I'll be working with Metagame's and 1Hive's Comms contributors to put this together hopefully for next week.

**Comment by tamarandom** [comment]
Update: @eduardovegap has something that might be scheduled for the 27 Oct.

**Comment by eduardovegap** [comment]
After we launched, we could think on retake this.

**Comment by mount-manu** [comment]
**Edu update:** Didn't happen; won't happen...so we close.
