### ISSUE TITLE
Second Graviton training!

### ISSUE THREAD

**Issue by JuankBell** [CommonsBuild/coordination#803]
## 👇🏽  What is this issue about? Give as much detail as you can. 

We are going to start the second graviton training in september! 

This document will be used to design the sessions and the study plan that we are going to be following.
https://docs.google.com/document/d/1txyn1dND8xG_ofNG_rxRzvNuBfGl3j20w9Au5N8kq0E/edit?usp=sharing

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. Engage facilitators: @liviade1 @ddan4 @durgadas @mount-manu @JuankBell 
2. Set exact dates for the training.
3.  Communicating the training within the DAO ecosystem (promoting online and in ETHCC) and making visual pieces for the content (Graviton how-to documents)

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@GriffGreen 

## 👀  Who should be in the loop about this issue?
@tamarandom

**Comment by natenatesoo** [comment]
Update: Finish the studying plan.  Will have 3 syncs with facilitators.

**Comment by natenatesoo** [comment]
Good Job! Second Gen Gravitons!
