### ISSUE TITLE
TEC Unconference Planning

### ISSUE THREAD

**Issue by GriffGreen** [CommonsBuild/coordination#807]
## 👇🏽  What is this issue about? Give as much detail as you can. 
In Paris, we need to have a TEC Post Hatch Sense Making Planning Sesh with all of us there!

Prob on the 24th :-(

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by chuygarcia92** [comment]
The name of the place we're looking at for making this happen is Le Grand Breguet and the address is 17 Rue Breguet, 75011.

We still haven't confirmed with the manager but Julie is expecting an answer tomorrow.
