### ISSUE TITLE
Praise system development 

### ISSUE THREAD

**Issue by liviade1** [CommonsBuild/coordination#810]
## 👇🏽  What is this issue about? Give as much detail as you can. 

We have gathered many insights from the IH intervention process. Which ones do we want to incorporate moving forward? 

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. Improve quantification process - what can be automated? What is important to remain manual? 
2. Praise guidelines for producing clean data sets - should we have a praise onboarding and a couple of rules for how to praise? Do we want to have categories?
3. How is the praise going to be distributed? One proposal to the DAO that sends funds to the SourceCred DAO for distribution? 

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by natenatesoo** [comment]
Update: Onboarding Octopus and other data scientists.

**Comment by tamarandom** [comment]
Shawn can bring this to the labs in early Sept.

**Comment by tamarandom** [comment]
Suggestion: loop in rdfbx (I'm sure I have his handle wrong, sorry!)
