### ISSUE TITLE
Communicate meeting free week at the TEC July 19-23

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#811]
## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by Vyvy-vi** [comment]
I think this can be closed now.

**Comment by chuygarcia92** [comment]
Done.
