### ISSUE TITLE
TEC stickers 

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#812]
## 👇🏽  What is this issue about? Give as much detail as you can. 
stickers? too late? 
Can Julie print them in Paris. 

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by chuygarcia92** [comment]
The DAOist TG group shared these local printing contacts and notes:

- https://www.panopli.co/ 
- https://kymono.co/ (they are not as qualitative as the first one)
- https://imprimeriedumarais.com/ (most expensive and a true printer, the other ones are more startup-focused)

We'll check in with them to get some quotes.

**Comment by chuygarcia92** [comment]
The stickers are done and already rocking most stewards laptops (I hope)
