### ISSUE TITLE
Create a Card preview for the Hatch.tecommons.org site

### ISSUE THREAD

**Issue by GriffGreen** [CommonsBuild/coordination#815]
![photo_2021-07-20_01-20-10](https://user-images.githubusercontent.com/14945613/126239604-f19c45f9-9f7d-42b3-85b9-5afa785643e7.jpg)

<img width="475" alt="Screen Shot 2021-07-20 at 1 20 22 AM" src="https://user-images.githubusercontent.com/14945613/126239617-ea1b1429-4732-431b-aec6-8da8a82101fe.png">

I'm not sure who should take this on... but we need a picture and some text that will autogenerate when the hatch page link i put in a tweet or in telegram!

**Comment by markoprljic** [comment]
Please use any image from TEC Marketing resources. For text, I'm not the most qualified person to provide that :)
https://www.figma.com/file/kyXvCY9ttgQEtsLyzSnu16/TEC-Marketing?node-id=0%3A1

**Comment by Vyvy-vi** [comment]
I can work on this :)

**Comment by Vyvy-vi** [comment]
![Screenshot 2021-07-21 at 7 23 01 PM](https://user-images.githubusercontent.com/62864373/126500283-2c121655-1ddc-4f7f-a994-58c730b27ffe.png)
![Screenshot 2021-07-21 at 7 14 30 PM](https://user-images.githubusercontent.com/62864373/126500288-45b8ef25-3aa9-40ed-92e6-249a1fb0397b.png)
![Screenshot 2021-07-21 at 6 39 49 PM](https://user-images.githubusercontent.com/62864373/126500293-d125d870-2126-486d-9ade-131e484c8c9f.png)
![Screenshot 2021-07-21 at 6 34 10 PM](https://user-images.githubusercontent.com/62864373/126500301-4d06f0d3-f7af-43e8-8e65-91d1a6202aa4.png)

Which one of these four looks the best? Also, what would be the recommended text for this?

**Comment by markoprljic** [comment]
Thanks @Vyvy-vi 
I think the blue one is te winner :)

**Comment by Vyvy-vi** [comment]
Hmm, it looks neat :)

I'm wondering what would be the best text possible for the description?

**Comment by Vyvy-vi** [comment]
I opened a PR with the needed changes -  https://github.com/CommonsSwarm/tec-hatch/pull/119

(Once that gets merged and te frontend gets rebuilt, we should have the cards showing up)

**Comment by Vyvy-vi** [comment]
Closed by `2df2034`

**Comment by Vyvy-vi** [comment]
Yaay! We have Card previews now 🎉
