### ISSUE TITLE
Best practices of the advice process

### ISSUE THREAD

**Issue by iviangita** [CommonsBuild/coordination#818]
## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by liviade1** [comment]
Let's sync on this  we are working on advice process as well for the decision making flow

**Comment by Zeptimus** [comment]
its been on the product backlog for some time now, there are not updates at all i feel if you are looking at it   i could take support role and give feedback if needed
