### ISSUE TITLE
Topics that need the Advice Process

### ISSUE THREAD

**Issue by iviangita** [CommonsBuild/coordination#819]
## 👇🏽  What is this issue about? Give as much detail as you can. 
We'd like to increase the engagement of the community members in our Advice Process, especially in our forum. Here are the things that can be done as suggested by @JuankBell, who's taking this on as well. Thanks Juan!

[ ] Make a list of topics that need the advice process
[ ] Make a slide on the community call 

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.  More engagement in the advice process
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@Zeptimus 

## 👀  Who should be in the loop about this issue?
@iviangita

**Comment by JuankBell** [comment]
Slide was made under the transparency part of the community call :)

![Captura de Pantalla 2021-08-06 a la(s) 6.44.55 p. m..png](https://images.zenhubusercontent.com/5fb57c9c5472cf79e80e7f7e/bd108b63-815c-4612-8c09-e3e376b4c501)
