### ISSUE TITLE
Run a Community Currency Potluck

### ISSUE THREAD

**Issue by cranders1** [CommonsBuild/coordination#82]
## 📋 Anything to add?

🍞  Organize and lead a Community Currency Potluck 🍯 

## ⏰ Urgency/Due Date/Blockers?

**URGENCY**: Medium
**DUE DATE**: Dec 10 or pre-holidays
**BLOCKERS**: Covid

## ❓ Why is it important?

Sharing personal experiences and quality time with like minded individuals is the crux to any community. Eat Drink Build regenerative economies.

## 🎉 Subtasks

- [ ] Find a Champion 🙏 
- [ ] Research
- [ ] Organize and ask for help
- [ ] Pull it off

## 🤼‍ Reviewer

@

## 🔗 Work doc - inspirational links
[Grassroots Economics: How to Host a Community Currency Potluck](https://www.grassrootseconomics.org/post/how-to-host-a-currency-potluck)

**Comment by jessicazartler** [comment]
@GriffGreen do we still need this issue or what is this?
@tamarandom CCing

**Comment by cranders1** [comment]
This came from the original OWG manifesto that I inherited as a potential activity/issue. It could be left indefinitely or simply removed.

**Comment by tamarandom** [comment]
Hey @jessicazartler and @cranders1 is the scope of this coordinate all community currency initiatives into a single feel-good meeting? I think it's a great idea but a lot of time consuming coordination work. I can see leaving it here as "For Contributors" and low priority in case an enthusiastic contributor wants to take this and run with it. Make sense?

**Comment by jessicazartler** [comment]
Yes, this was an issue that Griff had written, that is why I was asking above if he had some vision for this that was needed -- it is a cool exercise, but it would be a whole thing in itself that I don't think is critical for the hatch -- maybe also if he wanted it done to write directions or intended outcomes/purpose so a contributor could take it on. Thanks Tam!

**Comment by GriffGreen** [comment]
yeah, we can close it, or leave it for contributors I would let @cranders1 decide.

This was an idea Sebnem had, but it was too early when she was pushing it. 

I think we are doing the potluck work now in onboarding... talking to Proposals (and we should follow up with them when we can give some next steps for the Hatch) and talking to hatchers and asking them if they want to make a proposal... 

So I wouldn't put time in this issue unless Sebnem or Craig had more vision for it

**Comment by cranders1** [comment]
If there's no downside to leaving it open, then let's just leave it for a potential suitor. 
But happy to close it up to tidy the space ;)

**Comment by tamarandom** [comment]
Backlog refinement! 

It's been 7 months. Closing. If there is a new idea for social cohesion a new issue for that would be very welcome!

**Comment by cranders1** [comment]
thnx @tamarandom
