### ISSUE TITLE
Draft Soft Gov WG funding proposal

### ISSUE THREAD

**Issue by liviade1** [CommonsBuild/coordination#821]
## 👇🏽  What is this issue about? Give as much detail as you can. 

What should Soft Gov request funding for once the Commons is live? 
What are the small projects that can be developed?
Who will be working on each one of them? 
What is a fair funding? 
How will the funds be managed between contributors?

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by natenatesoo** [comment]
Update: Looking for collaborators.

**Comment by tamarandom** [comment]
Soft Gov will be using Rewards System & request funding for special projects via CV.
