### ISSUE TITLE
Reward Systems - what is the figure that the reward system will need?

### ISSUE THREAD

**Issue by liviade1** [CommonsBuild/coordination#822]
## 👇🏽  What is this issue about? Give as much detail as you can. 
Part of this (or all?) can be allocated via the initial buy-in. The rest would be a proposal to CV. 

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. A number denominated in TEC tokens 
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 🔗  Are there links or docs related to this issue?
https://forum.1hive.org/t/pollen-distribution-period-starting-july-20th/4168?u=chuygarcia92 

## 👀  Who should be in the loop about this issue?
@

**Comment by natenatesoo** [comment]
Update: Looking for Collaborators for this issue.

**Comment by liviade1** [comment]
"80,000 wxDAI (32%) worth of TEC will go directly to fund the distributions of the reward system and the management of those funds will be set by the Reward Board." according to the initial buy in proposal
