### ISSUE TITLE
Transparency on Discord Tags/Roles

### ISSUE THREAD

**Issue by iviangita** [CommonsBuild/coordination#824]
## 👇🏽  What is this issue about? Give as much detail as you can. 

Discord tags/labels on individual accounts are important in some certain tasks, especially to establish credibility and trust. We're hoping we can have a more transparent process on giving these Discord roles/tags to the community members who are actively contributing in TEC and it's clear to community members the functions of these roles/tags.

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. A documented and transparent process of giving Discord tags/roles to community members
2. Discord roles/tags are clearly described
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@Zeptimus @iviangita 

## 🔗  Are there links or docs related to this issue?
Working document: https://docs.google.com/document/d/1el7GdOZwqTTTYb3Es-tzR6e9uNb_KRTe1t7MGQ9JTPY/edit?usp=sharing

## 👀  Who should be in the loop about this issue?
@

**Comment by iviangita** [comment]
Will assign this to Zer8 once he accepts the invitation to edit on this workspace

**Comment by Zeptimus** [comment]
We have a first draft https://docs.google.com/document/d/1el7GdOZwqTTTYb3Es-tzR6e9uNb_KRTe1t7MGQ9JTPY/edit

**Comment by Zeptimus** [comment]
Closing https://forum.tecommons.org/t/tec-discord-roles/581
