### ISSUE TITLE
TEC content ownership

### ISSUE THREAD

**Issue by Santigs** [CommonsBuild/coordination#827]
## 👇🏽  What is this issue about? Give as much detail as you can. 
Discuss best way to choose and assign a proxy to act on behalf of TEC in the event of content conflicts

To be included in Gitbook

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by teresacd11** [comment]
**What does success look like?** 
1.	Having an Agreement with contributors where this is stablished and is fair for both parties.
2.	Having it signed by all current contributors.
3.	Having it updated to new contributors. 

**Who should be part of the Advice Process?** 
Gravity for conflict resolution, Legal 

**Are there links or docs related to this issue?**
https://github.com/CommonsBuild/tec-handbook/blob/main/tec-agreements-1/code-of-conduct.md
https://github.com/CommonsBuild/tec-handbook/blob/main/hatch-101/legal.md
https://github.com/CommonsBuild/tec-branding-assets/blob/main/LICENSE

**Comment by teresacd11** [comment]
Here is the draft: https://docs.google.com/document/d/1-K1BalVCcLe9sz8Dl6ASGkdsrWw_eSu8/edit#

**Comment by teresacd11** [comment]
Pending for final review in case someone has any other notes + implementation in Discord and Covenant. @iviangita 
Notes where added by @Boonjue and reviewed.

**Comment by iviangita** [comment]
Thanks @teresacd11! I reviewed the document and I have no additional changes. I'm trying to find the Discord message that people sign when they join the server so we can integrate this document there. I'll give updates once I have it. Aside from Discord, we can also add this agreement to Gitbook.

**Comment by iviangita** [comment]
I submitted this content to TEC Gitbook - pending review from admin

**Comment by mount-manu** [comment]
Teresa completed this ([and it's live](https://token-engineering-commons.gitbook.io/tec-handbook/tec-agreements-1/content-ownership-agreement)) so I'm closing it now.
