### ISSUE TITLE
Write a new blog post for Gravity, promoting the next Graviton training

### ISSUE THREAD

**Issue by JuankBell** [CommonsBuild/coordination#828]
![gravity_invitation.jpeg](https://images.zenhubusercontent.com/5fb57c9c5472cf79e80e7f7e/7d4572a5-ad08-42ac-924b-3695e98fb557)

## 👇🏽  What is this issue about? Give as much detail as you can. 

We will have the second Graviton training in September, and to promote it, we want to write a new blog post inviting people to participate and share some of the progress that we have had in this last months. :)

We will be working in this document.
https://docs.google.com/document/d/1Q01vBGdLdxkMqBoezRS0Ej0xP7D6MbLtZ15qqS1GLwQ/edit

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. Lot of engagement from contributors coming from diverse Communities
2. A great blog post to share that explains the goals of gravity and its training!

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)

@liviade1 @mount-manu @durgadas @anna-Marie @ddan4 

## 🔗  Are there links or docs related to this issue?

https://docs.google.com/document/d/1Q01vBGdLdxkMqBoezRS0Ej0xP7D6MbLtZ15qqS1GLwQ/edit

## 👀  Who should be in the loop about this issue?
@GriffGreen

**Comment by natenatesoo** [comment]
Update: New Blog post to be distributed with the help of Durgadas.

**Comment by JuankBell** [comment]
Post published! https://medium.com/token-engineering-commons/graviton-training-season-2-8f9817cf404d
