### ISSUE TITLE
Making the POAPs for the Graviton training

### ISSUE THREAD

**Issue by JuankBell** [CommonsBuild/coordination#832]
## 👇🏽  What is this issue about? Give as much detail as you can. 
make the POAPs that will be used to certify the participation in the graviton trainings and the people that will become gravitons 

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. have 10 POAPs to deliver to participants of the training https://app.poap.xyz/admin/events
2. Make a design with small changes for each POAP
3. Have a good system to deliver the POAPs (bot integration on Discord and easy step by step)

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@mount-manu @Zeptimus @JuankBell 

## 🔗  Are there links or docs related to this issue?
https://app.poap.xyz/admin/events

## 👀  Who should be in the loop about this issue?
@liviade1

**Comment by Michael-A-Heuer** [comment]
I would like to work on this issue.
I am POAP collector myself and I also want to learn how to use them for my project.

**Comment by heueristik** [comment]
**Steps to finish:**
- [x] creating the POAP events
- To see the events go to the [POAP event page](https://app.poap.xyz/admin/events/) and search for `Graviton Session`. For the POAP edit codes ask me or request access to the *Graviton Session POAPs GoogleSheet*
- [x] [invite the POAP bot to the TEC discord](https://discord.com/api/oauth2/authorize?client_id=764554729476194315&permissions=2112&scope=bot) (requires admin rights to the discord server)
- [x] [configure the POAP bot for the individual events](https://github.com/poapxyz/poap-bot#configuring-the-poap-bot-for-an-event-setup-bot) by uploading the claim codes (currently kept by me)

The POAP bot installation and configuration is described [here](https://github.com/poapxyz/poap-bot).

**Comment by Zeptimus** [comment]
We should only have 1 person assaign as point of contact this job its being done well ill remove myself as assigne, but if there is any help needed just DM me or tag me here

**Comment by JuankBell** [comment]
POAP bot working and set for the first session! Thanks @Vyvy-vi and @Michael-A-Heuer

**Comment by Michael-A-Heuer** [comment]
Better remove the image above @JuankBell ^^. 
You are leaking the first secret and some claim codes.

**Comment by JuankBell** [comment]
POAPs ready! 
Closing issue: next repeating task is feeding the bot with each week's password and link list. 
![Captura de Pantalla 2021-09-17 a la(s) 10.47.13 a. m..png](https://images.zenhubusercontent.com/5fb57c9c5472cf79e80e7f7e/1e7b7548-b71b-47f1-a70c-a44ad26927c7)
