### ISSUE TITLE
Outreach for SWAG. 

### ISSUE THREAD

**Issue by eduardovegap** [CommonsBuild/coordination#837]
## 👇🏽  What is this issue about? Give as much detail as you can. 
@iviangita requested help outreaching people who have funded the TEC HATCH by letting them know that they can claim their SWAG. 

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. Sent message to everyone who has sent funds.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by iviangita** [comment]
Linked to [816](https://app.zenhub.com/workspaces/tec-coordination-workspace-5fad0d3fbbe4da0011c2f40d/issues/commonsbuild/coordination/816)

**Comment by tamarandom** [comment]
@iviangita @eduardovegap : do you feel that this outreach has been done? Can we close this now?

**Comment by iviangita** [comment]
Yes this can be closed. We will also follow up with Comms team on the status of Hubspot so we can send a Hatch Swag reminder via email as well. 

cc: @eduardovegap
