### ISSUE TITLE
Translation of TEC articles/documents

### ISSUE THREAD

**Issue by iviangita** [CommonsBuild/coordination#839]
## 👇🏽  What is this issue about? Give as much detail as you can. 
Having our TEC articles translated into international languages will help us push our mission forward in different corners of the world and welcome more members to our community. Some contributors have already reached out to offer their time and skills to help with the translation and introduce the TEC to their parts of the world.

We need to coordinate these efforts, establish a process around the translations, and get these things organized. Here are the initial concerns that we have to think about and discuss:

- What articles/documents do we want to translate?
- What priority languages do we want to translate them to? Who are the contributors available to do the translation? Here are the contributors who already have shown interest in supporting this work:
_Chinese - Shawn
Turkish - Alp
Spanish - Juanka, Manu
Romanian - Zer8_
_Will also touch base with rdfbbx for coordination_

- Where is the best place to publish/keep the translated versions?
- Who will do the QA? How do we ensure that the translation is accurate?
_Suggested short-term solution: Put a disclaimer that the original author doesn’t have any contribution to the translated version and add the link to the original version_
- Inform the original author that the article will be/has been translated.
- How do we compensate the contributors for this? IH? Bounties?
- Anything else?

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. There's a process for coordinating translation work
2. We have identified the articles/materials to be translated and publish/keep them in a platform/website that's accessible to the target audience
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@tamarandom

## 🔗  Are there links or docs related to this issue?
Recommended by Vyvy: https://crowdin.com/ 

## 👀  Who should be in the loop about this issue?
@

**Comment by iviangita** [comment]
For the list of articles, we can start with only 3 for now. These are my best picks:

1) [Token Engineering Commons: Analysis of Stakeholders, Tokens & Governance Processes ](https://medium.com/token-engineering-commons/token-engineering-commons-69398048209a) - there are other introductory articles about TEC but some details in those articles are outdated. This one is the latest and the most comprehensive.
2) [Engineering Ethics in Web3](https://medium.com/token-engineering-commons/engineering-ethics-in-web3-18d981278018) - this is one of our best evergreen content pieces 
3) [TEC Hatch: What's Next?! ](https://medium.com/token-engineering-commons/tec-hatch-whats-next-9b282fce1827) - this is to give the latest update on the status of TEC

@tamarandom @chuygarcia92 do you think these are okay? I'm open to other suggestions :)

**Comment by chuygarcia92** [comment]
Maybe this could be a little ambitious but I'd love to contribute with Shermin's piece as well:
https://medium.com/token-engineering-commons/token-engineering-commons-69398048209a

**Comment by tamarandom** [comment]
@iviangita What do you think of keeping the list of articles limited to evergreen? At least to start with. So the last one I would take off the list. It will no longer be so useful in 2 months time. 

@chuygarcia92 that's the same one as the first link in @iviangita's list. You know what they say about great minds!

**Comment by iviangita** [comment]
@tamarandom yes we can limit the articles to evergreen, can we replace no.3 with this: [Wielding Promethean Fire — The Importance of Token Engineering Public Goods](https://medium.com/token-engineering-commons/wielding-promethean-fire-the-importance-of-te-public-goods-9afba0ce5a43)? :)

**Comment by iviangita** [comment]
To close this issue, this is the quick process what we’ve come up with:

1. We will open a new issue for each article to be translated.
2. Ivy will coordinate with the contributors who have previously expressed interests in translating articles for TEC and invite them to participate in the issue if they are available.
3. The translated articles will be posted on Gitbook or the TEC Content Map. As we don’t have Language experts yet to review accuracy of the translations, the article should have a disclaimer that the original author doesn’t have any contribution to the translated version and the translator will add the link to the original version. 

Here are the first 2 articles that we suggest to be translated as these are evergreen content pieces that talk about TEC and token engineering comprehensively:

a) T[oken Engineering Commons: Analysis of Stakeholders, Tokens & Governance Processes ](https://medium.com/token-engineering-commons/token-engineering-commons-69398048209a)
b) E[ngineering Ethics in Web3 ](https://medium.com/token-engineering-commons/engineering-ethics-in-web3-18d981278018)

This task is voluntary and will be rewarded with Praise.
