### ISSUE TITLE
Framework for Project's Proposals.

### ISSUE THREAD

**Issue by eduardovegap** [CommonsBuild/coordination#841]
## 👇🏽  What is this issue about? Give as much detail as you can. 

This issue is to find consensus over a better process to handle proposals. 

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@liviade1 

## 🔗  Are there links or docs related to this issue?
https://forum.tecommons.org/t/proposed-framework-for-receiving-projects-proposals/562

## 👀  Who should be in the loop about this issue?
@

**Comment by tamarandom** [comment]
Hey @eduardovegap - is this coming into Sprint 18?

**Comment by GriffGreen** [comment]
@eduardovegap can this be closed?

**Comment by tamarandom** [comment]
Closing.
