### ISSUE TITLE
Stewards WG funding proposal 

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#844]
## 👇🏽  What is this issue about? Give as much detail as you can. 
What and who should be funded as part of the Stewards WG? 

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. Drafting a crappy first draft for Advice Process
2. Draft a good proposal for publishing to the Forum
3. Eventually, after the Commons Upgrade, proposing to the DAO

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@GriffGreen @liviade1 @Stewards 

## 👀  Who should be in the loop about this issue?
@

**Comment by tamarandom** [comment]
I've done a lot of think work towards this over this Sprint. The outline for the model is taking shape. I expect that a first draft will happen next Sprint.

**Comment by tamarandom** [comment]
First draft is ready. Phew! Just in time for tomorrow's council!
https://docs.google.com/document/d/1Df96GptjepEDRJCK4bI6BCnr0KfQNaPpVsMLCCb6qwY/edit#

**Comment by GriffGreen** [comment]
love it!

**Comment by tamarandom** [comment]
Looking like we will have a good version to post on the Forum for advice process in Sprint 21.

**Comment by tamarandom** [comment]
Posted on the Forum. https://forum.tecommons.org/t/steward-wg-3-month-funding-proposal/713
