### ISSUE TITLE
Hatch DAO Vote: 75% governance rights restored

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#846]
## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by JuankBell** [comment]
Proposal posted. Advice process being done about the technical solution.
https://forum.tecommons.org/t/75-governance-giveback/569

**Comment by JuankBell** [comment]
I think that this vote could be done through weighted voting with multiple alternatives: 

1. No Governance giveback
2. 75% Governance giveback + (Quick and dirty solution)
3. 75% Governance giveback + (Slow and steady solution)
4. 75% Governance giveback + (still unknown solution)

Advice process* @GriffGreen

**Comment by JuankBell** [comment]
Proposal to be voted on the 24-27 september. @chuygarcia92 tagged to help communicating the vote https://forum.tecommons.org/t/75-governance-giveback/569/15

**Comment by JuankBell** [comment]
Snapshot proposal was approved with 92% support. 
Follow up for the implementation and the discussion for the technical solution will be during Commons Swarm calls and in the same forum thread https://snapshot.org/#/tecommons.eth/proposal/Qmcbkz5vL9XW1LqhvoKQqLeP8wfToHkTQZjMYvuXxozB5j

**Comment by tamarandom** [comment]
done!
