### ISSUE TITLE
Hatch DAO Vote: Initial buy into the ABC for the DAO

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#848]
## 👇🏽  What is this issue about? Give as much detail as you can. 

More details coming soon!

@tamarandom and @Zeptimus will collaborate on getting this done.

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by Zeptimus** [comment]
Posted on the forum on advice process it's having good engagement https://forum.tecommons.org/t/should-we-do-the-initial-buy-into-the-bonding-curve/574/6

**Comment by tamarandom** [comment]
This is closed, it was posted to the forum for ideation!
