### ISSUE TITLE
Legal review of covenant before community vote

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#849]
## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by tamarandom** [comment]
After @liviade1 has the updated covenant, it should be looked at by Legal before going to community  vote.

**Comment by iviangita** [comment]
Pablo (new legal contributor) will review the Covenant over the weekend and give his feedback if it's ready to proceed with the community vote. Bringing this to next sprint!

**Comment by tamarandom** [comment]
Excellent!

**Comment by tamarandom** [comment]
Covenant update on Dev 7th on the Forum: 
https://forum.tecommons.org/t/tec-community-covenant/572/10

TEC Community Covenant
The Token Engineering Commons is a self-governed organization with the purpose of advancing the field of token engineering. The TEC supports the creation of ethical, safe, resilient and diverse economic systems to benefit societies around the world.

The TEC’s mission is to become a Schelling Point 1 for the token engineering community through economic and social layers. The economic layer funds projects that discover, develop and proliferate the best practices for engineering safe tokenized economies, while aligning our collective success with the individual benefit of TEC token holders. Our social layer is even more important, as it unites the token engineering field around the ethical principles, standards, tools and methodologies that emerge as this nascent field advances.

The Token Engineering Commons cultural framework operates based on Elinor Ostrom’s principles for governing the commons. It values a prosocial perspective and prioritizes the advancement of token engineering over short-term profits. ‌Integrity, curiosity, constructive inquiry, consistency, presence and gratitude are foundational for maintaining mutual respect within the growing community.‌

The TEC encourages its members to be radically open source, non-hierarchical, transparent in their intentions and accountable for their actions.

The growth of the TEC community is directly related to the community’s ability to foster an inclusive, welcoming, and healthy culture that people can feel proud of and delighted to adopt as their own. When people choose to participate in the TEC community, they are implicitly supporting the community’s mission, culture, values, and norms.

Therefore, TEC rests on an ever-evolving social contract, which sets expectations for how members should engage both with the protocol and with one another. Organizationally, the Covenant first lays out our pledge to each other to make the TEC community a welcoming and safe environment for everyone. Second, it directs the reader to the polycentric governance framework used in the TEC and finally it covers the enforcement mechanisms. As a community driven DAO, the Covenant is subject to change via the community.

The Pledge
We as members, contributors, and leaders declare to make participation in the TEC community a harassment-free experience for everyone, regardless of age, visible or invisible disability, ethnicity, sexual orientation, gender identity and/or expression, level of experience, education, socio-economic status, nationality, personal appearance or religion.

We promise to act in ways that contribute to an open, welcoming, diverse, inclusive, and healthy community.

Our Standards
Examples of behavior that contributes to a positive environment for our community include:

Demonstrating empathy and kindness toward other people
Being respectful of differing opinions, viewpoints, and experiences
Giving and gracefully accepting constructive feedback
Accepting responsibility and apologizing to those affected by our mistakes, and learning from the experience
Focusing on what is best not just for us as individuals, but for the overall community
Examples of unacceptable behavior include:
The use of sexualized language or imagery, and sexual attention or advances of any kind
Trolling, insulting or derogatory comments, and personal or political attacks
Public or private harassment
Publishing others’ private information, such as a physical or email address, without their explicit permission (commonly called doxing)
Other conduct which could reasonably be considered inappropriate in a professional setting
Decision Making
The Token Engineering Commons uses a polycentric governance framework that gives cultural, financial and technical decisions similar importance. The processes and parameters for each governance module are specified in this living document and might change based on the community’s decisions according to the governance process currently at the time of the change.

DAO Enforcement
The on-chain mechanism for enforcement depends on Celeste and is meant to be used within Conviction Voting and Tao Voting.

The ability for the Token Engineering Commons protocol to enforce this covenant is limited to the direct interactions that community members have with the protocol, specifically the ability for community members to submit proposals to allocate funds or adjust protocol parameters.

The proposer will be required to deposit TEC tokens when submitting a proposal, attesting that the impact of the proposal could be reasonably considered to align with TEC’s social contract. A dispute can be created by another community member if they disagree with the proposer’s attestation by challenging the proposal and staking an equivalent amount of TEC tokens. If after being challenged, the proposal is not withdrawn, Celeste will be used to settle the dispute with the right to appeal that decision.

Celeste keepers are expected to review the proposal, this covenant, evidence submitted by the proposer and challenger and related past disputes in order to provide a judgement that they feel best aligns with the established norms and intention of the TEC community.

Cultural Enforcement
The cultural mechanism for enforcement will depend on Gravity. Actions that contradict the mission, vision, values and pledge of the TEC will be handled through Gravity, TEC’s trust creation and conflict management working group. The TEC has a system of graduated sanctions to approach different types of behavioral issues.

Gravity promotes methods for addressing conflict and counts with a trained group of facilitators called Gravitons. Every community member has the right to approach Gravity easily and with no costs.

The Gravity group aims to support the TEC by:

Actively promoting trust and managing conflict between individuals, groups, and the community as a whole.
Recognizing boundaries and areas of potential dispute, as well as explicit violations of boundaries between individuals, groups, and the community as a whole.
Supporting communication between community members and encouraging active participation.
Promoting community resilience and long-lasting human relationships by proactively co-creating boundaries, discussion and exchange in a system of shared values.
Promoting Advice Process regarding the implementation of graduated sanctions and commit to its use with respect to all individuals.
Transparency
The TEC values transparency as a cultural practice as it helps to promote trust, mutual monitoring, accountability and inclusion. Most of the community calls are recorded and published on TEC’s Youtube channel. The Transparency working group promotes frequent audits to proposals and working groups. Credentials management is visible and admins follow a particular code of conduct.

If this covenant has to be changed or updated, a proposal should be published in the forum following Community Advice Process, then sent to Tao Voting for approval.

**Comment by iviangita** [comment]
Here are Shawn's comment:

_yeah, third paragraph I'd consider changing "short-term profits" with "short-term gain".  Third paragraph of DAO Enforcement - if coins aren't earning money, I'd consider a different word than staking which has a common understanding in crypto as earning an APY.  If it does earn an APY, this comment can be ignored.  I like the link to the polycentric voting and Celeste.  The comments to the document should be answered.  Otherwise, I think it looks good!_

Added and integrated it in @liviade1's document: https://docs.google.com/document/d/1RTLgArtG48VvATEVPOS5NWpYfX8odti5c-znotaDX2Q/edit?usp=sharing 

CLOSING!
