### ISSUE TITLE
set up snapshot for testing as potential platform for next votes 

### ISSUE THREAD

**Issue by liviade1** [CommonsBuild/coordination#854]
## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@natenatesoo @liviade1

**Comment by natenatesoo** [comment]
Done!
