### ISSUE TITLE
Post Hatch Reward System

### ISSUE THREAD

**Issue by liviade1** [CommonsBuild/coordination#86]
## 📋 Anything to add?

(prehatch : effort is incentivized by impact hours and post-hatch that incentive goes away. So, how will effort be incentivized afterwards? Need plan before hatch launches for post hatch incentivization. 

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by drllau** [comment]
Random acts of kindness?
- activity / participation can be measured using systems such as SourceCred
- based on accumulated praise, a % chance of drawing a small "gift" (token) can be airdropped
- note that for volunteer non-profits orgs, there are monetary caps
- there can also be intangibles like letters of appreciation, virtual boquets, most valued contributor

Build up a set of social rituals to recognise non-monetary contributions

**Comment by elihanover** [comment]
What's the status on this?  I've been doing some independent reflection and would like to help drive this forward.
