### ISSUE TITLE
Review and add graduated sanctions on code of conduct for admins

### ISSUE THREAD

**Issue by Zeptimus** [CommonsBuild/coordination#861]
## 👇🏽  What is this issue about? Give as much detail as you can. 
Review the code of conduct for admins https://docs.google.com/document/d/1hnwSQn4vxboxazraX2qPwa25bBBrvk3TpXsSDkXhqCM/edit and add graduated sanctions for those who miss behave

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@Zeptimus 

## 👀  Who should be in the loop about this issue?
@

**Comment by JuankBell** [comment]
OK from Gravity. 

Violating this Code of Conduct may lead to: 

*Discussions with the Stewards Working Group, to determine transformational strategies. 
*Escalation to the Gravity Working Group to search for mediated solutions according to the TEC graduated sanctions,
*Eventually subject an Administrator to removal of platform access or other privileges in the organization.
