### ISSUE TITLE
Revisit agreements in Handbook

### ISSUE THREAD

**Issue by MrsBadgerface** [CommonsBuild/coordination#862]
## 👇🏽  What is this issue about? Give as much detail as you can. 
Request by @liviade1 for someone to revisit the agreements in the handbook to ensure that they reflect our MVV.

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. Relevant stewards agree that any edits to the agreements are suitable.
2. Community supports edits.
3. If edits made, agreements in the Handbook are updated.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@liviade1 

## 🔗  Are there links or docs related to this issue?
https://token-engineering-commons.gitbook.io/tec-handbook/tec-agreements-1/why-do-we-need-agreements

## 👀  Who should be in the loop about this issue?
@liviade1

**Comment by MrsBadgerface** [comment]
Update:

- The contributors have dived into these and added tons of questions and ideas.
- I've shared the document in the stewards channel and asked for stewards to please answer questions when they can or support or reject suggestions.
- Livia and I will liaise on Monday 6th Sept re. next steps and ownership while I'm on holiday from the 8th Sept for 2 weeks.

The Google doc is here: https://docs.google.com/document/d/1diintDuutf-OK9u0noyleaKS7BfkoF2UUuCrHhmwYNQ/edit#heading=h.y1g4fl643n7q

**This will need to be moved to the next sprint.**

**Comment by MrsBadgerface** [comment]
Handing this over to @liviade1 to move forwards as I'm away for the next two weeks.

**Comment by tamarandom** [comment]
Closing old issues.
