### ISSUE TITLE
Make a long-term Gravity roadmap 

### ISSUE THREAD

**Issue by JuankBell** [CommonsBuild/coordination#863]
## 👇🏽  What is this issue about? Give as much detail as you can. 

We have been using 3month roadmaps in Gravity, but feedback and insights show that it would be good to have a clear long term scope (1year) of the project, to follow interconnected goals and objectives that take us to the place we would like to be. 

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. We have clear steps to direct the project for making Gravity a DAO 
2. We have a funding and rewards system strategy for gravitons
3. Gravity having its our own Mission-vision-values

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@liviade1 @tamarandom @GriffGreen @ddan4 @MrsBadgerface 

## 👀  Who should be in the loop about this issue?
@durgadas @mount-manu @Zeptimus

**Comment by JuankBell** [comment]
Done with help of Durgadas on past days. missing to share, communicate and receive feedback :)
 https://docs.google.com/spreadsheets/d/159PXnpqmSALyo0Ps3Pk7HyzEkSeapNnBG5005Qh4qU0/edit#gid=752293848

**Comment by JuankBell** [comment]
Next task: 3 month activities calendar

**Comment by GriffGreen** [comment]
We have a draft but it needs to become a infographic

**Comment by natenatesoo** [comment]
Still in Progress. To remain in Product Backlog.

**Comment by JuankBell** [comment]
![Captura de Pantalla 2022-03-03 a la(s) 7.45.35 a. m..png](https://images.zenhubusercontent.com/5fb57c9c5472cf79e80e7f7e/877e6751-f90a-47ba-84af-fc8f3bf254d3)

**Comment by JuankBell** [comment]
This will be promoted within the medium article scheduled for end of march.
https://docs.google.com/document/d/1hC3CRWzcljSvHQ7iRQ1g_m8uCrPpRQ6Bdu6Ghw5N_jQ/edit

**Comment by mount-manu** [comment]
**Juanka's Update:** Besides pushing for engagement through Medium, Twitter, and our HubSpot biweekly newsletter, we want to organize hack sessions around what Gravity DAO's token engineering model would look like, how we can start configuring our Gardens, and setting up the legal due diligence that would allow us to crowd-fund through a Hatch event. Q3 will be when we elaborate on this and specify dates of completion.
