### ISSUE TITLE
Comms WG Funding proposal 

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#864]
## 👇🏽  What is this issue about? Give as much detail as you can. 
(already work in progress....)

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by chuygarcia92** [comment]
this presentation is a work in progress for the TE Comms DAO:

https://docs.google.com/presentation/d/1NEL4iyTe28C71RwNiGwBmQ_8NI27eLvU1IO2_7JeDQI/edit?usp=sharing

**Comment by chuygarcia92** [comment]
All proposals have been submitted. Closing this issue now.
