### ISSUE TITLE
Devops support for our merch and swag shop

### ISSUE THREAD

**Issue by iviangita** [CommonsBuild/coordination#868]
## 👇🏽  What is this issue about? Give as much detail as you can. 

If you're looking at this issue hoping to contribute to the project, welcome! We'd love to have you contribute, so please let us know if you have any questions.

Comment on the issue or touch base in our [Discord](https://discord.gg/WxMPdEvV).

We have experienced some technical issues on our swag and merch shops and are still looking for one or more devops that can provide support there. It's not glamorous work but it would make sure we can keep giving away cool TEC swag!!

We are using Origin Protocol's dshop: https://www.originprotocol.com/en/dshop

If you can make your way around codebase in github and have a good understanding of backend APIs and docker PLEASE reach out to @kristoferlund @iviangita @tamarandom and we will give you a brief so you can **help keep the TEC swag flowing to the community in the future!!**

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. Technical issues are identified
2. There's a solution for these technical issues
3. Less issues in the future and support is available whenever an issue occurs

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by Big-Gray-Al** [comment]
Bringing your attention to the epic that I have just created for getting a build pipeline started on the praise system.

Assuming it comes together on schedule, We will probably need some help from the non-technical community to do user testing in the next week or two.

https://app.zenhub.com/workspaces/praise-617a8e3dfa496c001053f251/issues/commonsbuild/praise_frontend/22

**Comment by tamarandom** [comment]
Hey @Big-Gray-Al, This is excellent though not so related to this issue. ;)
Yes, I think we can rally up some people to do user testing when it is ready! Good to have the heads up.

**Comment by tamarandom** [comment]
Good news! We have moved onto another platform (wordpress and a custom plugin). Closing this issue now.
