### ISSUE TITLE
Removal of Hatch Outreach WG from TEC website

### ISSUE THREAD

**Issue by danelsuga** [CommonsBuild/coordination#870]
Cross-posted in website dev as issue #35

## 👇🏽  What is this issue about? Give as much detail as you can. 

Remove Hatch Outreach Working Group has closed. Please remove the WG from the TEC website.

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. Removal of Hatch Outreach WG from website that lists all WG's.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@@markoprljic @kristoferlund 

## 🔗  Are there links or docs related to this issue?

https://tecommons.org/workgroups

## 👀  Who should be in the loop about this issue?
@tamarandom

**Comment by kristoferlund** [comment]
Done deal.

https://tecommons.org/workgroups

**Comment by tamarandom** [comment]
⚡ ⚡
