### ISSUE TITLE
Value proposition for early stage strategic investors

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#874]
## 👇🏽  What is this issue about? Give as much detail as you can. 
Attracting early investors. 

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. Thinking around ballpark figures and who would be good candidates for value-aligned, strategic partners
2. Feel out interest in early participation into the TEC
3. Small team to follow through to conclusion

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@Angela @GriffGreen @ygg .... who else!?

## 🔗  Are there links or docs related to this issue?
The initial forum post: https://forum.tecommons.org/t/should-we-do-the-initial-buy-into-the-bonding-curve/574/8

## 👀  Who should be in the loop about this issue
@Stewards

**Comment by tamarandom** [comment]
Making some progress here but this will continue over the next few Sprints.

**Comment by GriffGreen** [comment]
maybe we should make this it's own forum post

**Comment by tamarandom** [comment]
Yes, great idea! At the moment, it's think work and nothing is written yet but when something more concrete is ready, that's where it will go.

**Comment by tamarandom** [comment]
Going to come back to this after we have a better idea of the final figure that will be allocated to this in the buy-in proposal. So likely the sprint after the next one.

**Comment by tamarandom** [comment]
Closing this because it never came together.

![meh.jpeg](https://images.zenhubusercontent.com/5faaa1d038c6409364f7830c/1b1496be-adb3-4592-b0ae-e1a6dcd53fa3)
