### ISSUE TITLE
Continue research on DAO Treasury Management 

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#876]
## 👇🏽  What is this issue about? Give as much detail as you can. 
Evaluate and propose suggestion for treasury management. The options are not few. What are the criteria we should use to evaluation the options, which one will best serve the TEC?

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. Someone owns this!
2. Evaluation of the options and selection process 
3. Design and propose the solution for vote

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@griff @divine-comedian @zeptimus @ivingita

## 👀  Who should be in the loop about this issue?
@Stewards

**Comment by Zeptimus** [comment]
Still in progress we hold some debates 
https://forum.tecommons.org/t/earn-interest-on-wxdai-with-hatch-funds-tec-x-agave/604/9
https://forum.tecommons.org/t/swap-tec-tokens-for-agave-tokens-tec-x-agave/605/10

**Comment by Zeptimus** [comment]
Update: https://forum.tecommons.org/t/lets-talk-about-treasury-management/642

**Comment by tamarandom** [comment]
With Sampo live, we can close this.
