### ISSUE TITLE
Praise bot message

### ISSUE THREAD

**Issue by iviangita** [CommonsBuild/coordination#877]
## 👇🏽  What is this issue about? Give as much detail as you can. 

The Praise bot message needs to be updated since the Hatch is finished.

This is the old Praise bot message:

**Discord**
![image.png](https://images.zenhubusercontent.com/5fb5cba95f94b9eb73a91fe5/255891ed-6da3-4f1e-a951-92ce58644356)

**Telegram**
![image.png](https://images.zenhubusercontent.com/5fb5cba95f94b9eb73a91fe5/e75fd603-05eb-4785-a8b4-d2be65fc8407)

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@liviade1 

## 👀  Who should be in the loop about this issue?
@Zeptimus

**Comment by iviangita** [comment]
Hi @Zeptimus @liviade1 I finished revising the Praise bot message - hope you can take a look and feel free to add other changes! :)

https://docs.google.com/document/d/1D4lvWGlPMrj1gIDVP7UT2QKkMFbxMyMA8MoR3RZSTvQ/edit?usp=sharing

**Comment by tamarandom** [comment]
Hey @Vyvy-vi !!

@iviangita and I just made some changes and it's ready to go! There is only one outstanding questions about the image that will be used when it is sent but I think we can see this when we test it out. Is it possible to create use a specific image and not default to one of the ones associated with the articles linked?

**Comment by Vyvy-vi** [comment]
I think that can be done

**Comment by tamarandom** [comment]
👍

**Comment by iviangita** [comment]
Hello @Vyvy-vi just wanna check if there are updates on this? Please let me know if there's anything I can support you with :)

**Comment by iviangita** [comment]
UPDATE: @Vyvy-vi has applied the changes, I'm coordinating with @krisjpi to re-deploy the bot

**Comment by iviangita** [comment]
UPDATE: The new Praise bot message has been implemented in TEC Discord by @hurek. However, the one on Telegram isn't updated yet. @GriffGreen may I know whom I can reach out to to implement the changes on the Telegram praise bot message? :)

**Comment by tamarandom** [comment]
Update: @hurek (Rudolf!) is the person to ask.

**Comment by GriffGreen** [comment]
https://github.com/commons-stack/CommonsStackBot/blob/master/constants.js

I think we can just change it there and it will update

**Comment by GriffGreen** [comment]
lines 96 thru 106 are what need to be changed...

**Comment by iviangita** [comment]
I submitted a pull request with @Vyvy-vi's help, he will test it before making it live :)

**Comment by tamarandom** [comment]
@GriffGreen do you know who has access to / manages the praise-bot on Telegram? @hurek gave feedback to @iviangita that he does not have access to the bot.

**Comment by Vyvy-vi** [comment]
I think the bot on Telegram auto-deploys

**Comment by tamarandom** [comment]
@Vyvy-vi hmmm... you happen to know where is the text stored?

**Comment by iviangita** [comment]
DONE! Thank you so much @Vyvy-vi @tamarandom for providing support in this issue 🙏🏽

**Discord**
![image.png](https://images.zenhubusercontent.com/5fb5cba95f94b9eb73a91fe5/a39d7d51-d65b-4895-a8f3-d3403d49a56b)

**Telegram**
![image.png](https://images.zenhubusercontent.com/5fb5cba95f94b9eb73a91fe5/2af4d228-b444-4ec2-9559-8048fded42b2)
