### ISSUE TITLE
Documentation on types of Snapshot voting

### ISSUE THREAD

**Issue by iviangita** [CommonsBuild/coordination#878]
## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by Zeptimus** [comment]
Done! https://forum.tecommons.org/t/decision-making-guide/609/4
