### ISSUE TITLE
Development for Communitas WG!

### ISSUE THREAD

**Issue by danelsuga** [CommonsBuild/coordination#881]
## 👇🏽  What is this issue about? Give as much detail as you can. 
It's time to develop a WG for orientation and community building!

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. New members feel guided. 
2. Non new members feel guided!
3. Assistance on integration and relationships within the community.
4. Figuring it out if integration with TEC Scouts is possible.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@GriffGreen @tamarandom @chuygarcia92 @eduardovegap @Santigs @liviade1 @natenatesoo @cranders1 @JuankBell @LinuxIsCool @solsista @iviangita  @Zeptimus 

## 🔗  Are there links or docs related to this issue?

Manifesto: https://docs.google.com/document/d/1g9vycoqIZkg83KyRM-7wMeCN-QxZTSfO-Ofq8o7U9pQ/edit?usp=sharing

## 👀  Who should be in the loop about this issue?
@

**Comment by eduardovegap** [comment]
@danelsuga I took the liberty of adding some points to what success looks like.

**Comment by danelsuga** [comment]
The Communitas WG has been created! There are a few more steps to undertake (website WG page [#908], forum [#909]), but I believe this issue can now be closed.
