### ISSUE TITLE
WG new contributors wishlist

### ISSUE THREAD

**Issue by danelsuga** [CommonsBuild/coordination#889]
## 👇🏽  What is this issue about? Give as much detail as you can. 
I would like to request on regular basis a new list from stewards for issues they would have for new contributors to take

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. Regularly identifying roles for new contributors to share with them.
2. New contributors regularly taking on issues.
3. This leading to new contributors becoming part of the community!

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@GriffGreen @tamarandom @chuygarcia92 @eduardovegap @Santigs @liviade1 @natenatesoo @cranders1 @JuankBell @LinuxIsCool @solsista @iviangita  @Zeptimus 

## 👀  Who should be in the loop about this issue?
@

**Comment by GriffGreen** [comment]
added mine!

**Comment by tamarandom** [comment]
Link: https://docs.google.com/document/d/1hkbt8R8BlHWsLd5OHHqZ-hMmH8dmkDAoY9c7J2ZtRc0/edit

**Comment by danelsuga** [comment]
Thanks, everyone!

**Comment by tamarandom** [comment]
@freshelle - have you a little time to work with me or @Vyvy-vi  on this?
