### ISSUE TITLE
Estimating how many contributors we have now!

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#891]
## 👇🏽  What is this issue about? Give as much detail as you can. 
Since we stopped bi-weekly praise, we haven't been estimating active contributors. Find new way to do this. 

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

**Comment by GriffGreen** [comment]
https://docs.google.com/spreadsheets/d/1d7KVvAUlWb2yZPDTMttr1gEHzod6RKOiheGk-FX0BqE/edit?usp=sharing

In this sheet we track the number of unique discord handles (there is a tab that shows that) 

This is an estimate... cause we have people on our telegram, that are left out of this count... but then also there are people who change their discord name that are counted multiple times... so i think it balances out and this is a good estimate.

**Comment by GriffGreen** [comment]
Current estimate is 460

**Comment by tamarandom** [comment]
⚡ ⚡ ⚡
