### ISSUE TITLE
Make snapshot more accessible to the public 

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#893]
## 👇🏽  What is this issue about? Give as much detail as you can. 
Add to website? Gitbook? Discord pinned message? Footer of our Blogpost, on our Twitter bio, etc? 

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. It is easy for Hatchers to find our snapshot link so they can vote!
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@natenatesoo @Zeptimus @danelsuga 

## 👀  Who should be in the loop about this issue?
@Stewards

**Comment by tamarandom** [comment]
@natenatesoo should this come into Sprint 18?

**Comment by natenatesoo** [comment]
Incorporated within other issues created, so we can close it.
