### ISSUE TITLE
Community WG Manifesto

### ISSUE THREAD

**Issue by danelsuga** [CommonsBuild/coordination#896]
## 👇🏽  What is this issue about? Give as much detail as you can. 

Advice process on the manifesto for the new Community WG

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)

The stewards would approve this manifesto and subsequently approve the Community WG so we can move forward both with the objectives of the WG (and eventually with a new proposal for funding before the upgrade).

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@stewards
@GriffGreen @tamarandom @chuygarcia92 @eduardovegap @Santigs @liviade1 @natenatesoo @cranders1 @JuankBell @LinuxIsCool @solsista @iviangita @Zeptimus @MrsBadgerface 

## 🔗  Are there links or docs related to this issue?

Here is the manifesto:

https://docs.google.com/document/d/1g9vycoqIZkg83KyRM-7wMeCN-QxZTSfO-Ofq8o7U9pQ/edit?usp=sharing

**Comment by Zeptimus** [comment]
yeah its so needed thanks katy for taking that on! The team looks awesome!!

**Comment by GriffGreen** [comment]
So excited for a Community WG!!

**Comment by danelsuga** [comment]
We've named it Communitas WG, and it's ready to go!

https://docs.google.com/document/d/1g9vycoqIZkg83KyRM-7wMeCN-QxZTSfO-Ofq8o7U9pQ/edit#
