### ISSUE TITLE
Forums backend update

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#897]
## 👇🏽  What is this issue about? Give as much detail as you can. 

![Screen Shot 2021-09-05 at 11.44.55 PM.png](https://images.zenhubusercontent.com/5faaa1d038c6409364f7830c/651377c7-65c6-460a-be5f-ce7a6aef0725)

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. discourse update ;) 
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by Vyvy-vi** [comment]
![Discourse Update has been completed](https://user-images.githubusercontent.com/62864373/133413344-153a46a0-30b0-4d95-b928-24e12e279f34.png)
done! :)

**Comment by tamarandom** [comment]
Excellent!!
