### ISSUE TITLE
Gitcoin Grant R11

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#898]
## 👇🏽  What is this issue about? Give as much detail as you can. 
We we do this?

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@cranders1 @GriffGreen 

## 🔗  Are there links or docs related to this issue?
https://gitcoin.co/grants/1155/token-engineering-commons

## 👀  Who should be in the loop about this issue?
@

**Comment by cranders1** [comment]
hey @tamarandom & @GriffGreen. happy to update the TEC grant for GR11.
i will try to update the logo and info, but still with a generic flavor.
if others have more specific grant ideas, i'm all ears ;)

**Comment by tamarandom** [comment]
You are a superhero, @cranders1 ! ⚡ 🦸 ⚡

**Comment by tamarandom** [comment]
@cranders1 - I think this is all done - shall we close now?

**Comment by cranders1** [comment]
yep
