### ISSUE TITLE
TEC token listings

### ISSUE THREAD

**Issue by chuygarcia92** [CommonsBuild/coordination#901]
## 👇🏽  What is this issue about? Give as much detail as you can. 
Work on pre stuff required for listings. The goal is to list TEC ASAP after the Commons Upgrade.

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. We're able to list TEC on main platforms shortly after the ABC launch
2. Establish contact with support for proposed listing platforms
3. Develop required API for talking to the ABC

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@sembrestels @PJColombo @GriffGreen @Zeptimus @natenatesoo @chuygarcia92 

## 🔗  Are there links or docs related to this issue?
* CoinGecko
* CoinMarketCap
* DeepDAO
* PositiveBlockchain.io

## 👀  Who should be in the loop about this issue?
@tamarandom @liviade1

**Comment by natenatesoo** [comment]
Yay! Good Job!
