### ISSUE TITLE
What is the feasibility of changing the TEC Praise bot icon to the TEC logo? 

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#906]
## 👇🏽  What is this issue about? Give as much detail as you can. 
Is is currently the Commons Stack one. See here:

![Screen Shot 2021-09-16 at 10.18.48 AM.png](https://images.zenhubusercontent.com/5faaa1d038c6409364f7830c/70af0b01-7441-4180-896a-38ee8c3411b5)

Even though the Praise was received for TEC and not CS.

![Screen Shot 2021-09-16 at 10.19.42 AM.png](https://images.zenhubusercontent.com/5faaa1d038c6409364f7830c/31d7ce7d-fcf0-425d-96da-a25f83cd80bb)

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. Determine whether this is possible or not. 
2. If it's possible, we should do it. 
Benefit being (1) greater distinction between CS and TEC and (2) feature that other organizations adopting Praise as a product would need.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@iviangita @Vyvy-vi @krisjpi @kristoferlund @hurek (<-- finally got rdfbbx's github handle!)

## 👀  Who should be in the loop about this issue?
@GriffGreen

**Comment by Vyvy-vi** [comment]
There's a small issue there.
CommonsStack and the TEC use the same discord bot for Praise.

To change the profile picture, we would need to deploy our own instance

**Comment by tamarandom** [comment]
Good to know. It sounds like the kind of thing we will need to do eventually. 

Open question: what are the consequences to deploying an independent TEC praise bot?

**Comment by Vyvy-vi** [comment]
There would be a hosting cost for the bot, and I think there might be some differences in how the praise gets handled for both CommonsStack and the TEC. (I think the praise goes to a spreadsheet, where griff separates them into separate Praise Quant sheets)

**Comment by tamarandom** [comment]
Tagging with Next Sprint to that this comes up for discussion in our Sprint planning now...

**Comment by tamarandom** [comment]
@Vyvy-vi @kristoferlund can we look at what it would take to deploy an independent Praise bot for the TEC and where in the Rewards System plan that would make the most sense to implement.

**Comment by Vyvy-vi** [comment]
We would need an active worker, which can be available on any VPS like DigitalOcean for around 5$/month or something.
The hosting process should be straightforward, however we might need our own spreadsheet credentials(*I'm not sure).

With regard to the new Rewards plan, and the backend approach to it, I think the bot would remain like it is _however_ it would store the data in the backend via an API request(I guess)

**Comment by hurek** [comment]
@Vyvy-vi Do you want to have a micro-service architecture? Since my main stack is java + spring framework, I don't see a problem in running discord and telegram bot as components of the same application.

**Comment by Vyvy-vi** [comment]
That can be done 🤔

**Comment by GriffGreen** [comment]
we will want to consider doing this in telegram as well

**Comment by Vyvy-vi** [comment]
> Do you want to have a micro-service architecture? Since my main stack is java + spring framework, I don't see a problem in running discord and telegram bot as components of the same application.

Considering how the new interactions API works, we could probably cross-link these neatly. (Interactions API allows you to run the bot entirely on an HTTP server) 🤔

**Comment by tamarandom** [comment]
> > Do you want to have a micro-service architecture? Since my main stack is java + spring framework, I don't see a problem in running discord and telegram bot as components of the same application.
> 
> Considering how the new interactions API works, we could probably cross-link these neatly. (Interactions API allows you to run the bot entirely on an HTTP server) 🤔

Thanks @hurek @Vyvy-vi ! Looping in @kristoferlund so it's on his radar too.  

I'm sensing this is feasible. I'm out of my depth with discussion on the technical architecture and advantages or disadvantages so look forward to the end solution following those discussions!

**Comment by kristoferlund** [comment]
Do I understand this correctly? We consider migrating the current praise bot over to a java/spring architecture and separating the TEC and CS bots? The upgraded bot would run on an HTTP server accepting calls from the outgoing webhooks of the Discord Interaction API?

That to me seems like a good idea no matter how we move on with the rest of the praise project.

**Comment by kristoferlund** [comment]
Is praise data stored to google sheets directly by the bot currently or is there an intermediate copy/paste step? One way of taking baby steps for upgrading the praise process would be to move from google sheets to something more capable - Coda or possibly Airtable. If we choose that route we should consider building the bot so that it can support different data stores.

**Comment by Vyvy-vi** [comment]
Yes!

**Comment by tamarandom** [comment]
Chatting with @Vyvy-vi and here are the nest steps as we see them: 

If we decide to move forward with separating the TEC praise bot from the CS Praise bot, the next steps would be:

1. (tamara/griff) make new TEC praise spreadsheet & get credentials 
2. (vyvy) setup discord application, invite 4-5 of the Stewards into the “team” 
3. (vyvy) request from Kai server to host the bot 
4. (vyvy) remove the present bot & invite the new bot

**Comment by kristoferlund** [comment]
We can do as decribed. Or, we can wait until MVP of new praise is online by end of nov. Then, the bots need to be separated as part of the upgraded Rewards System anyway. Or rather, it wont be the same bot running on TEC as CS until CS also (hopefully) upgrade to the new praise system.

**Comment by tamarandom** [comment]
@kristoferlund  That is the question! My thinking is that as long as it is relatively easy we may as well just do it now rather than wait another 6-8 weeks (at least). From what I understand so far, it is relatively simple and we should probably just make a plan and execute. Do you think there is compelling reason to hold off? There very well might be something I am not thinking of!

**Comment by kristoferlund** [comment]
If it's easy, let's do it! Or rather, @Vyvy-vi, if you say let's do it, let's do it.

**Comment by tamarandom** [comment]
Hey @Vyvy-vi @kristoferlund I think we should close this. With the other priorities, this one is pretty low on the list. It will happen along with the Praise redesign and development. Any reason not to close it now?

**Comment by kristoferlund** [comment]
Close it!

**Comment by Vyvy-vi** [comment]
I think we can maybe close this for now :+1:
