### ISSUE TITLE
Add Communitas WG to TEC website

### ISSUE THREAD

**Issue by danelsuga** [CommonsBuild/coordination#908]
## 👇🏽  What is this issue about? Give as much detail as you can. 
The new Communitas WG needs to be added to the TEC website please!

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. Adding the info for Communitas WG to the WG webpage of the TEC website
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@markop

## 👀  Who should be in the loop about this issue?
@

**Comment by kristoferlund** [comment]
Sure I'll add! As soon as there is a logo @markoprljic.

**Comment by tamarandom** [comment]
Why don't we reuse the one for Hatch Outreach? It's a great one!!

**Comment by kristoferlund** [comment]
Eduardo, [11 Oct 2021 at 18:36:55]:
Description: The intention of this Working Group is to nurture, grow and guide the TEC community. The points of focus are new member orientation, current member community building, and organisational design: namely, guiding folks into the TEC and helping folks navigate the TEC from the inside.

Steward: eduardovegap#0422 + Tam2140#9361

Weekly call time: Monday's 8PM CET - 2PM EST

**Comment by tamarandom** [comment]
Added! Repurposed the logo from the Hatcher Outreach group. 

![Screen Shot 2021-10-13 at 10 57 12 AM](https://user-images.githubusercontent.com/703624/137101244-7aa76e93-59a1-4596-a487-5200aed32854.png)


![Screen Shot 2021-10-13 at 10 56 34 AM](https://user-images.githubusercontent.com/703624/137101145-920bc33b-13e6-4963-ba67-5e592413692b.png)
