### ISSUE TITLE
Add Communitas WG to the forum

### ISSUE THREAD

**Issue by danelsuga** [CommonsBuild/coordination#909]
## 👇🏽  What is this issue about? Give as much detail as you can. 
Add a page on the Communitas WG to the forum

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. Include all the pertinent info to join the other WG's on the forum
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@stewards

**Comment by eduardovegap** [comment]
https://forum.tecommons.org/t/communitas-working-group/649 The post has been added.
