### ISSUE TITLE
Work on listing our token on coingeko and see what do we need

### ISSUE THREAD

**Issue by Zeptimus** [CommonsBuild/coordination#910]
## 👇🏽  What is this issue about? Give as much detail as you can. 

Identify all the needs to get our token listed

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by chuygarcia92** [comment]
Update from @Zeptimus: 
the TEC token would need to be transferable so it can be listed in a DEX that's recognized by coingecko like Honeyswap.. we'll be on standby for this one until the community has started debates around this parameter

**Comment by chuygarcia92** [comment]
check in with the giveth team, talk to @GriffGreen for guidance on this topic

Vitor needs to add an API for speculative supply

**Comment by Zeptimus** [comment]
https://www.coingecko.com/en/coins/token-engineering-commons
