### ISSUE TITLE
Gravity transparency structure session with Juank 

### ISSUE THREAD

**Issue by liviade1** [CommonsBuild/coordination#919]
## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by JuankBell** [comment]
We made a zenhub board! Thanks livi for your help
https://app.zenhub.com/workspaces/gravity-614b594733915b001237f06e/board?repos=409276305
Cases from the registry are still to be migrated
