### ISSUE TITLE
Gravity Gitcoin grant for round 12

### ISSUE THREAD

**Issue by JuankBell** [CommonsBuild/coordination#920]
## 👇🏽  What is this issue about? Give as much detail as you can. 
We need to decide how are we going to receive the funds coming from the grant, and reach a 100 followers in the "Gravity DAO (@GravityDAO)" twitter, to be able to participate. Inform that until having a better page, the https://tecommons.org/ will be used in the Gitcoin form.

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. We start receiving funds for the sustainability of Gravity, with an address that could be a multisig or a DAO.
2.  We promote Gravity as a project born from the TEC but becoming a public good.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@liviade1 @tamarandom @GriffGreen @sembrestels 

## 👀  Who should be in the loop about this issue?
@Zeptimus @ddan4 @mount-manu

**Comment by GriffGreen** [comment]
YEAH!

**Comment by JuankBell** [comment]
![Captura de Pantalla 2021-10-15 a la(s) 11.08.28 a. m..png](https://images.zenhubusercontent.com/5fb57c9c5472cf79e80e7f7e/73701a75-d5c4-478a-94a4-b534475924c0)
Twitter with 100 followers 
And Github repo: https://app.zenhub.com/workspaces/gravity-614b594733915b001237f06e/board?repos=409276305

**Comment by JuankBell** [comment]
This is the only question that is now blocking this issue. What would be address where funds will be collected? A multsig? custodied by who?

**Comment by JuankBell** [comment]
Multisig created https://gnosis-safe.io/app/#/safes/0xE6439D8bc494f30Eb5afCF7C7Bc9e97bB989225f/balances, now we just need to make a "gravity committee" of people who will manage the funds. This can be done after the Gitcoin grant is created.

**Comment by JuankBell** [comment]
@Razga reviewed it :) https://gitcoin.co/grants/3951/gravity-conflict-management-dao grant inactive but will start for round 12

**Comment by tamarandom** [comment]
Woot!
