### ISSUE TITLE
Kick off Contributor index for Comms 

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#922]
## 👇🏽  What is this issue about? Give as much detail as you can. 
(details to be added by @chuygarcia92 )

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. This should help match creative contributors onboarded into Comms 
2. This should help coordination of creatives and TE comms projects 
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by chuygarcia92** [comment]
Updated document:
https://docs.google.com/spreadsheets/d/1DsjlaW1wBDjBw3OimNrqMvfjwdaGcVWpgMxiAcY3AtE/edit?usp=sharing

**Comment by chuygarcia92** [comment]
we're looking at a solid list of contributors now, so closing this issue :)
