### ISSUE TITLE
Rock the vote: campaign to let Hatchers know we will have a vote on 75% restore deleted governance

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#924]
## 👇🏽  What is this issue about? Give as much detail as you can. 
Staying in tight sync with Comms on this one but there will be a vote from **Sept 24-28** that is very important to the TEC Hatchers. It will have a big impact so we should treat this one with a personal outreach to as many of the Hatchers we can reach. Especially those that were involved in the early discussions!

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. Clear message about what the proposal is, when the vote opens and closes, and what the link is to cast a vote.
2. Messages updating the original and new threads on the Forum
3. Personally reach out to those that were involved in the discussions and solutioning.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
 @liviade1 @JuankBell  @tamarandom

## 👀  Who should be in the loop about this issue?
@Stewards

**Comment by eduardovegap** [comment]
Hello everyone

This is the link to keep track of Hatchers campaigns/outreach, including this one: https://docs.google.com/spreadsheets/d/169yWkwvAI_t1ucN5yRdFK4-EbDuWcIMKazScO-dCw6Q/edit#gid=823281628

**Comment by tamarandom** [comment]
The message itself is here: https://hackmd.io/@FKnVPj1-QQG3HvvH8c3Dow/ryV9iuOQY

**Comment by eduardovegap** [comment]
Accomplished, vote is closed.

**Comment by tamarandom** [comment]
Excellent results! Big thanks again to @eduardovegap and Gene!
