### ISSUE TITLE
Banner update for the "welcome to the TEC" orientation weekly call

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#925]
## 👇🏽  What is this issue about? Give as much detail as you can. 

Hi @danelsuga @MrsBadgerface @eduardovegap 

I just noticed the banner for the rebranded "TEC Orientation" still says it's an AMA. Wondering whether you wanted to have new graphics for that banner? 

![Screen Shot 2021-09-22 at 5.54.47 PM.png](https://images.zenhubusercontent.com/5faaa1d038c6409364f7830c/784cbba1-9f36-44e1-8774-94df1ef8cc1b)

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@Vyvy-vi 

## 👀  Who should be in the loop about this issue?
@

**Comment by danelsuga** [comment]
Thanks. Absolutely. What is this banner? Where can I change it?

**Comment by Vyvy-vi** [comment]
wupps, didn't change that

**Comment by Vyvy-vi** [comment]
We could do 2 things to change the graphic-
- Get a new one. (I think `acidlazzer` has a template for that banner)
OR
- Edit the old banner in a slide here: https://docs.google.com/presentation/d/1A5z5IRhLeVEUgNb-h_USCVFZlmJFp5sDFDUt4QVEZ9Y/edit#slide=id.gcc4dd34b71_0_56
(you could export that slide to an image, and send it to me)

For updating the banner the bot sends, you could upload that image to the github repo over here(and open a Pull Request)- 
https://github.com/Vyvy-vi/TEC-Discord-Automation/tree/main/.github/resources (If you're facing issues in the above, maybe we can sync up on this, and try to make this more easier to update and edit)

**Comment by Vyvy-vi** [comment]
I think it would also make sense to update the text sent in there

**Comment by tamarandom** [comment]
@eduardovegap will update the text. Thanks @Vyvy-vi

**Comment by tamarandom** [comment]
Will be completed as part of #995

**Comment by tamarandom** [comment]
Will be completed as part of #995
