### ISSUE TITLE
Praise Process Description

### ISSUE THREAD

**Issue by kristoferlund** [CommonsBuild/coordination#928]
Who: @divine-comedian plus @kristoferlund 

How does the whole process tie together, from _praise given_ to _TEC in wallet_.

- Community influence, what can the community vote on?
- Reward System Committee, how does that work?
    - Fund requests
    - Payments
Etc.

**Comment by kristoferlund** [comment]
Find Process Description work doc here: https://docs.google.com/document/d/1jkRg3fhF-7ZiYklc1zR9pkt69FqBAWWKc3GaYjdFTaQ/edit

**Comment by divine-comedian** [comment]
live on the forum! 

https://forum.tecommons.org/t/outlining-the-rewards-system-process-v2/646
