### ISSUE TITLE
Choice of backend architecture

### ISSUE THREAD

**Issue by kristoferlund** [CommonsBuild/coordination#932]

**Comment by kristoferlund** [comment]
- Preferred backend platform of @hurek is Java/Spring. Do we paint ourselves into a corner by making that choice? In general, we need make sure we don't become overly reliant on the knowledge of one person.
- What could be alternatives to Java/Spring?
- Is it realistic to make the backend completely event driven? As a way or future proofing it, or rather making it easier to make the step if we want to move to a web3 platform at a later stage?
    - Ceramic seems intreresting
    - Dfinity provides a great dev experience and integrates easily with the eth ecosystem

**Comment by hurek** [comment]
https://spring.io/event-driven <- @kristoferlund 

We have an application for 200 thousand active users written in Java + Spring. It's not even reactive. It is as classic and monolithic as possible. And at the same time as fast as possible. We can use event-driven and microservices, connect kafka or another message broker, but in fact, what you want to do is not such a highly loaded application that would require something very complex. We can invent bicycles as much as we want, the main thing is to understand that it is justified and not to create overheads.

**Comment by kristoferlund** [comment]
I agree @hurek, we should try to keep the stack as simple as possible, this is not a super complex application. There will be no high request loads etc.

I don't want to go too deep into the discussion here but rather let you and @PabloCGL come up with a proposed architecture.

I came to think about some more boundaries/guides: 
- We decided yesterday that one installation = one community. That makes the overall architecture simpler. Plus, we **don't** want to take on hosting other communities praise instances with all that means - support etc.
- Hosting costs are an issue for small communities, ideally we would like to be able to run backend on one of the lower tiers of chosen provider. The ca $10 a month tier that many providers offer.
- Most frontend devs close to CS/TEC work in React. The choice of backend needs to play nicely with that.

**Comment by hurek** [comment]
react is perfectly combined with Java. About the cost. We can setup the database in a container next to the application, but this is a bad practice. It is always better to keep the database somewhere else. And here we have two options. Either we keep the database in the cloud and pay some amount for its rent (5 or 10 dollars), or we keep the database in a container on another server. If we want to save money, we need a person who will constantly monitor the database and make backups. 

In my vision, there is an ideal option:
- server ($10 is enough to place an application, frontend, bots there)
- database (5-10$ plus auto backups). 

The total cost is about 20-30$
@kristoferlund

**Comment by hurek** [comment]
We also need to decide which database we want to work with. I really like PostgreSQL, I'm used to working with it. And Spring Data makes it very convenient to handle this. You can use mongo, but I understand it worse than with PostgreSQL @PabloCGL @kristoferlund

**Comment by Vyvy-vi** [comment]
I'm wondering, if we're having thoughts about Java being a cornered spot, maybe we could consider using expressJs or Nest? (I think we have a reasonable amount of people that could work with Js, moreover, I think performance-wise even though this isn't "the best", but at the same time for anything close to our needs, it should work pretty well). And afaik, most Js backend frameworks play well with React...

**Comment by hurek** [comment]
@Vyvy-vi The React works perfectly with Java/Spring. If you want to develop in Js, then you will have to do it yourself, because I am not so familiar with the JS stack. I am well aware of Spring Data (databases, transactions, etc.), Spring Security and other cool things that will allow you to quickly and reliably develop projects. I am not ready to undertake to develop a project with tech stack, in which I am not sure.

**Comment by hurek** [comment]
I am ready to write bots with JS, Python or another language, because they are "less responsible applications" and it is difficult to make mistakes there (each bot fits in 1 file). But if we talk about the backend, I'm ready to write it only in Java.
