### ISSUE TITLE
Deploy survey, guide-bot & channel list on Discord server

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#938]
## 👇🏽  What is this issue about? Give as much detail as you can. 
There are 3 components that are being updates: survey, guide-bot and channel list.

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. Deploy the new onboarding flow (see #1033)
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
 @eduardovegap @tamarandom @mcsmith89 @gideonro 

## 👀  Who should be in the loop about this issue?
@tamarandom

**Comment by tamarandom** [comment]
Update:

Channel list = done
Guide-bot = done
Survey = in progress

@Vyvy-vi any blockers on the survey I can help with?

**Comment by Vyvy-vi** [comment]
Survey has also been completed.
However, it isn't entirely integrated into the Guide-Bot, for now...
