### ISSUE TITLE
Twitter Scraping

### ISSUE THREAD

**Issue by mount-manu-zz** [CommonsBuild/coordination#946]
## 👇🏽  What is this issue about? Give as much detail as you can. 
Twitter scraping, that is, coding a program that'll extract the unstructured data from thousands of Tweets from dozens of organizations from within our ecosystem or in our direct periphery, as a means to structure it in a way that allows us to do data analysis on it, resulting in (hopefully) valuable insights into underlying reasons and opinions behind a situation or phenomenon. 

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. Deriving valuable insights from the issues people are engaging with; discovering behavioral patterns through sentiment analysis
2. Uncover interesting topics that are being discussed within the cryptoeconomic and token engineering scene and use that knowledge to inform our content production process
3. Gain a clearer sense of who our target audience is (i.e. user research)

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@natenatesoo @divine-comedian 

## 👀  Who should be in the loop about this issue?
@chuygarcia92

**Comment by mount-manu** [comment]
The engineer who was working with me on this had to take care of his father, which became ill, and so this issue is currently on hold.

**Comment by mount-manu** [comment]
The engineer that I was working with postponed delivery due to a family emergency and then went AWOL so I'm closing this.
