### ISSUE TITLE
New feature video for YouTube

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#947]
## 👇🏽  What is this issue about? Give as much detail as you can. 
Now that the Hatch has happened, shall we choose a new Feature video for the YouTube page? 

![Screen Shot 2021-09-29 at 8.02.05 AM.png](https://images.zenhubusercontent.com/5faaa1d038c6409364f7830c/fde38e03-e31a-407e-bd34-7672cee74dc1)

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@Zeptimus @iviangita @chuygarcia92 @mount-manu 

## 👀  Who should be in the loop about this issue?
@

**Comment by Zeptimus** [comment]
yeaah good catch what about the unconference what do you think?

**Comment by tamarandom** [comment]
Nice choice!!

**Comment by Zeptimus** [comment]
Done!
