### ISSUE TITLE
Create template for Snapshot. 

### ISSUE THREAD

**Issue by eduardovegap** [CommonsBuild/coordination#949]
## 👇🏽  What is this issue about? Give as much detail as you can. 

Snapshot or proposals should be standardized a little bit more. And I suggest that it includes how it affects hatchers. 

Also the Template could be sync with the Forum proposals, a workshop may be needed to make it possible. 

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. 
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@liviade1 @tamarandom 

## 👀  Who should be in the loop about this issue?
@

**Comment by tamarandom** [comment]
There is already a template in the Forum (when you submit a proposal). Can we use that exactly? 

Here is a template thank Bankless uses. I came across it on Boardroom. https://docs.google.com/document/d/18IWZ2MwZkmh1XqGmwimiHs3bysm3LIq1ld8X2aYQpt4/edit

**Comment by tamarandom** [comment]
This is an example of the template that PrimeDAO uses: https://docs.google.com/document/d/135ZH2AByCU7cmXbG501Cu4Xl8LgMcJiHpb_-XzhNlzY/edit

**Comment by eduardovegap** [comment]
I love that example @tamarandom, I think the only part that I added but still need rephrasing is the "how the propose guarantee results" 

this is my active working document: https://docs.google.com/document/d/17R-9Ro-rPLWvRNG5gK-sJqnWSFhcICNeeaC-UOEqsYg/edit

**Comment by tamarandom** [comment]
Hi @eduardovegap! Shall we leave this open and pull it into the next sprint to incorporate the changes that were suggested that make sense to you?

**Comment by eduardovegap** [comment]
@tamarandom yes! will label it as next sprint

**Comment by eduardovegap** [comment]
Final document opened for final / grammar review. 

https://docs.google.com/document/d/17R-9Ro-rPLWvRNG5gK-sJqnWSFhcICNeeaC-UOEqsYg/edit

**Comment by tamarandom** [comment]
Dropped in a bunch of edits last night. Thanks @eduardovegap !!

**Comment by tamarandom** [comment]
What are the next steps? I'm thinking:
1) update the forum template
2) create a forum post about the new template
3) add the template to gitbook for easy reference going forward.

@eduardovegap @liviade1 @natenatesoo

**Comment by tamarandom** [comment]
Update: we should have this template linked in Boardroom. @natenatesoo will open new issue for that.
