### ISSUE TITLE
Reimagine Medium: how can we better use it? 

### ISSUE THREAD

**Issue by natenatesoo** [CommonsBuild/coordination#950]
## 👇🏽  What is this issue about? Give as much detail as you can. 
Re-imagining how we distribute community updates associated with our Working Groups.

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. Ensuring that updates are distributed to our Community through Medium
2. Getting more engagement and views on our Medium Page
3. Educating community members.  

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@tamarandom 
@danelsuga 
@JuankBell 

## 👀  Who should be in the loop about this issue?
@chuygarcia92

**Comment by tamarandom** [comment]
Love this! Anyway I can support, holler!

**Comment by tamarandom** [comment]
@natenatesoo I think you and @gideonro are on top of this and have been making huge strides. Going to leave this open since it seems like it is really a recurring task on your plate.

**Comment by natenatesoo** [comment]
Progress has been made with the development of the Writers Guild and the Editorial Board.

**Comment by tamarandom** [comment]
Closing this! It's def in good hands with @gideonro and @natenatesoo
