### ISSUE TITLE
Scaling our community call! Max 25 is not enough!

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#953]
## 👇🏽  What is this issue about? Give as much detail as you can. 
What options do we have for allowing everyone that wants to watch the community call like do it? We hit the 25max limit every community call now. Death by popularity! 

![Screen Shot 2021-09-30 at 8.59.52 PM.png](https://images.zenhubusercontent.com/5faaa1d038c6409364f7830c/19caa713-fd38-4c3a-8374-b61a9dd55deb)

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. Everyone that wants to watch the community call live, can do so.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@chuygarcia92 @Vyvy-vi 

## 👀  Who should be in the loop about this issue?
@GriffGreen @Zeptimus

**Comment by Zeptimus** [comment]
I would second Chuy and use stage and re-structure the community call since it's also something we agreed to improve this sprint.  I think re-structure the call could be done by Comms and or Stewards WG what about a monday meeting to get some ideas on how to draft it? :D

**Comment by tamarandom** [comment]
One of the options: move the community call to another platform.

**Comment by Vyvy-vi** [comment]
I think moving to another platform might be the most feasible option...
Potential choices - 
- Jitsi
- Zoom (free and used by everyone)
- NextCloud (self hosted)
- GoogleMeet (free and used by everyone)
- Wire (self hosted)
- Bevy (paid)
- Element (needs people to have element set up)

**Comment by chuygarcia92** [comment]
I'd also like to propose [Butter](app.butter.us) I think it has great tools that will help keeping each WG under a determined amount of time. Here's their Youtube channel with some demos: 

https://www.youtube.com/channel/UCa0Ibbj5NXV9VKkRVAGPD8A 

And as far as I know it's free to use :)

**Comment by Vyvy-vi** [comment]
That looks neat!
Maybe we can try this out?

**Comment by tamarandom** [comment]
Possible option:
- There is a livestream on YouTube. 
- Someone can join the #can't-join channel and stream it there for those that can't join.

**Comment by tamarandom** [comment]
@natenatesoo volunteers. We can test this out and see if it works!

**Comment by chuygarcia92** [comment]
I feel this might be a config issue in the community hall voice channel, since we held an AMA in the Agave server with over 100 people in the room and we were able to share a screen with a presentation, it's also logical that we could even achieve more than this since we're all the way up in NITRO 🔥

**Comment by Vyvy-vi** [comment]
While livestreaming with 100 people works, Video Calls strictly have a 25 member cap, afaik.

**Comment by natenatesoo** [comment]
Update?

**Comment by eduardovegap** [comment]
No solution have been found. No need to it at the moment, so it will be closed.
