### ISSUE TITLE
Steward POAP

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#956]
## 👇🏽  What is this issue about? Give as much detail as you can. 
We should have a TEC Steward POAP.

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by tamarandom** [comment]
Thanks to @acidlazzer for doing this on the down low so we could make it a surprise for all!

**Comment by acidlazzer** [comment]
Glad to be part of this!
