### ISSUE TITLE
Steward's Engagement Report

### ISSUE THREAD

**Issue by mount-manu-zz** [CommonsBuild/coordination#963]
## 👇🏽  What is this issue about? Give as much detail as you can. 
Talking to one of the leads at Gitcoin's Memes, Merch, and Marketing (MMM) Workstream, I've come to find that their DAO has Steward Report cards! The idea is for it to gather and display the following values:
- Steward's initiation date
- Number of forum posts authored
- Steward's Workstream (i.e. Working Group) 
- Steward's voting weight
- Steward's % of participation in votes
- (This is a non-exhaustive list: more parameters to be added)

The objective of this is accountability, sure, but it'll also help illuminate the aggregate amount of work that Stewards do, which is sometimes taken for granted and is always hard to put into perspective. Ideally it'll also serve as a guiding post for how much time and work it takes to be a Steward.

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. Designing the UI/UX for the Steward Report Cards' web page
2. Coding the Steward Report Cards' web page, front end and back end, and syncing it with whatever databases and wallets it would fetch data from
3.  Maintaining the Steward Report Cards' web page so that it's updated in real-time (or close enough)

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@chuygarcia92 @Zeptimus @iviangita 

## 🔗  Are there links or docs related to this issue?
Gitcoin's DAO Steward Report Cards:
https://www.daostewards.xyz/

**Comment by liviade1** [comment]
@liviade1

**Comment by tamarandom** [comment]
Nice!!  💜   Looking at Gitcoin's, this looks like a good chunk of work but in terms of transparency, it's right on!! Might I suggest the first step should be a proposal that estimates the budget and timeline for this work?

**Comment by mount-manu-zz** [comment]
This is not a priority for me right now, nor have I dedicated any hours to this, so I'll close this for now and revisit it later if the community deems it a worthy pursuit.
