### ISSUE TITLE
Revisit the Transparency Audit process

### ISSUE THREAD

**Issue by iviangita** [CommonsBuild/coordination#964]
## 👇🏽  What is this issue about? Give as much detail as you can. 
We're revisiting the audit process and see how we can improve it. Here's our working document: https://docs.google.com/document/d/1IgG94l6cCO3d0Zrfsi6ucUEp99A96P_s2uOTQhmB-Tc/edit?usp=sharing

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@Zeptimus 

## 👀  Who should be in the loop about this issue?
@

**Comment by iviangita** [comment]
This is already a work in progress: https://docs.google.com/document/d/1IgG94l6cCO3d0Zrfsi6ucUEp99A96P_s2uOTQhmB-Tc/edit?usp=sharing

**Comment by Zeptimus** [comment]
Done, next step its deploy it

**Comment by iviangita** [comment]
The new approach is posted on the forum for advice process: https://forum.tecommons.org/t/transparency-audit-report-a-new-approach/673
