### ISSUE TITLE
start to work on decision making visuals/ infographics 

### ISSUE THREAD

**Issue by liviade1** [CommonsBuild/coordination#969]
## 👇🏽  What is this issue about? Give as much detail as you can. 
@chuygarcia92 offered help as well 🙏

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by chuygarcia92** [comment]
@acidlazzer will be supporting this issue

**Comment by liviade1** [comment]
We are working on the flow here - Catarina will be jumping in to help with the design too, I'll connect you with her also @acidlazzer 
https://miro.com/app/board/o9J_lYcRTik=/
