### ISSUE TITLE
TEC x KfW Bankengruppe: TE for Structural Poverty Alleviation

### ISSUE THREAD

**Issue by mount-manu-zz** [CommonsBuild/coordination#970]
## 👇🏽  What is this issue about? Give as much detail as you can. 
<working on description, will update soon>

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by innov8tor3** [comment]
Is the Grassroots Economics tag related to the actual organisation based in Kenya, led by Will Ruddick? Or is that just coincidence?

The basis of the Kenyan organisation is formed around true mutual credit. MC indeed works best when capital is scarce, and is counter cyclical in nature to the money economy, based on my work with a UK based MC group.

We know one other large scale incidence, based in Slovenia, that has been running since the partition of Yugoslavia.

**Comment by mount-manu-zz** [comment]
Yes @innov8tor3 this issue is related to them. This is still in the early stages but the idea is to incentivize microfranchise development through token engineering. 

I'm of the opinion that, once you have a stable currency backed by mutual credit (like they do), the next step is to build grassroots business systems that equip people with the necessary skills needed to grow a successful micro-enterprise, addressing both the lack of jobs _and_ the lack of goods and services available to the poor. Through this structural approach, we are enabling people to become economically self-reliant.

Gifting a person a fish VS giving them a fishing rod VS building a fishing rod-factory where the fishers gradually become the owners...

**Comment by csggene3** [comment]
So this type of application imo is the true "killer app" for token engineering and obviously the ultimate endgame for any tokenomics system hoping for truly widespread adoption ie beyond the first world. I'm currently trying to help a couple friends I've made in Africa get into some kind of UBI project, but the projects like Proof of Humanity still have a long way to go. Microfranchise development seems like it would be much more feasible in the short term considering blockchain options like WAX with custodial wallets, simple (nearly no code) contract tools, and 0 transaction fees (this is done by staking wax for "CPU", and there are some caveats like needing to purchase "RAM", but with enough volume or structuring transactions the cost can be driven towards 0). The tools are centered around NFTs, but there's no reason why limited numbers of NFTs could not represent redemptions for physical goods by vendors, with individual communities utilizing their own exchange token, and perhaps a special exchange to support all exchange tokens aggregated values against fiat and traditional trade pairs. The difficulty though is obviously that the process of educating and enabling end users is much more complex than distributing sticks and string for fishing poles, with a kindly nudge towards the waterfront, as I know we are all aware. But I do think there are potentially ways to integrate the technology on the backend, and remove it from the front end to improve adoption, like printing unitized or denominated "paper wallets" and imagining a semi-physical crypto system or partial "pseudo fiat" system with merchant centered aggregation points for redemption or distribution of paper. This would enable truly "off-chain" (literally paper hand-to-hand) transactions at almost 0 cost (paper still costs a little bit) and still allowing for a functioning distributed ledger system with a portion perpetually existing in a no-tech, no-electricity environment.

**Comment by mount-manu-zz** [comment]
This is more along the lines of Giveth's MVV so I'll close this for now.
