### ISSUE TITLE
Animated TEC Discord icon

### ISSUE THREAD

**Issue by acidlazzer** [CommonsBuild/coordination#975]
## 👇🏽  What is this issue about? Give as much detail as you can. 
This can help to add more personality to the discord server and take advantage of the tools provided by the plataform.

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. TEC discord server icon is animated
2. People like it
3. It´s cool :D

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by tamarandom** [comment]
Nice! CC: @Vyvy-vi

**Comment by Vyvy-vi** [comment]
Yes 💯 
That would be awesome!

Would @acidlazzer or anyone else be interested in making a GIF for the animated server icon?

**Comment by acidlazzer** [comment]
I´m working on that! :D

**Comment by chuygarcia92** [comment]
@acidlazzer is the coolest guy ![logo tec gif.gif](https://images.zenhubusercontent.com/6000e68bc28f519103606a04/65b2a55f-61de-48c3-ae1e-27383ed99035)
