### ISSUE TITLE
Recording Communitas call

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#977]
## 👇🏽  What is this issue about? Give as much detail as you can. 
There is a new time for the Communitas call. Is is not at 8pm CET every Monday. 

@Zeptimus and @iviangita what's the best way to get this into a recording schedule> @eduardovegap mentioned he started the recording bot but .... did we do it right!? ;)

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. Communitas WG meetings (audio or video) are available on TEC YouTube page
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by Zeptimus** [comment]
yeah i checked it it didnt get well recorded, for next one i can just put my other cumputer on the meeting but ill be on common swarm (the real me haha :D)

**Comment by tamarandom** [comment]
Ah, too bad. It was electric. Maybe it's time for you to get me recording too. 😆  I will be in this call for the coming number of weeks and can commit to doing the recordings (just need help knowing how!)

**Comment by Zeptimus** [comment]
Yeah!!! lets have a quick call for setting up obs before next comunitas call let me know when is it a good. I feel late mornings should work very good for us since there is no many calls there :p

**Comment by tamarandom** [comment]
Hey @Zeptimus @iviangita - I was not able to get OBS to either window or display capture on either my desktop or laptop today! Sorry but I think I am not going to be able to record the Communitas call today. The audio works fine, which can be a last resort option.

**Comment by Zeptimus** [comment]
dw i got ur back 🤜🤛

**Comment by eduardovegap** [comment]
How do we resolve this in a way that's reliable? :D

**Comment by Zeptimus** [comment]
Ivy it's taking care and if she someday cant i can back her i think we can close this one

**Comment by iviangita** [comment]
I'm taking this :)

**Comment by tamarandom** [comment]
@iviangita @Zeptimus I figured out how to make it work on osx:
"Security & Privacy > Screen Recording > check OBS icon"

So I will be recording Communitas tonight!
