### ISSUE TITLE
Swag shop "Processing" error - HELP!

### ISSUE THREAD

**Issue by iviangita** [CommonsBuild/coordination#981]
## 👇🏽  What is this issue about? Give as much detail as you can. 
People get stuck at the final final step of order submission in our [swag shop](https://swag.tecommons.org/#/checkout/payment), which is built on Origin Protocol. After clicking "Payment", it stops at "Processing" stage.

![image.png](https://images.zenhubusercontent.com/5fb5cba95f94b9eb73a91fe5/bf41d661-3821-4c50-a2e9-367a0cad7863)

@tamarandom came across this same issue on Origin Protocol's discord server in the dshop support channel.

![image.png](https://images.zenhubusercontent.com/5fb5cba95f94b9eb73a91fe5/ce860c1b-7656-4fe0-94f0-5870603e62b0)

And this is how it looks like on our shop 👇🏽

![image.png](https://images.zenhubusercontent.com/5fb5cba95f94b9eb73a91fe5/421db902-1cf8-429d-80ac-e233460b24da)

**Are there devs in our community who can possibly help us? Origin Protocol already stopped supporting their platform. Should we migrate to another platform? We're open to suggestions** 

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. Fix the "Processing" error
2. Orders go through successfully to Printful
3. 

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@tamarandom 

## 👀  Who should be in the loop about this issue?
@

**Comment by tamarandom** [comment]
Hi @iviangita ! Amin reached out to me as he has been unable to make a purchase from the shops for the last few days. Without someone that can fix this, we are going to need to take the shops down. ;( 

I would propose throwing out a **call for help** on both the TEC and CS discord servers but in the mean time we should probably take these frontends down so that they are not wasting people's time. 

CC: @kristoferlund @Vyvy-vi @geleeroyale

**Comment by geleeroyale** [comment]
Are you sure? Of course I can take them down immediately

**Comment by tamarandom** [comment]
@geleeroyale - We have found a glimmer of hope so let's hold off for another couple of days. But if this solution does not work, then, yes, we will have to take down all three of the shops.

**Comment by tamarandom** [comment]
Wow. We're back in business! 
![Screen Shot 2021-10-15 at 1.43.57 PM.png](https://images.zenhubusercontent.com/5faaa1d038c6409364f7830c/1a07279e-41c0-4623-b151-6653868330a4)
