### ISSUE TITLE
Assign quantifiers

### ISSUE THREAD

**Issue by kristoferlund** [CommonsBuild/coordination#983]
## Rules

![image](https://user-images.githubusercontent.com/9698363/136383052-512f09f9-a2bb-4170-a432-c8982788ff9f.png)

**Comment by kristoferlund** [comment]
@hurek and @PabloCGL, check the suggested formula for determining "min pool size". Does it work?

**Comment by PabloCGL** [comment]
The formula makes sense to me, but the math in the examle is slightly off 😁

**Comment by kristoferlund** [comment]
Issue moved to [CommonsBuild/praise_backend #16](https://github.com/CommonsBuild/praise_backend/issues/16) via [**ZenHub**](https://www.zenhub.com/)
