### ISSUE TITLE
Setup sesh.fyi on our Discord! // Testing Discord Events!

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#995]
## 👇🏽  What is this issue about? Give as much detail as you can. 
The sesh bot is a took we can plug in to handle the event announcements much more easily. 
https://sesh.fyi/

We can test it out and see if it works for us!

We might lost the image banner but this tool allows us to follow exact calendar events so that changes to the calendar (bi-weekly, for example) are automatically accounted for without manual update.

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. Test out sesh.fyi
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by tamarandom** [comment]
@Vyvy-vi and I have tested this out in the last Sprint. We will roll it out this Sprint. There are some tweaks and changes that is necessary to make but we hope to make it as smooth as we can.

**Comment by tamarandom** [comment]
Tracking the rollouts here: https://docs.google.com/spreadsheets/d/1ZSUA8zYOJdkb2HTCAXVlZwHfBSMGbxLEnSOWFeCry3k/edit

**Comment by tamarandom** [comment]
Hey @ZarMarquez this is the one I would LOVE your help with! I will need to show you what it entails. Shouldn't take more than 30 minutes or so though and will be a good time for us to hang out and get to know each other!

**Comment by tamarandom** [comment]
Hey @Vyvy-vi I am testing out Discord Events you shared. Setup the Communitas call tomorrow. The event is setup. There isn't a repeat option. And it doesn't say there will be any reminder. Discord will probably be building out the features for this but for the present, we would still need another option for the banner call reminders.

And it looks like it just shows up here in this event channel:
 ![Screen Shot 2021-11-14 at 6.17.37 PM.png](https://images.zenhubusercontent.com/5faaa1d038c6409364f7830c/2df74027-e5e2-482f-aa62-ca2e0860b8a0)

**Comment by ZarMarquez** [comment]
> entails

Sounds good @tamarandom! I'm more than happy to help with this. I'll poke around their website to get a better grasp before we meet. My schedule is pretty flexible, let know what works best for you.

**Comment by Ionneto** [comment]
Just fell in here by coincidence when looking for some sesh info, being using it for some months now in communities I manage and can tell you that I haven't found a single better tool for this goal, even discord events ain't nowhere close to it yet.

Reach me as Zeugh#0001 on disc if you need any help with it

**Comment by tamarandom** [comment]
Hey @ionneto That's great! The main issue we ran into testing it out was the posting on the channel immediately after the end of the call. It looks like scheduling the posting on a channel (for example, an hour before the call starts) is on their roadmap but not available yet.

**Comment by Ionneto** [comment]
I'm not really sure what you mean by that. In JuiceboxDAO we have a specific events channel where it has all the upcoming agenda and it always has the last message being the full list of events, then anyone can click any of the links and RSVP to the event they want. 

Not ideal maybe, and not in the best possible place, but the !link option that connects it to google agenda kind of solves it for everyone to always be on the loop of what's coming in the next few days and the DMing of alerts for events you RVSPd also helps

**Comment by tamarandom** [comment]
I went to have a look. Like this....right? Yeah, we may have to deprioritize the call reminders on the channel itself. Thanks for chiming in, @Ionneto, really appreciate hearing this feedback!
![Screen Shot 2021-11-18 at 10 00 28 AM](https://user-images.githubusercontent.com/703624/142384003-f235bcd0-f145-4598-8520-903988ddfd3e.png)

**Comment by tamarandom** [comment]
We're going to pause on sesh.fyi and use Discord events. @Vyvy-vi are there any server side actions to make needed to disable or delete sesh? Let's do it then close this!

**Comment by tamarandom** [comment]
@Vyvy-vi kicked the bot. Solved.
